{
  "hash": "966334e5ec3912af2fe1d1501bd97f08",
  "result": {
    "markdown": "---\ntitle: \"EDA Assignment 7: Chapter 9\"\nauthor: \"Sangwon Ju, Yonsei Public Administration\"\ndate: 'JUNE/3/2021'\npage-layout: full\nformat: \n    html\ncategories: \n    \"Exploratory Data Analysis (2021 Spring) [in Korean]\"\nimage: \"image.png\"\n---\n\n\n9장. 로버스트 선형회귀\n\n# 1번\n\nR의 trees 자료를 이용하여 다음을 수행하여라.\n\n## (가)\n\nVolume을 Y축에, Height를 X축에 그리고 또한 Volume을 Y축에, Girth를 X축에 그린 후 두 그래프에서 자료들판단)이 직선으로 모형을 세우기 적합한 지, 선형성이 어떤 것이 더 강한지 비교하여라. (눈으로 판단)\n\n\n::: {.cell}\n\n```{.r .cell-code}\npacman::p_load(\"skimr\",\"tidyverse\")\ntrees %>% glimpse()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nRows: 31\nColumns: 3\n$ Girth  <dbl> 8.3, 8.6, 8.8, 10.5, 10.7, 10.8, 11.0, 11.0, 11.1, 11.2, 11.3, …\n$ Height <dbl> 70, 65, 63, 72, 81, 83, 66, 75, 80, 75, 79, 76, 76, 69, 75, 74,…\n$ Volume <dbl> 10.3, 10.3, 10.2, 16.4, 18.8, 19.7, 15.6, 18.2, 22.6, 19.9, 24.…\n```\n:::\n\n```{.r .cell-code}\nskimr::skim(trees)\n```\n\n::: {.cell-output-display}\nTable: Data summary\n\n|                         |      |\n|:------------------------|:-----|\n|Name                     |trees |\n|Number of rows           |31    |\n|Number of columns        |3     |\n|_______________________  |      |\n|Column type frequency:   |      |\n|numeric                  |3     |\n|________________________ |      |\n|Group variables          |None  |\n\n\n**Variable type: numeric**\n\n|skim_variable | n_missing| complete_rate|  mean|    sd|   p0|   p25|  p50|   p75| p100|hist  |\n|:-------------|---------:|-------------:|-----:|-----:|----:|-----:|----:|-----:|----:|:-----|\n|Girth         |         0|             1| 13.25|  3.14|  8.3| 11.05| 12.9| 15.25| 20.6|▃▇▃▅▁ |\n|Height        |         0|             1| 76.00|  6.37| 63.0| 72.00| 76.0| 80.00| 87.0|▃▃▆▇▃ |\n|Volume        |         0|             1| 30.17| 16.44| 10.2| 19.40| 24.2| 37.30| 77.0|▇▅▁▂▁ |\n:::\n\n```{.r .cell-code}\nsum(is.na(trees)) # 결측치 없음\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0\n```\n:::\n\n```{.r .cell-code}\nplot(y=trees$Volume,x=trees$Height,main=\"Linearity of volume and height\",xlab=\"height\",ylab=\"volume\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-1-1.png){width=672}\n:::\n\n```{.r .cell-code}\nplot(y=trees$Volume,x=trees$Girth,main=\"Linearity of volume and girth\",xlab=\"girth\",ylab=\"volume\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-1-2.png){width=672}\n:::\n:::\n\n\n첫번째 자료의 경우 경향성이 따로 나타나지 않는 것으로 보인다. 두 Plot을 비교할 경우 두번째 자료(volume,girth)가 직선으로 모형으로 세우기 적합하다고 본다. X축과 Y축의 선형성 또한 두번째 자료가 더 강하게 나타나는 것으로 보인다.\n\n## (나)\n\n각각 r-line을 적합 시킨 후 그래프 위에 그려라. 각기 잔차를 구하여 y-hat vs. residual plot을 그리고 적합 타당성을 판단하고 비교하여라.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 첫번째 플롯에 대해서\nplot(y=trees$Volume,x=trees$Height,main=\"Linearity of volume and height\",xlab=\"height\",ylab=\"volume\")\n(z1 <- line(x=trees$Height,y=trees$Volume))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nline(x = trees$Height, y = trees$Volume)\n\nCoefficients:\n[1]  -115.118     1.918\n```\n:::\n\n```{.r .cell-code}\nabline(coef(z1))\nz1.ls <- lm(trees$Volume ~ trees$Height)\nabline(z1.ls$coef, lty=2,col=\"red\")\nlegend(x = 63, y = 72, c(\"R - Line\", \"Regression\"), \n       lty=c(1,2),lwd=2,col = c(\"black\",\"red\"),cex=0.7)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# Tukey-Tree Plot :\nplot(residuals(z1) ~ fitted(z1), main = \"Residual plot by rline:Volume~Height\")\nabline(0,0)       \n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-2-2.png){width=672}\n:::\n\n```{.r .cell-code}\nboxplot(residuals(z1)) # outlier 없음\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-2-3.png){width=672}\n:::\n\n```{.r .cell-code}\n# 두번째 플롯에 대해서\nplot(y=trees$Volume,x=trees$Girth,main=\"Linearity of volume and girth\",xlab=\"girth\",ylab=\"volume\")\n(z2 <- line(x=trees$Girth,y=trees$Volume))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nline(x = trees$Girth, y = trees$Volume)\n\nCoefficients:\n[1]  -36.585    5.046\n```\n:::\n\n```{.r .cell-code}\nabline(coef(z2))\nz2.ls <- lm(trees$Volume ~ trees$Girth)\nabline(z2.ls$coef, lty=2,col=\"red\")\nlegend(x = 8.5, y = 71, c(\"R - Line\", \"Regression\"), \n       lty=c(1,2),lwd=2,col = c(\"black\",\"red\"),cex=0.7)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-2-4.png){width=672}\n:::\n\n```{.r .cell-code}\n# Tukey-Tree Plot :\nplot(residuals(z2) ~ fitted(z2), main = \"Residual plot by rline: Volume~Height\")\nabline(0,0)    \n\n# 이차함수를 따를지도 모른다.\nk=seq(-100,100,0.1)\na<-function(x) {((1/50)*(x-35)^2)-8}\nlines(a(k)~k)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-2-5.png){width=672}\n:::\n\n```{.r .cell-code}\nboxplot(residuals(z2)) # outlier 없음\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-2-6.png){width=672}\n:::\n:::\n\n\n첫번째 Plot의 경우 이 분산성이 발생하는 것으로 보인다. Y_hat이 작을 때에는 잔차의 폭이 좁았는데 점점 커질수록 잔차의 폭이 넓어지고 있는 모습을 보이고 있다는 점에서 그러하다. Ideal한 Residual Plot은 띠 모양으로 Plot의 점들이 x축에 평행한 직선을 이루어야 하는데 Plot에서의 잔차는 점차 늘어나고 있다는 점에서 Transformation을 통해 잔차를 조정해야 한다.\n\n두번째 Plot의 경우에도 점들이 x축에 평행하게 모여있지는 않고 일종의 Qudratic Form (2차함수) 곡선을 이루고 있는 것으로 보인다.Ideal한 Residual Plot은 띠 모양으로 Plot의 점들이 x축에 평행 직선을 이루어야 하는데 실제 Plot의 모양은 곡선을 이루고 있는 것으로 보아 변수 들을 변환한다면 현재의 잔차들이 가지고 있는 경향성을 완화할 수 있을 것이라고 생각한다.\n\n## (다)\n\nVolume \\~ Height plot에서 직선화하기 위한 재표현을 시행착오 방법으로 찾아라. Volume만 변환시켜 보아라. Height만 변환시켜 보아라. 시행착오 과정을 모두 수록하여라.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 단순화\nattach(trees)\nmedHeight <- as.vector(3)\nmedVolume <- as.vector(3)\nmedHeight[1] <- median(Height[1:10]); medVolume[1] <- median(Volume[1:10])\nmedHeight[2] <- median(Height[11:21]); medVolume[2] <- median(Volume[11:21])\nmedHeight[3] <- median(Height[22:31]); medVolume[3] <- median(Volume[22:31])\nplot(medVolume~medHeight, type=\"b\",main=\"MedVolume~MedHeight\")   # \"b\"= both points and line\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n\n```{.r .cell-code}\ndetach(trees)\n\n# 시행착오\n# 먼저 Y변수에 대해서 큰부분을 작게 작은 부분을 크게 만드는 변환\nplot(y=sqrt(trees$Volume),x=trees$Height,main=\"Linearity of sqrt(volume) and height\",xlab=\"height\",ylab=\"sqrt volume\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-3-2.png){width=672}\n:::\n\n```{.r .cell-code}\nplot(y=log(trees$Volume),x=trees$Height,main=\"Linearity of log(volume) and height\",xlab=\"height\",ylab=\"log volume\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-3-3.png){width=672}\n:::\n\n```{.r .cell-code}\n# X변수에 대해서 변환을 진행\nplot(y=trees$Volume,x=(trees$Height)^2,main=\"Linearity of volume and height squares\",xlab=\"height squares\",ylab=\"volume\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-3-4.png){width=672}\n:::\n\n```{.r .cell-code}\n# 책에서 제시한 변환법\nvh=trees$Volume/trees$Height\nplot(y=vh,x=trees$Height,main=\"Linearity of volume/height and height\",xlab=\"height\",ylab=\"volume/height\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-3-5.png){width=672}\n:::\n\n```{.r .cell-code}\n# Volume만 변화시키기\n# 1) y에 Sqrt 씌우기\n\nplot(y=sqrt(trees$Volume),x=trees$Height,main=\"Linearity of sqrt(volume) and height\",xlab=\"height\",ylab=\"sqrt volume\")\n(z3 <- line(x=trees$Height,y=sqrt(trees$Volume)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nline(x = trees$Height, y = sqrt(trees$Volume))\n\nCoefficients:\n[1]  -7.7958   0.1693\n```\n:::\n\n```{.r .cell-code}\nabline(coef(z3))\nz3.ls <- lm(sqrt(trees$Volume) ~ trees$Height)\nabline(z3.ls$coef, lty=2,col=\"red\")\nlegend(x = 63, y = 8.5, c(\"R - Line\", \"Regression\"), \n       lty=c(1,2),lwd=2,col = c(\"black\",\"red\"),cex=0.7)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-3-6.png){width=672}\n:::\n\n```{.r .cell-code}\n# 2) y에 Log 씌우기\n\nplot(y=log(trees$Volume),x=trees$Height,main=\"Linearity of log(volume) and height\",xlab=\"height\",ylab=\"log volume\")\n(z4 <- line(x=trees$Height,y=log(trees$Volume)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nline(x = trees$Height, y = log(trees$Volume))\n\nCoefficients:\n[1]  -1.39776   0.06068\n```\n:::\n\n```{.r .cell-code}\nabline(coef(z4))\nz4.ls <- lm(log(trees$Volume) ~ trees$Height)\nabline(z4.ls$coef, lty=2,col=\"red\")\nlegend(x = 63, y = 4.2, c(\"R - Line\", \"Regression\"), \n       lty=c(1,2),lwd=2,col = c(\"black\",\"red\"),cex=0.7)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-3-7.png){width=672}\n:::\n\n```{.r .cell-code}\n# 3) x에 제곱 씌우기\nplot(y=trees$Volume,x=(trees$Height)^2,main=\"Linearity of volume and height squares\",xlab=\"height squares\",ylab=\"volume\")\n(z5 <- line(x=(trees$Height)^2,y=trees$Volume))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nline(x = (trees$Height)^2, y = trees$Volume)\n\nCoefficients:\n[1]  -43.3710    0.0127\n```\n:::\n\n```{.r .cell-code}\nabline(coef(z5))\nk=(trees$Height)^2\nz5.ls <- lm(trees$Volume ~k )\nabline(z5.ls$coef, lty=2,col=\"red\")\nlegend(x = 4000, y = 72, c(\"R - Line\", \"Regression\"), \n       lty=c(1,2),lwd=2,col = c(\"black\",\"red\"),cex=0.7)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-3-8.png){width=672}\n:::\n\n```{.r .cell-code}\n# 4) Huh\nvh=trees$Volume/trees$Height\nplot(y=vh,x=trees$Height,main=\"Linearity of volume/height and height\",xlab=\"height\",ylab=\"volume/height\")\n(z6 <- line(x=trees$Height,y=vh))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nline(x = trees$Height, y = vh)\n\nCoefficients:\n[1]  -1.12720   0.01978\n```\n:::\n\n```{.r .cell-code}\nabline(coef(z6))\nz6.ls <- lm(vh~trees$Height)\nabline(z6.ls$coef, lty=2,col=\"red\")\nlegend(x = 64, y = 0.85, c(\"R - Line\", \"Regression\"), \n       lty=c(1,2),lwd=2,col = c(\"black\",\"red\"),cex=0.7)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-3-9.png){width=672}\n:::\n:::\n\n\n총 네가지 방법으로 변환을 진행해 보았는데 4가지 표현 중 x변수를 변환하는 방법의 경우 r-line 위쪽 부분의 점들이 어느정도 r-line에 평행하게 선형성을 보이고 있으나 밑부분의 점들은 선형적이지 않아 선택하지 않았다. y변수에 대한 변환 중 log와 sqrt를 비교할 경우 log 변환을 한 Plot의 가장 큰 점인 (90,4.5) 부근에 한 점이 가장자리 점들을 기준으로 한 선위에서 약간 벗어난 것으로 보이기 때문에 y변수에 대한 sqrt 변환이 log변환에 비해서 적합하다고 판단하였다.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(y=log(trees$Volume),x=log(trees$Height),main=\"Linearity of log(volume) and log(height)\",xlab=\"log height\",ylab=\"log volume\")\n(z7 <- line(x=log(trees$Height),y=log(trees$Volume)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nline(x = log(trees$Height), y = log(trees$Volume))\n\nCoefficients:\n[1]  -16.582    4.573\n```\n:::\n\n```{.r .cell-code}\nabline(coef(z7))\nz7.ls <- lm(log(trees$Volume) ~ log(trees$Height))\nabline(z7.ls$coef, lty=2,col=\"red\")\nlegend(x = 4.15, y = 4.15, c(\"R - Line\", \"Regression\"), \n       lty=c(1,2),lwd=2,col = c(\"black\",\"red\"),cex=0.7)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n\n```{.r .cell-code}\nplot(y=sqrt(trees$Volume),x=sqrt(trees$Height),main=\"Linearity of sqrt(volume) and sqrt(height)\",xlab=\"sqrt height\",ylab=\"sqrt volume\")\n(z8 <- line(x=sqrt(trees$Height),y=sqrt(trees$Volume)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nline(x = sqrt(trees$Height), y = sqrt(trees$Volume))\n\nCoefficients:\n[1]  -20.50    2.94\n```\n:::\n\n```{.r .cell-code}\nabline(coef(z8))\nz8.ls <- lm(sqrt(trees$Volume) ~ sqrt(trees$Height))\nabline(z8.ls$coef, lty=2,col=\"red\")\nlegend(x = 8, y = 8.5, c(\"R - Line\", \"Regression\"), \n       lty=c(1,2),lwd=2,col = c(\"black\",\"red\"),cex=0.7)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-4-2.png){width=672}\n:::\n:::\n\n\n추가로 x축 y축 전부에 log와 sqrt 변환을 적용하였는데 위의 변환들 보다 잔차들이 안정되어진 것으로 추정된다.\n\n## (라)\n\n(다)에 찾은 변환으로 각기 r-line으로 적합하고 residual plot, residual의 boxplot, stem-and-leaf display 등으로 적합성를 비교하여라.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nplot(residuals(z3) ~ fitted(z3), main = \"Residual plot by rline:sqrt(volume) ~ height\")\nabline(0,0)    \n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n\n```{.r .cell-code}\nplot(residuals(z4) ~ fitted(z4), main = \"Residual plot by rline:log(volume) ~ height\")\nabline(0,0) \n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-5-2.png){width=672}\n:::\n\n```{.r .cell-code}\nplot(residuals(z5) ~ fitted(z5), main = \"Residual plot by rline:volume ~ height^2\")\nabline(0,0)    \n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-5-3.png){width=672}\n:::\n\n```{.r .cell-code}\nplot(residuals(z6) ~ fitted(z6), main = \"Residual plot by rline:volume/height ~ height\")\nabline(0,0) \n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-5-4.png){width=672}\n:::\n\n```{.r .cell-code}\nplot(residuals(z7) ~ fitted(z7), main = \"Residual plot by rline:log volume ~ log height\")\nabline(0,0) \n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-5-5.png){width=672}\n:::\n\n```{.r .cell-code}\nplot(residuals(z8) ~ fitted(z8), main = \"Residual plot by rline:sqrt volume ~ sqrt height\")\nabline(0,0) \n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-5-6.png){width=672}\n:::\n:::\n\n\n그러나 Residual plot을 그려볼 경우 여러 변환들 중 적합해 보이는 것은 y변수에 대한 log 변환인 것으로 보인다. 나머지 변환의 경우 직선 밑 부분의 점들이 점점 줄어들고 있는 경향성이 나타나고 있는데 그럴경우 적합하지 않은 변환이기 때문이다\n\ny변수에만 log변환을 한 경우를 다른 Residual plot을 비교할 경우 미묘한 차이지만 맨위에 있는 4개의 점들이 줄어드는 경향성이 있고 마지막점의 이상성이 다소 있다는 점에서 단점이 있지만 전반적인 Residual Plot을 비교하면 log가 가장 적정해 보인다.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nboxplot(residuals(z3),main=\"Residual boxplot of sqrt(volume) ~ height\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n\n```{.r .cell-code}\nboxplot(residuals(z4),main=\"Residual boxplot of log(volume) ~ height\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-6-2.png){width=672}\n:::\n\n```{.r .cell-code}\nboxplot(residuals(z5),main=\"Residual boxplot of volume ~ height^2\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-6-3.png){width=672}\n:::\n\n```{.r .cell-code}\nboxplot(residuals(z6),main=\"Residual boxplot of volume/height ~ height\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-6-4.png){width=672}\n:::\n\n```{.r .cell-code}\nboxplot(residuals(z7),main=\"Residual boxplot of xy log\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-6-5.png){width=672}\n:::\n\n```{.r .cell-code}\nboxplot(residuals(z8),main=\"Residual boxplot of xy sqrt\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-6-6.png){width=672}\n:::\n:::\n\n\n첫번째, 두번째 boxplot의 경우 median이 lower hinge쪽에 더 가까운 것으로 보인다. 또 Whisker의 길이도 lower whisker쪽이 더 길게 나타나고 있다. Whisker의 길이와 Box내의 대칭성의 경우 3번째 Boxplot이 가장 대칭적인 것으로 보인다. 그럼에도 불구하고 log변환에서 대칭성이 크게 감소하지는 않았다는 점에서 사용 가능한 변환으로 보인다.\n\nx변수와 y변수에 동시에 log변환을 취한 boxplot이 y변수에만 log변환을 취한 boxplot에 비해서 whisker의 길이가 대칭적이 된 것으로 보인다.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstem(residuals(z3))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  The decimal point is at the |\n\n  -1 | 865\n  -1 | 0\n  -0 | 887655\n  -0 | 443100\n   0 | 3\n   0 | 5678\n   1 | 33444\n   1 | 58899\n```\n:::\n\n```{.r .cell-code}\nstem(residuals(z4))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  The decimal point is 1 digit(s) to the left of the |\n\n  -6 | 6\n  -4 | 821\n  -2 | 454110\n  -0 | 77650\n   0 | 014\n   2 | 174\n   4 | 4688900\n   6 | 173\n```\n:::\n\n```{.r .cell-code}\nstem(residuals(z5))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  The decimal point is 1 digit(s) to the right of the |\n\n  -2 | 431\n  -1 | 55\n  -1 | 20\n  -0 | 9999866\n  -0 | 40\n   0 | 1344\n   0 | 5\n   1 | 01344\n   1 | 566\n   2 | 04\n```\n:::\n\n```{.r .cell-code}\nstem(residuals(z6))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  The decimal point is 1 digit(s) to the left of the |\n\n  -2 | 864\n  -1 | 7631100\n  -0 | 99764\n   0 | 034678\n   1 | 56889\n   2 | 14579\n```\n:::\n\n```{.r .cell-code}\nstem(residuals(z7))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  The decimal point is 1 digit(s) to the left of the |\n\n  -6 | 4\n  -4 | 818\n  -2 | 46111\n  -0 | 887764\n   0 | 007\n   2 | 084\n   4 | 5789900\n   6 | 178\n```\n:::\n\n```{.r .cell-code}\nstem(residuals(z8))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  The decimal point is at the |\n\n  -1 | 965\n  -1 | 0\n  -0 | 98776655\n  -0 | 421\n   0 | 044\n   0 | 678\n   1 | 22334\n   1 | 5788\n   2 | 0\n```\n:::\n\n```{.r .cell-code}\nstem(residuals(z3),0.5)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  The decimal point is at the |\n\n  -1 | 8650\n  -0 | 887655443100\n   0 | 35678\n   1 | 3344458899\n```\n:::\n\n```{.r .cell-code}\nstem(residuals(z4),0.5)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  The decimal point is at the |\n\n  -0 | 7655\n  -0 | 33222222221\n   0 | 0012334\n   0 | 555555677\n```\n:::\n\n```{.r .cell-code}\nstem(residuals(z5),0.5)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  The decimal point is 1 digit(s) to the right of the |\n\n  -2 | 431\n  -1 | 5520\n  -0 | 999986640\n   0 | 13445\n   1 | 01344566\n   2 | 04\n```\n:::\n\n```{.r .cell-code}\nstem(residuals(z6),0.5)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  The decimal point is 1 digit(s) to the left of the |\n\n  -2 | 864\n  -0 | 763110099764\n   0 | 03467856889\n   2 | 14579\n```\n:::\n\n```{.r .cell-code}\nstem(residuals(z7),0.5)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  The decimal point is at the |\n\n  -0 | 6655\n  -0 | 33222222220\n   0 | 002233\n   0 | 5555555678\n```\n:::\n\n```{.r .cell-code}\nstem(residuals(z8),0.5)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  The decimal point is at the |\n\n  -1 | 9650\n  -0 | 98776655421\n   0 | 044678\n   1 | 223345788\n   2 | 0\n```\n:::\n:::\n\n\n전반적으로 가장 큰 Cluster를 기준으로 대칭적인 종모양을 띄고 있지는 않은 것으로 보인다. y변수에 대한 sqrt변환의 경우와 log변환의 경우 그리고 x변수에 대한 제곱 변환의 경우 한개의 Cluster가 아니라 여러개의 Cluster가 있는 것으로 보인다. 교재에서 제시한 변환 방식이 Skewed to the right 되어 있지만 그나마 한개의 종모양의 형태를 띄고 있는 것으로 보인다.\n\nxy변수에 대한 log변환을 취한 경우 Stem 4를 제외하면 전반적으로 종모양이 잘 이루어지고 있는 것으로 보인다. stem 4가 이상치가 아니라면 2개의 cluster에 의한 쌍봉분포일 것이고, stem 4가 이상치라면 정규분포를 잘 이루고 있는 것으로 볼 수 있다.\n\n# 2번\n\nR의 airquality 자료를 이용하여 Ozone의 양을 제일 잘 예측할 수 있는 변수를 찾으려고 한다. 이 자료는 결측치가 많은 자료이다. 결측치를 분석에서 제외할 때 두 가지 방법이 있다.\n\n하나는 네 변수 중에 하나라도 결측값이 있으면 모두 사용하지 않는 방법 (이 자료의 경우는 해당 row를 사용하지 않음; case-wise deletion) 인데 그렇게 되면 너무 많은 자료를 잃게 된다. 다른 하나는 각 분석단계에서 가능한 많은 자료를 이용하는 방법이 있다(pair-wise deletion). 예를 들면 Ozone의 평균값을 구할 때는 Ozone의 결측값만 제외시키고, Ozone과 Solar.R의 r-line 구할 때는 Ozone과 Solar.R에서만 결측이 생긴 자료를 제외하고 분석하는 것이다. 여기서의 분석은 두 번째 방법으로 하여라. R command 사용시 결측값을 제외시키는 작업을 따로 하지 않아도 자동으로 두 번째 방법이 적용된다.\n\n## (가)\n\nOzone을 Y변수로 하고, Solar.R, Wind, Temp 각각의 세 X 변수에 대하여 산점도를 그리고 변환이 필요하면 변환하여 r-line으로 적합한 후 residual 분석 등으로 최적 X 변수의 순위를 선정하여라.\n\n### 결측치 확인하기\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(\"airquality\")\n\ncolSums(is.na(airquality))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  Ozone Solar.R    Wind    Temp   Month     Day \n     37       7       0       0       0       0 \n```\n:::\n\n```{.r .cell-code}\ndim(airquality)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 153   6\n```\n:::\n\n```{.r .cell-code}\nround(colSums(is.na(airquality))/dim(airquality)[1]*100,2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  Ozone Solar.R    Wind    Temp   Month     Day \n  24.18    4.58    0.00    0.00    0.00    0.00 \n```\n:::\n:::\n\n\nOzone 자료의 결측치 비율이 24.18%로 거의 1/4에 해당하는 자료에 대한 Ozone 데이터가 나타나지 않은 것으로 보인다. 따라서 분석을 진행 할때 있어 이부분을 유의해야 할 것으로 보인다. Solar.R자료는 약 4.58%에 해당하는 자료가 현재 결측되어진 것으로 보인다.\n\n### Ozone\\~Solar.R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nattach(airquality)\nplot(Ozone~Solar.R,main=\"linearity of Ozone ~ Solar\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n\n```{.r .cell-code}\nlength(Ozone) # 51개씩 쪼개기\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 153\n```\n:::\n\n```{.r .cell-code}\nairquality2=airquality[order(airquality$Solar.R),]\n\nmedOzone <- as.vector(3)\nmedSolar <- as.vector(3)\nmedOzone[1] <- median(airquality2$Ozone[1:51],na.rm=T); medSolar[1] <- median(airquality2$Solar.R[1:51],na.rm=T)\nmedOzone[2] <- median(airquality2$Ozone[52:102],na.rm=T); medSolar[2] <- median(airquality2$Solar.R[52:102],na.rm=T)\nmedOzone[3] <- median(airquality2$Ozone[103:153],na.rm=T); medSolar[3] <- median(airquality2$Solar.R[103:153],na.rm=T)\nplot(medOzone ~ medSolar, type=\"b\") \n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-9-2.png){width=672}\n:::\n\n```{.r .cell-code}\n# 선형관계보다는 기울기가 음수인 이차함수의 관계인 것으로 보인다. y변수 변환을 통해 선형성을 확보 \n\nplot(y=log(Ozone),x=Solar.R,main=\"Linearity of log(Ozone) and Solar.R\",xlab=\"Solar.R\",ylab=\"log(Ozone)\")\n(z1 <- line(y=log(Ozone),x=Solar.R))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nline(y = log(Ozone), x = Solar.R)\n\nCoefficients:\n[1]  2.74304  0.00341\n```\n:::\n\n```{.r .cell-code}\nabline(coef(z1))\nz1.ls <- lm(log(Ozone) ~ Solar.R)\nabline(z1.ls$coef, lty=2,col=\"red\")\nlegend(x = 250, y = 1, c(\"R - Line\", \"Regression\"), \n       lty=c(1,2),lwd=2,col = c(\"black\",\"red\"),cex=0.7)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-9-3.png){width=672}\n:::\n\n```{.r .cell-code}\nplot(y=sqrt(Ozone),x=Solar.R,main=\"Linearity of sqrt(Ozone) and Solar.R\",xlab=\"Solar.R\",ylab=\"sqrt(Ozone)\")\n(z2 <- line(y=sqrt(Ozone),x=Solar.R))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nline(y = sqrt(Ozone), x = Solar.R)\n\nCoefficients:\n[1]  3.808932  0.008582\n```\n:::\n\n```{.r .cell-code}\nabline(coef(z2))\nz2.ls <- lm(sqrt(Ozone) ~ Solar.R)\nabline(z2.ls$coef, lty=2,col=\"red\")\nlegend(x = 10, y = 12, c(\"R - Line\", \"Regression\"), \n       lty=c(1,2),lwd=2,col = c(\"black\",\"red\"),cex=0.7)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-9-4.png){width=672}\n:::\n\n```{.r .cell-code}\ns2=Solar.R^2\nplot(y=Ozone,x=s2,main=\"Linearity of Ozone and Solar.R^2\",xlab=\"Solar.R^2\",ylab=\"Ozone\")\n(z3 <- line(y=Ozone,x=s2))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nline(y = Ozone, x = s2)\n\nCoefficients:\n[1]  1.935e+01  2.498e-04\n```\n:::\n\n```{.r .cell-code}\nabline(coef(z3))\nz3.ls <- lm(Ozone ~ s2)\nabline(z3.ls$coef, lty=2,col=\"red\")\nlegend(x = 10, y =150, c(\"R - Line\", \"Regression\"), \n       lty=c(1,2),lwd=2,col = c(\"black\",\"red\"),cex=0.7)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-9-5.png){width=672}\n:::\n\n```{.r .cell-code}\nplot(residuals(z1) ~ fitted(z1), main = \"Residual plot by rline:log y ~ x\")\nabline(0,0) \n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-9-6.png){width=672}\n:::\n\n```{.r .cell-code}\nplot(residuals(z2) ~ fitted(z2), main = \"Residual plot by rline:sqrt y ~ x\")\nabline(0,0) \n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-9-7.png){width=672}\n:::\n\n```{.r .cell-code}\nplot(residuals(z3) ~ fitted(z3), main = \"Residual plot by rline: y~ x^2\")\nabline(0,0) \n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-9-8.png){width=672}\n:::\n\n```{.r .cell-code}\n# log 변환 \nboxplot(residuals(z1)) # outlier 1개\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-9-9.png){width=672}\n:::\n\n```{.r .cell-code}\nboxplot(residuals(z2)) # outlier 없음\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-9-10.png){width=672}\n:::\n\n```{.r .cell-code}\nboxplot(residuals(z3)) # outlier 2개\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-9-11.png){width=672}\n:::\n\n```{.r .cell-code}\n# stem and leaf\nstem(residuals(z1))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  The decimal point is 1 digit(s) to the left of the |\n\n  -26 | 7\n  -24 | \n  -22 | \n  -20 | \n  -18 | \n  -16 | \n  -14 | 44\n  -12 | 4342\n  -10 | 4\n   -8 | 96624\n   -6 | 763776533321\n   -4 | 88610854\n   -2 | 865407632\n   -0 | 8744221088742\n    0 | 001139\n    2 | 0344802445799\n    4 | 0114735\n    6 | 44568\n    8 | 1280002234469\n   10 | 602689\n   12 | 44556\n   14 | 7\n```\n:::\n\n```{.r .cell-code}\nstem(residuals(z2))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  The decimal point is at the |\n\n  -3 | 20\n  -2 | 999432000\n  -1 | 7666655544443221111000\n  -0 | 9999766543333222221110\n   0 | 0013357899999\n   1 | 001111222677\n   2 | 0122667799\n   3 | 223344577789\n   4 | 1679\n   5 | 0015\n   6 | \n   7 | 1\n```\n:::\n\n```{.r .cell-code}\nstem(residuals(z3))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  The decimal point is 1 digit(s) to the right of the |\n\n  -3 | 43\n  -2 | 976400\n  -1 | 986555554433332221111000\n  -0 | 99998776655543333222211\n   0 | 00011446\n   1 | 011122233344568\n   2 | 1459\n   3 | 01279999\n   4 | 2569\n   5 | 1117789\n   6 | 03\n   7 | 06\n   8 | 0366\n   9 | 8\n  10 | \n  11 | \n  12 | \n  13 | 5\n```\n:::\n\n```{.r .cell-code}\ncor.test(Ozone,Solar.R,na.rm=T)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPearson's product-moment correlation\n\ndata:  Ozone and Solar.R\nt = 3.8798, df = 109, p-value = 0.0001793\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n 0.173194 0.502132\nsample estimates:\n      cor \n0.3483417 \n```\n:::\n\n```{.r .cell-code}\ncor.test(log(Ozone),Solar.R,na.rm=T)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPearson's product-moment correlation\n\ndata:  log(Ozone) and Solar.R\nt = 5.3509, df = 109, p-value = 4.885e-07\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n 0.2947757 0.5921585\nsample estimates:\n      cor \n0.4561082 \n```\n:::\n\n```{.r .cell-code}\ncor.test(sqrt(Ozone),Solar.R,na.rm=T)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPearson's product-moment correlation\n\ndata:  sqrt(Ozone) and Solar.R\nt = 4.5948, df = 109, p-value = 1.17e-05\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n 0.2339963 0.5480629\nsample estimates:\n      cor \n0.4028201 \n```\n:::\n\n```{.r .cell-code}\ncor.test(Ozone,s2,na.rm=T)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPearson's product-moment correlation\n\ndata:  Ozone and s2\nt = 2.8565, df = 109, p-value = 0.00513\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n 0.08152183 0.42918594\nsample estimates:\n      cor \n0.2639047 \n```\n:::\n\n```{.r .cell-code}\n# y변수에 그래프의 잔차제곱 합\nsum(residuals(z1)^2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 66.29339\n```\n:::\n\n```{.r .cell-code}\nsum(residuals(z2)^2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 596.0805\n```\n:::\n\n```{.r .cell-code}\nsum(residuals(z3)^2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 129877.1\n```\n:::\n\n```{.r .cell-code}\ndetach(airquality)\n```\n:::\n\n\n총 3가지 변환 중 y축에 대한 변환들이 잔차들이 안정되어진 것으로 보인다. 1번 변환 (y변수만 log 변환)의 경우 자료가 잘 퍼져있다는 장점이 있으나 잔차들의 곡선의 경향성이 완전히 사라지지는 않은 것으로 보인다. 잔차의 크기가 작은 편이다. 2번 변환 (y변수만 sqrt 변환)의 경우 자료에서의 곡선성이 거의 사라졌다는 장점이 있으나 잔차의 y축으로 퍼진 범위가 넓어졌다.\n\n변환한 그래프들을 기준으로 전반적으로 Ozone량과 Solar.R의 값은 양의 상관관계를 가지고 있는 것으로 보인다.\n\n### Ozone\\~Wind\n\n\n::: {.cell}\n\n```{.r .cell-code}\nattach(airquality)\nattach(airquality)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following objects are masked from airquality (pos = 3):\n\n    Day, Month, Ozone, Solar.R, Temp, Wind\n```\n:::\n\n```{.r .cell-code}\nplot(Ozone~Wind,main=\"linearity of Ozone ~ Wind\")\n(z <- line(x=Wind,y=Ozone))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nline(x = Wind, y = Ozone)\n\nCoefficients:\n[1]  113.175   -7.417\n```\n:::\n\n```{.r .cell-code}\nabline(coef(z))\nz.ls <- lm(Ozone~Wind)\nabline(z.ls$coef, lty=2,col=\"red\")\nlegend(x = 16, y = 150, c(\"R - Line\", \"Regression\"), \n       lty=c(1,2),lwd=2,col = c(\"black\",\"red\"),cex=0.7)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-10-1.png){width=672}\n:::\n\n```{.r .cell-code}\nairquality2=airquality[order(airquality$Wind),]\n\nmedOzone <- as.vector(3)\nmedWind <- as.vector(3)\nmedOzone[1] <- median(airquality2$Ozone[1:51],na.rm=T); medWind[1] <- median(airquality2$Wind[1:51],na.rm=T)\nmedOzone[2] <- median(airquality2$Ozone[52:102],na.rm=T); medWind[2] <- median(airquality2$Wind[52:102],na.rm=T)\nmedOzone[3] <- median(airquality2$Ozone[103:153],na.rm=T); medWind[3] <- median(airquality2$Wind[103:153],na.rm=T)\nplot(medOzone ~ medWind, type=\"b\") \n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-10-2.png){width=672}\n:::\n\n```{.r .cell-code}\n# 감소하는 convex 함수의 관계인 것으로 보인다. y변수 변환을 통해 선형성을 확보\nplot(y=log(Ozone),x=Wind,main=\"Linearity of log(Ozone) and Wind\")\n(z1 <- line(y=log(Ozone),x=Wind))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nline(y = log(Ozone), x = Wind)\n\nCoefficients:\n[1]   5.3333  -0.1924\n```\n:::\n\n```{.r .cell-code}\nabline(coef(z1))\nz1.ls <- lm(log(Ozone) ~ Wind)\nabline(z1.ls$coef, lty=2,col=\"red\")\nlegend(x = 2, y = 1, c(\"R - Line\", \"Regression\"), \n       lty=c(1,2),lwd=2,col = c(\"black\",\"red\"),cex=0.7)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-10-3.png){width=672}\n:::\n\n```{.r .cell-code}\nplot(y=sqrt(Ozone),x=Wind,main=\"Linearity of sqrt(Ozone) and Wind\")\n(z2 <- line(y=sqrt(Ozone),x=Wind))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nline(y = sqrt(Ozone), x = Wind)\n\nCoefficients:\n[1]  11.8507  -0.5891\n```\n:::\n\n```{.r .cell-code}\nabline(coef(z2))\nz2.ls <- lm(sqrt(Ozone) ~ Wind)\nabline(z2.ls$coef, lty=2,col=\"red\")\nlegend(x = 16, y = 12, c(\"R - Line\", \"Regression\"), \n       lty=c(1,2),lwd=2,col = c(\"black\",\"red\"),cex=0.7)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-10-4.png){width=672}\n:::\n\n```{.r .cell-code}\nw2=Wind^2\nplot(y=Ozone,x=w2,main=\"Linearity of Ozone and Wind^2\")\n(z3 <- line(y=Ozone,x=w2))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nline(y = Ozone, x = w2)\n\nCoefficients:\n[1]  79.8590  -0.3743\n```\n:::\n\n```{.r .cell-code}\nabline(coef(z3))\nz3.ls <- lm(Ozone ~ w2)\nabline(z3.ls$coef, lty=2,col=\"red\")\nlegend(x = 300, y =150, c(\"R - Line\", \"Regression\"), \n       lty=c(1,2),lwd=2,col = c(\"black\",\"red\"),cex=0.7)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-10-5.png){width=672}\n:::\n\n```{.r .cell-code}\nplot(residuals(z1) ~ fitted(z1), main = \"Residual plot by rline\")\nabline(0,0) \n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-10-6.png){width=672}\n:::\n\n```{.r .cell-code}\nplot(residuals(z2) ~ fitted(z2), main = \"Residual plot by rline\")\nabline(0,0) \n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-10-7.png){width=672}\n:::\n\n```{.r .cell-code}\nplot(residuals(z3) ~ fitted(z3), main = \"Residual plot by rline\")\nabline(0,0) \n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-10-8.png){width=672}\n:::\n\n```{.r .cell-code}\nboxplot(residuals(z1)) # three outliers\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-10-9.png){width=672}\n:::\n\n```{.r .cell-code}\nboxplot(residuals(z2)) # one outlier\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-10-10.png){width=672}\n:::\n\n```{.r .cell-code}\nboxplot(residuals(z3)) # two outliers\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-10-11.png){width=672}\n:::\n\n```{.r .cell-code}\nstem(residuals(z1))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  The decimal point is at the |\n\n  -3 | 5\n  -3 | \n  -2 | \n  -2 | 11\n  -1 | \n  -1 | 4221100\n  -0 | 988887776666665555\n  -0 | 444433333333222222221111110000\n   0 | 000111122222223333333344444\n   0 | 555555555566677777899999\n   1 | 01133\n   1 | 6\n   2 | 3\n```\n:::\n\n```{.r .cell-code}\nstem(residuals(z2))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  The decimal point is at the |\n\n  -5 | 11\n  -4 | 1\n  -3 | 85111\n  -2 | 9887433322100\n  -1 | 7766655432111100000\n  -0 | 998888887665443310\n   0 | 0011222344455666999\n   1 | 00012234445666777999\n   2 | 01222246899\n   3 | 134667\n   4 | 7\n   5 | \n   6 | 4\n```\n:::\n\n```{.r .cell-code}\nstem(residuals(z3))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  The decimal point is 1 digit(s) to the right of the |\n\n  -5 | 5\n  -4 | 64310\n  -3 | 877643322\n  -2 | 9987765432110\n  -1 | 8887766666544220\n  -0 | 98876654444320\n   0 | 00134455667788999\n   1 | 01146799\n   2 | 00346689\n   3 | 0111123447\n   4 | 0277889\n   5 | 234\n   6 | 12\n   7 | 9\n   8 | \n   9 | 2\n  10 | \n  11 | 8\n```\n:::\n\n```{.r .cell-code}\n# y변수 그래프의 잔차제곱 합\nsum(residuals(z1)^2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 66.85564\n```\n:::\n\n```{.r .cell-code}\nsum(residuals(z2)^2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 489.5301\n```\n:::\n\n```{.r .cell-code}\nsum(residuals(z3)^2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 113187.1\n```\n:::\n\n```{.r .cell-code}\ncor.test(Ozone,Wind,na.rm=T)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPearson's product-moment correlation\n\ndata:  Ozone and Wind\nt = -8.0401, df = 114, p-value = 9.272e-13\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n -0.7063918 -0.4708713\nsample estimates:\n       cor \n-0.6015465 \n```\n:::\n\n```{.r .cell-code}\ncor.test(log(Ozone),Wind,na.rm=T)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPearson's product-moment correlation\n\ndata:  log(Ozone) and Wind\nt = -6.822, df = 114, p-value = 4.551e-10\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n -0.6563096 -0.3948621\nsample estimates:\n       cor \n-0.5384181 \n```\n:::\n\n```{.r .cell-code}\ncor.test(sqrt(Ozone),Wind,na.rm=T)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPearson's product-moment correlation\n\ndata:  sqrt(Ozone) and Wind\nt = -7.8938, df = 114, p-value = 1.983e-12\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n -0.7008452 -0.4622775\nsample estimates:\n       cor \n-0.5944899 \n```\n:::\n\n```{.r .cell-code}\ncor.test(Ozone,w2,na.rm=T)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPearson's product-moment correlation\n\ndata:  Ozone and w2\nt = -6.2579, df = 114, p-value = 7.055e-09\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n -0.6298998 -0.3561715\nsample estimates:\n      cor \n-0.505653 \n```\n:::\n\n```{.r .cell-code}\ndetach(airquality)\n```\n:::\n\n\n3가지 변환 중 Ozone에 sqrt를 취한 변환이 가장 적절해 보인다. Boxplot 기준으로 Residual에서 한개의 Outlier가 존재하고 median에서 hinge들 까지의 길이와 whisker의 길이들이 서로 각각 대칭적인 것으로 보인다. 줄기 잎 그림을 그렸더니 두 변환에서 모두 0을 중심으로 하는 종모양을 어느정도 이루고 있는 것으로 보인다. 변환 이전에 비해서 잔차들이 안정된 것으로 보이지만 완전하지 않다. 변환한 데이터들 기준으로 Ozone과 Wind는 전반적으로 음의 상관관계를 보이고 있는 것을 확인할 수 있다.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n### Ozone~Temp\nattach(airquality)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following objects are masked from airquality (pos = 3):\n\n    Day, Month, Ozone, Solar.R, Temp, Wind\n```\n:::\n\n```{.r .cell-code}\nplot(Ozone~Temp,main=\"linearity of Ozone ~ Temp\")\n(z <- line(x=Temp,y=Ozone))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nline(x = Temp, y = Ozone)\n\nCoefficients:\n[1]  -194.216     3.027\n```\n:::\n\n```{.r .cell-code}\nabline(coef(z))\nz.ls <- lm(Ozone~Temp)\nabline(z.ls$coef, lty=2,col=\"red\")\nlegend(x = 58, y = 150, c(\"R - Line\", \"Regression\"), \n       lty=c(1,2),lwd=2,col = c(\"black\",\"red\"),cex=0.7)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-11-1.png){width=672}\n:::\n\n```{.r .cell-code}\n# 직선에서 많이 떨어져있는 3~5개정도의 점을 제외하면 전반적으로 변수들이 양의 상관관계를 보이고 있는 것으로 보인다.\n\nairquality3=airquality[order(airquality$Temp),]\n\nmedOzone <- as.vector(3)\nmedTemp <- as.vector(3)\nmedOzone[1] <- median(airquality3$Ozone[1:51],na.rm=T); medTemp[1] <- median(airquality3$Temp[1:51],na.rm=T)\nmedOzone[2] <- median(airquality3$Ozone[52:102],na.rm=T); medTemp[2] <- median(airquality3$Temp[52:102],na.rm=T)\nmedOzone[3] <- median(airquality3$Ozone[103:153],na.rm=T); medTemp[3] <- median(airquality3$Temp[103:153],na.rm=T)\nplot(medOzone ~ medTemp, type=\"b\") \n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-11-2.png){width=672}\n:::\n\n```{.r .cell-code}\n# 증가하는 convex 함수의 관계인 것으로 보인다. y변수 변환을 통해 선형성을 확보 \n\nplot(y=log(Ozone),x=Temp,main=\"Linearity of log ozone and temp\",xlab=\"temp\",ylab=\"log Ozone\")\n(z1<- line(y=log(Ozone),x=(Temp)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nline(y = log(Ozone), x = (Temp))\n\nCoefficients:\n[1]  -2.8968   0.0813\n```\n:::\n\n```{.r .cell-code}\nabline(coef(z1))\nz1.ls <- lm(log(Ozone) ~ Temp)\nabline(z1.ls$coef, lty=2,col=\"red\")\nlegend(x = 58, y = 5, c(\"R - Line\", \"Regression\"), \n       lty=c(1,2),lwd=2,col = c(\"black\",\"red\"),cex=0.7)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-11-3.png){width=672}\n:::\n\n```{.r .cell-code}\nplot(y=sqrt(Ozone),x=Temp,main=\"Linearity of sqrt ozone and temp\",xlab=\"temp\",ylab=\"sqrt Ozone\")\n(z2<- line(y=sqrt(Ozone),x=Temp))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nline(y = sqrt(Ozone), x = Temp)\n\nCoefficients:\n[1]  -12.7938    0.2424\n```\n:::\n\n```{.r .cell-code}\nabline(coef(z2))\nz2.ls <- lm(sqrt(Ozone) ~ Temp)\nabline(z2.ls$coef, lty=2,col=\"red\")\nlegend(x = 58, y = 12, c(\"R - Line\", \"Regression\"), \n       lty=c(1,2),lwd=2,col = c(\"black\",\"red\"),cex=0.7)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-11-4.png){width=672}\n:::\n\n```{.r .cell-code}\nt2=Temp^2\nplot(Ozone~t2,main=\"linearity of Ozone ~ Temp^2\")\n(z3 <- line(x=t2,y=Ozone))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nline(x = t2, y = Ozone)\n\nCoefficients:\n[1]  -79.53178    0.01972\n```\n:::\n\n```{.r .cell-code}\nabline(coef(z3))\nz3.ls <- lm(Ozone~t2)\nabline(z3.ls$coef, lty=2,col=\"red\")\nlegend(x = 3000, y = 150, c(\"R - Line\", \"Regression\"), \n       lty=c(1,2),lwd=2,col = c(\"black\",\"red\"),cex=0.7)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-11-5.png){width=672}\n:::\n\n```{.r .cell-code}\nplot(residuals(z1) ~ fitted(z1), main = \"Residual plot by rline\")\nabline(0,0) \n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-11-6.png){width=672}\n:::\n\n```{.r .cell-code}\nplot(residuals(z2) ~ fitted(z2), main = \"Residual plot by rline\")\nabline(0,0) \n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-11-7.png){width=672}\n:::\n\n```{.r .cell-code}\nplot(residuals(z3) ~ fitted(z3), main = \"Residual plot by rline\")\nabline(0,0) \n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-11-8.png){width=672}\n:::\n\n```{.r .cell-code}\nboxplot(residuals(z1)) # 5 outliers\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-11-9.png){width=672}\n:::\n\n```{.r .cell-code}\nboxplot(residuals(z2)) # 2 outliers\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-11-10.png){width=672}\n:::\n\n```{.r .cell-code}\nboxplot(residuals(z3)) # 3 outliers\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-11-11.png){width=672}\n:::\n\n```{.r .cell-code}\nstem(residuals(z1))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  The decimal point is 1 digit(s) to the left of the |\n\n  -18 | 0\n  -16 | 6\n  -14 | 9\n  -12 | \n  -10 | 700\n   -8 | \n   -6 | 7764228864331\n   -4 | 65187640\n   -2 | 9975322111074321\n   -0 | 866655420732111\n    0 | 112356679002345889\n    2 | 05666889113344689\n    4 | 175579\n    6 | 11357557\n    8 | 67\n   10 | 4676\n   12 | 2\n   14 | 04\n```\n:::\n\n```{.r .cell-code}\nstem(residuals(z2))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  The decimal point is at the |\n\n  -4 | 0\n  -3 | 811\n  -2 | 65311000\n  -1 | 9987777666444443333322221000\n  -0 | 888888876665522210\n   0 | 0011112233344455555677788888999\n   1 | 012333334455588\n   2 | 013668\n   3 | 007\n   4 | 04\n   5 | \n   6 | 1\n```\n:::\n\n```{.r .cell-code}\nstem(residuals(z3))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  The decimal point is 1 digit(s) to the right of the |\n\n  -4 | 10\n  -3 | 773100\n  -2 | 88754332111\n  -1 | 888877666666655444443211100\n  -0 | 999977654220\n   0 | 011223344567888899999\n   1 | 0002222233344445556889\n   2 | 12238\n   3 | 00128\n   4 | 55\n   5 | \n   6 | \n   7 | 15\n   8 | \n   9 | \n  10 | \n  11 | 8\n```\n:::\n\n```{.r .cell-code}\n# y변수 그래프의 잔차제곱 합\nsum(residuals(z1)^2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 40.98835\n```\n:::\n\n```{.r .cell-code}\nsum(residuals(z2)^2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 332.1941\n```\n:::\n\n```{.r .cell-code}\nsum(residuals(z3)^2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 64694.05\n```\n:::\n\n```{.r .cell-code}\ncor.test(Ozone,Temp)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPearson's product-moment correlation\n\ndata:  Ozone and Temp\nt = 10.418, df = 114, p-value < 2.2e-16\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n 0.5913340 0.7812111\nsample estimates:\n      cor \n0.6983603 \n```\n:::\n\n```{.r .cell-code}\ncor.test(sqrt(Ozone),(Temp))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPearson's product-moment correlation\n\ndata:  sqrt(Ozone) and (Temp)\nt = 11.869, df = 114, p-value < 2.2e-16\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n 0.6491335 0.8152728\nsample estimates:\n      cor \n0.7434629 \n```\n:::\n\n```{.r .cell-code}\ncor.test(log(Ozone),(Temp))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPearson's product-moment correlation\n\ndata:  log(Ozone) and (Temp)\nt = 11.741, df = 114, p-value < 2.2e-16\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n 0.6444258 0.8125409\nsample estimates:\n      cor \n0.7398211 \n```\n:::\n\n```{.r .cell-code}\ncor.test((Ozone),t2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPearson's product-moment correlation\n\ndata:  (Ozone) and t2\nt = 10.859, df = 114, p-value < 2.2e-16\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n 0.6100642 0.7923742\nsample estimates:\n      cor \n0.7130697 \n```\n:::\n\n```{.r .cell-code}\ndetach(airquality)\n```\n:::\n\n\n3가지 변환 중 sqrt 변환이 가장 적절해 보인다. boxplot 기준으로 median에서 hinge들까지의 거리가 적절해보이고 (다소 위쪽으로 몰려있는 것 처럼 보이지만), whisker의 길이도 대칭적인 것으로 보인다. 다만 outlier의 수는 2개이다. Stem and Leaf Plot에서 변환 이후 데이터에서 종 모양이 대칭적으로 나타나는 것 처럼 보인다.\n\n변환한 데이터들 기준으로 Ozone과 Temp는 전반적으로 양의 상관관계를 보이고 있는 것을 확인할 수 있다.\n\n변환된 데이터들의 Residual plot들을 기준으로 볼 때 예측력이 가장 높은 지표는 Wind변수이고, 다음으로는 Temp변수이고, 다음으로는 Solar.R변수 인 것으로 추측된다. Residual들이 가장 넓게 퍼져있는 지표는 Soalr.R변수이고 나머지 두변수들은 Residual이 원형으로 다소 뭉쳐있는데 상대적으로 Temp 변수들이 많이 퍼져있기 때문에 Wind 변수의 순위를 높게 잡았다.\n\nX\\~Y둘다 변환\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchoose(3,1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 3\n```\n:::\n\n```{.r .cell-code}\nattach(airquality)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following objects are masked from airquality (pos = 3):\n\n    Day, Month, Ozone, Solar.R, Temp, Wind\n```\n:::\n\n```{.r .cell-code}\n# Ozone ~ Solar.R\ncor.test(Ozone,Solar.R)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPearson's product-moment correlation\n\ndata:  Ozone and Solar.R\nt = 3.8798, df = 109, p-value = 0.0001793\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n 0.173194 0.502132\nsample estimates:\n      cor \n0.3483417 \n```\n:::\n\n```{.r .cell-code}\nplot(y=log(Ozone),x=Solar.R,main=\"R-line\")\nabline(line(y=log(Ozone),x=Solar.R)$coeff)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-12-1.png){width=672}\n:::\n\n```{.r .cell-code}\nplot(y=log(Ozone),x=log(Solar.R),main=\"R-line: log\")\n(z1 <- line(y=log(Ozone),x=log(Solar.R)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nline(y = log(Ozone), x = log(Solar.R))\n\nCoefficients:\n[1]  0.8148  0.5269\n```\n:::\n\n```{.r .cell-code}\nabline(coef(z1))\nz1.ls <- lm(log(Ozone) ~ log(Solar.R))\nabline(z1.ls$coef, lty=2,col=\"red\")\nlegend(x = 2, y = 4.5, c(\"R - Line\", \"Regression\"), \n       lty=c(1,2),lwd=2,col = c(\"black\",\"red\"),cex=0.7)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-12-2.png){width=672}\n:::\n\n```{.r .cell-code}\nplot(y=sqrt(Ozone),x=sqrt(Solar.R),main=\"R-line: sqrt\")\n(z2 <- line(y=sqrt(Ozone),x=sqrt(Solar.R)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nline(y = sqrt(Ozone), x = sqrt(Solar.R))\n\nCoefficients:\n[1]  2.5206  0.2168\n```\n:::\n\n```{.r .cell-code}\nabline(coef(z2))\nz2.ls <- lm(sqrt(Ozone) ~ sqrt(Solar.R))\nabline(z2.ls$coef, lty=2,col=\"red\")\nlegend(x = 3, y = 12, c(\"R - Line\", \"Regression\"), \n       lty=c(1,2),lwd=2,col = c(\"black\",\"red\"),cex=0.7)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-12-3.png){width=672}\n:::\n\n```{.r .cell-code}\nplot(residuals(z1) ~ fitted(z1), main = \"Residual plot by rline: log\") #오른쪽으로 잔차들이 몰리게 되었다는 점에서 부적절한 변환으로 보임.\nabline(0,0)  \n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-12-4.png){width=672}\n:::\n\n```{.r .cell-code}\nplot(residuals(z2) ~ fitted(z2), main = \"Residual plot by rline: sqrt\") #한개의 outlier만 제외 하면 전반적으로 변환 이전에 비해서 잔차들이 잘 퍼져있는 것으로 보임. \nabline(0,0)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-12-5.png){width=672}\n:::\n\n```{.r .cell-code}\nboxplot(residuals(z1)) # outlier 없음\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-12-6.png){width=672}\n:::\n\n```{.r .cell-code}\nboxplot(residuals(z2)) # outlier 1개\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-12-7.png){width=672}\n:::\n\n```{.r .cell-code}\nstem(residuals(z1)) \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  The decimal point is 1 digit(s) to the left of the |\n\n  -18 | 1\n  -16 | \n  -14 | 650\n  -12 | 24\n  -10 | 332\n   -8 | 765421544\n   -6 | 84300874\n   -4 | 642219641\n   -2 | 7311999984320\n   -0 | 9887632\n    0 | 013893334777\n    2 | 005577825\n    4 | 369277\n    6 | 245023367\n    8 | 01112713337\n   10 | 25788049\n   12 | \n   14 | 3\n```\n:::\n\n```{.r .cell-code}\nstem(residuals(z2)) \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  The decimal point is at the |\n\n  -3 | 1\n  -2 | 997431100\n  -1 | 876655554444432210\n  -0 | 999888666665443322221111000\n   0 | 033467899999\n   1 | 0011111155677\n   2 | 0222677788\n   3 | 113344667888\n   4 | 0568\n   5 | 0115\n   6 | \n   7 | 1\n```\n:::\n\n```{.r .cell-code}\n# Y만 변환일 때에 비해 잔차들이 보이던 곡선의 경향성이 다소 완화되어진 것을 확인할 수 있다.\n\n\n# Ozone ~ Wind\ncor.test(Ozone,Wind)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPearson's product-moment correlation\n\ndata:  Ozone and Wind\nt = -8.0401, df = 114, p-value = 9.272e-13\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n -0.7063918 -0.4708713\nsample estimates:\n       cor \n-0.6015465 \n```\n:::\n\n```{.r .cell-code}\nplot(y=log(Ozone),x=Wind,main=\"R-line\")\nabline(line(y=log(Ozone),x=Wind)$coeff)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-12-8.png){width=672}\n:::\n\n```{.r .cell-code}\nplot(line(y=log(Ozone),x=Wind)$residuals~line(y=log(Ozone),x=Wind)$fit)\nabline(0,0) # 다소 곡선의 형태\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-12-9.png){width=672}\n:::\n\n```{.r .cell-code}\nplot(y=log(Ozone),x=log(Wind),main=\"R-line: log\")\n(z1 <- line(y=log(Ozone),x=log(Wind)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nline(y = log(Ozone), x = log(Wind))\n\nCoefficients:\n[1]   7.492  -1.845\n```\n:::\n\n```{.r .cell-code}\nabline(coef(z1))\nz1.ls <- lm(log(Ozone) ~ log(Wind))\nabline(z1.ls$coef, lty=2,col=\"red\")\nlegend(x = 0.5, y = 4.5, c(\"R - Line\", \"Regression\"), \n       lty=c(1,2),lwd=2,col = c(\"black\",\"red\"),cex=0.7)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-12-10.png){width=672}\n:::\n\n```{.r .cell-code}\nplot(y=sqrt(Ozone),x=sqrt(Wind),main=\"R-line: sqrt\")\n(z2 <- line(y=sqrt(Ozone),x=sqrt(Wind)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nline(y = sqrt(Ozone), x = sqrt(Wind))\n\nCoefficients:\n[1]  17.078  -3.664\n```\n:::\n\n```{.r .cell-code}\nabline(coef(z2))\nz2.ls <- lm(sqrt(Ozone) ~ sqrt(Wind))\nabline(z2.ls$coef, lty=2,col=\"red\")\nlegend(x = 1.5, y = 4, c(\"R - Line\", \"Regression\"), \n       lty=c(1,2),lwd=2,col = c(\"black\",\"red\"),cex=0.7)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-12-11.png){width=672}\n:::\n\n```{.r .cell-code}\nplot(residuals(z1) ~ fitted(z1), main = \"Residual plot by rline: log\") # Outlier 제외할 경우에도 약간의 곡선의 흔적이 남아있는 것으로 보임.\nabline(0,0)  \n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-12-12.png){width=672}\n:::\n\n```{.r .cell-code}\nplot(residuals(z2) ~ fitted(z2), main = \"Residual plot by rline: sqrt\") # 여전히 완벽하게 잔차를 퍼트리지는 못한 것으로 보이고 곡선의 흔적이 보임\nabline(0,0)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-12-13.png){width=672}\n:::\n\n```{.r .cell-code}\nboxplot(residuals(z1)) # outlier 3개\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-12-14.png){width=672}\n:::\n\n```{.r .cell-code}\nboxplot(residuals(z2)) # outlier 1개\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-12-15.png){width=672}\n:::\n\n```{.r .cell-code}\nstem(residuals(z1)) \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  The decimal point is at the |\n\n  -3 | 3\n  -2 | \n  -2 | 0\n  -1 | 9\n  -1 | 322200\n  -0 | 99988766655555555\n  -0 | 44444333333322211111111111111000\n   0 | 0001111111222333333344444\n   0 | 5555566666666667788899\n   1 | 000002333\n   1 | 67\n```\n:::\n\n```{.r .cell-code}\nstem(residuals(z2)) \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  The decimal point is at the |\n\n  -4 | 87\n  -3 | 751\n  -2 | 7766543300\n  -1 | 9977755222222100\n  -0 | 987777666555554443332221100\n   0 | 01345566678899\n   1 | 001233333344566678999\n   2 | 0001233444668\n   3 | 0137788\n   4 | 1\n   5 | 07\n```\n:::\n\n```{.r .cell-code}\n# Y만 변환일 때에 비해 잔차들이 보이던 곡선의 경향성이 다소 완화되어진 것을 확인할 수 있다. 잔차들이 조금 더 y축을 기준으로 대칭적이 된 것을 확인할 수 있다.\n\n\n\n# Ozone ~ Temp\ncor.test(Ozone,Temp)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPearson's product-moment correlation\n\ndata:  Ozone and Temp\nt = 10.418, df = 114, p-value < 2.2e-16\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n 0.5913340 0.7812111\nsample estimates:\n      cor \n0.6983603 \n```\n:::\n\n```{.r .cell-code}\nplot(y=log(Ozone),x=Temp,main=\"R-line\")\nabline(line(y=log(Ozone),x=Temp)$coeff)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-12-16.png){width=672}\n:::\n\n```{.r .cell-code}\nplot(line(y=log(Ozone),x=Temp)$residuals~line(y=log(Ozone),x=Temp)$fitted)\nabline(0,0) # outleir을 제외하더라도 다소 대칭적이지는 않아보임 (곡선 관계가 남아있는 것 같아보이지만 확실하지는 않음)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-12-17.png){width=672}\n:::\n\n```{.r .cell-code}\nplot(y=log(Ozone),x=log(Temp),main=\"R-line: log\")\n(z1 <- line(y=log(Ozone),x=log(Temp)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nline(y = log(Ozone), x = log(Temp))\n\nCoefficients:\n[1]  -23.526    6.208\n```\n:::\n\n```{.r .cell-code}\nabline(coef(z1))\nz1.ls <- lm(log(Ozone) ~ log(Temp))\nabline(z1.ls$coef, lty=2,col=\"red\")\nlegend(x = 4.05, y = 5., c(\"R - Line\", \"Regression\"), \n       lty=c(1,2),lwd=2,col = c(\"black\",\"red\"),cex=0.7)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-12-18.png){width=672}\n:::\n\n```{.r .cell-code}\nplot(y=sqrt(Ozone),x=sqrt(Temp),main=\"R-line: sqrt\")\n(z2 <- line(y=sqrt(Ozone),x=sqrt(Temp)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nline(y = sqrt(Ozone), x = sqrt(Temp))\n\nCoefficients:\n[1]  -31.28    4.24\n```\n:::\n\n```{.r .cell-code}\nabline(coef(z2))\nz2.ls <- lm(sqrt(Ozone) ~ sqrt(Temp))\nabline(z2.ls$coef, lty=2,col=\"red\")\nlegend(x = 7.5, y = 12, c(\"R - Line\", \"Regression\"), \n       lty=c(1,2),lwd=2,col = c(\"black\",\"red\"),cex=0.7)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-12-19.png){width=672}\n:::\n\n```{.r .cell-code}\nplot(residuals(z1) ~ fitted(z1), main = \"Residual plot by rline: log\") # 곡선의 형태가 완화되고 잔차들이 y축을 기준으로 대칭되어 나타나는 것으로 보인다. \nabline(0,0)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-12-20.png){width=672}\n:::\n\n```{.r .cell-code}\nplot(residuals(z2) ~ fitted(z2), main = \"Residual plot by rline: sqrt\") # 여전히 완벽하게 잔차를 퍼트리지는 못한 것으로 보이고 곡선의 흔적이 보임\nabline(0,0)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-12-21.png){width=672}\n:::\n\n```{.r .cell-code}\nboxplot(residuals(z1)) # outlier 4개\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-12-22.png){width=672}\n:::\n\n```{.r .cell-code}\nboxplot(residuals(z2)) # outlier 1개\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-12-23.png){width=672}\n:::\n\n```{.r .cell-code}\nstem(residuals(z1))  # 0을 기준으로 종모양이 나타남\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  The decimal point is 1 digit(s) to the left of the |\n\n  -16 | 93\n  -14 | 6\n  -12 | 5\n  -10 | 66\n   -8 | 432100\n   -6 | 41108431\n   -4 | 54200776200\n   -2 | 987554229843322\n   -0 | 987651099931\n    0 | 133357788899013467\n    2 | 00235555679011224\n    4 | 468915669\n    6 | 03349\n    8 | 52\n   10 | 4345\n   12 | 17\n   14 | 7\n```\n:::\n\n```{.r .cell-code}\nstem(residuals(z2)) \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  The decimal point is at the |\n\n  -4 | 0\n  -3 | 911\n  -2 | 6532110\n  -1 | 99888777776544444333222211100\n  -0 | 999888666665322110\n   0 | 0111222333455555566667788889\n   1 | 000122333444456789\n   2 | 11367\n   3 | 0128\n   4 | 03\n   5 | \n   6 | 1\n```\n:::\n\n```{.r .cell-code}\n# 변환이후에는 변환 이전에 비해서 큰 차이가 없는 것 처럼 보이기는 한다. outlier들을 제외 하더라도 큰 차이는 없는 것으로 보인다.\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nlmfit=lm(Ozone~Solar.R+Temp+Wind,data=airquality)\nsummary(lmfit)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = Ozone ~ Solar.R + Temp + Wind, data = airquality)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-40.485 -14.219  -3.551  10.097  95.619 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -64.34208   23.05472  -2.791  0.00623 ** \nSolar.R       0.05982    0.02319   2.580  0.01124 *  \nTemp          1.65209    0.25353   6.516 2.42e-09 ***\nWind         -3.33359    0.65441  -5.094 1.52e-06 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 21.18 on 107 degrees of freedom\n  (42 observations deleted due to missingness)\nMultiple R-squared:  0.6059,\tAdjusted R-squared:  0.5948 \nF-statistic: 54.83 on 3 and 107 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\nlmfit2=lm(sqrt(Ozone)~(Solar.R)+(Temp)+(Wind),data=airquality)\nsummary(lmfit2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = sqrt(Ozone) ~ (Solar.R) + (Temp) + (Wind), data = airquality)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-3.0994 -1.0902 -0.2060  0.8784  4.7782 \n\nCoefficients:\n             Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -3.284232   1.545516  -2.125 0.035888 *  \nSolar.R      0.005556   0.001554   3.574 0.000528 ***\nTemp         0.134491   0.016996   7.913 2.46e-12 ***\nWind        -0.220179   0.043869  -5.019 2.08e-06 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.42 on 107 degrees of freedom\n  (42 observations deleted due to missingness)\nMultiple R-squared:  0.6707,\tAdjusted R-squared:  0.6614 \nF-statistic: 72.64 on 3 and 107 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\nlmfit3=lm(log(Ozone)~(Solar.R)+(Temp)+(Wind),data=airquality)\nsummary(lmfit3)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = log(Ozone) ~ (Solar.R) + (Temp) + (Wind), data = airquality)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-2.06193 -0.29970 -0.00231  0.30756  1.23578 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept) -0.2621323  0.5535669  -0.474 0.636798    \nSolar.R      0.0025152  0.0005567   4.518 1.62e-05 ***\nTemp         0.0491711  0.0060875   8.077 1.07e-12 ***\nWind        -0.0615625  0.0157130  -3.918 0.000158 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.5086 on 107 degrees of freedom\n  (42 observations deleted due to missingness)\nMultiple R-squared:  0.6644,\tAdjusted R-squared:  0.655 \nF-statistic: 70.62 on 3 and 107 DF,  p-value: < 2.2e-16\n```\n:::\n\n```{.r .cell-code}\nlmfit4=lm(sqrt(Ozone)~sqrt(Solar.R)+sqrt(Temp)+sqrt(Wind),data=airquality)\nsummary(lmfit4)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = sqrt(Ozone) ~ sqrt(Solar.R) + sqrt(Temp) + sqrt(Wind), \n    data = airquality)\n\nResiduals:\n    Min      1Q  Median      3Q     Max \n-3.1313 -1.0142 -0.2502  0.9461  4.2580 \n\nCoefficients:\n              Estimate Std. Error t value Pr(>|t|)    \n(Intercept)   -9.59783    3.01971  -3.178 0.001937 ** \nsqrt(Solar.R)  0.12993    0.03477   3.737 0.000301 ***\nsqrt(Temp)     2.12867    0.29694   7.169 1.02e-10 ***\nsqrt(Wind)    -1.55165    0.26821  -5.785 7.28e-08 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 1.392 on 107 degrees of freedom\n  (42 observations deleted due to missingness)\nMultiple R-squared:  0.6837,\tAdjusted R-squared:  0.6748 \nF-statistic: 77.09 on 3 and 107 DF,  p-value: < 2.2e-16\n```\n:::\n:::\n\n\n변환전 데이터로 회귀분석 기준으로 변수들의 설명력을 볼 경우 Wind, Temp, Solar.R순서이다. 다만, 변환이 이루어지지 않았기 때문에 극단치에 영향을 많이 받았을 가능성이 있다. Sqrt나 Log변환을 진행 한 이후 회귀분석을 진행하면 영향력이 강한 독립변수는 Wind, Temp, Solar.R동일한 순서인 것으로 보인다.\n\n위에서 상관계수를 계산했을 때 확인했던 것처럼 Wind는 음의 회귀계수, 나머지 두 독립변수는 양의 회귀게수이다.\n\n(결론)\n\nOzone 변수에 Sqrt를 취한 값에 대한 적합값의 잔차들을 제곱해서 더할 경우 다음과 같다. Solar.R: 596.0805 Wind: 489.5301 Temp: 332.194\n\n잔차 제곱합의 기준에서 가장 작은 순서대로 fitting이 잘 되었다고 하였을 때, Temp, Wind, Solar.R 변수들의 순서로 Multiple r-line을 적합해보고자 한다.\n\n## (나)\n\n세 X 변수 사이의 종속성(dependency)을 X-Y 그래프로 직선 또는 곡선 관계의 경향이 있는 지 판단하여라. 세 변수가 한꺼번에 종속 관계가 있을 수 있으나 3차원 그래프를 이용해야 하므로 일단 세 변수 중 두 개씩 골라 X-Y 그래프를 그리고 두 변수 사이의 직선 또는 곡선 관계를 파악하여라. 필요한 경우에는 r-line으로 적합하여 판단하여라. (이러한 분석은 다중회귀식으로 모형을 확장할 때 필요한 작업이다)\n\n\n::: {.cell}\n\n```{.r .cell-code}\nchoose(3,2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 3\n```\n:::\n:::\n\n\n### Wind\\~Solar.R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nattach(airquality)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following objects are masked from airquality (pos = 3):\n\n    Day, Month, Ozone, Solar.R, Temp, Wind\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following objects are masked from airquality (pos = 4):\n\n    Day, Month, Ozone, Solar.R, Temp, Wind\n```\n:::\n\n```{.r .cell-code}\nplot(Wind~Solar.R,main=\"linearity of Solar.R ~ Wind\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-15-1.png){width=672}\n:::\n\n```{.r .cell-code}\ncor.test(Wind,Solar.R) # 상관관계가 없음\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPearson's product-moment correlation\n\ndata:  Wind and Solar.R\nt = -0.6826, df = 144, p-value = 0.496\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n -0.2172359  0.1066406\nsample estimates:\n        cor \n-0.05679167 \n```\n:::\n\n```{.r .cell-code}\ncor.test(Wind,sqrt(Solar.R)) # 상관관계가 없음\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPearson's product-moment correlation\n\ndata:  Wind and sqrt(Solar.R)\nt = -1.1529, df = 144, p-value = 0.2509\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n -0.25413132  0.06787189\nsample estimates:\n        cor \n-0.09563089 \n```\n:::\n\n```{.r .cell-code}\ncor.test(Wind,log(Solar.R)) # 상관관계가 없음\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPearson's product-moment correlation\n\ndata:  Wind and log(Solar.R)\nt = -1.4876, df = 144, p-value = 0.139\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n -0.27988233  0.04022473\nsample estimates:\n       cor \n-0.1230276 \n```\n:::\n\n```{.r .cell-code}\ncor.test(Wind,log(Solar.R)) # 상관관계가 없음\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPearson's product-moment correlation\n\ndata:  Wind and log(Solar.R)\nt = -1.4876, df = 144, p-value = 0.139\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n -0.27988233  0.04022473\nsample estimates:\n       cor \n-0.1230276 \n```\n:::\n\n```{.r .cell-code}\ncor.test(Wind,sqrt(Solar.R)) # 상관관계가 없음\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPearson's product-moment correlation\n\ndata:  Wind and sqrt(Solar.R)\nt = -1.1529, df = 144, p-value = 0.2509\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n -0.25413132  0.06787189\nsample estimates:\n        cor \n-0.09563089 \n```\n:::\n\n```{.r .cell-code}\ndetach(airquality)\n```\n:::\n\n\n태양 복사와 바람 변수는 서로 관계가 없는 것으로 보인다.\n\n### Wind\\~Temp\n\n\n::: {.cell}\n\n```{.r .cell-code}\nattach(airquality)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following objects are masked from airquality (pos = 3):\n\n    Day, Month, Ozone, Solar.R, Temp, Wind\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following objects are masked from airquality (pos = 4):\n\n    Day, Month, Ozone, Solar.R, Temp, Wind\n```\n:::\n\n```{.r .cell-code}\nplot(Wind~Temp,main=\"linearity of Wind ~ Temp\")\n\n(z <- line(x=Temp,y=Wind))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nline(x = Temp, y = Wind)\n\nCoefficients:\n[1]  24.7222  -0.1944\n```\n:::\n\n```{.r .cell-code}\nabline(coef(z))\nz.ls <- lm(Wind~Temp)\nabline(z.ls$coef, lty=2,col=\"red\")\nlegend(x = 58, y = 5, c(\"R - Line\", \"Regression\"), \n       lty=c(1,2),lwd=2,col = c(\"black\",\"red\"),cex=0.7)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-16-1.png){width=672}\n:::\n\n```{.r .cell-code}\ncor.test(Wind,Temp,na.rm=T) #음의 상관관계\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPearson's product-moment correlation\n\ndata:  Wind and Temp\nt = -6.3308, df = 151, p-value = 2.642e-09\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n -0.5748874 -0.3227660\nsample estimates:\n       cor \n-0.4579879 \n```\n:::\n\n```{.r .cell-code}\nairquality4=airquality[order(airquality$Temp),]\n\nmedWind <- as.vector(3)\nmedTemp <- as.vector(3)\nmedWind[1] <- median(airquality4$Wind[1:51],na.rm=T); medTemp[1] <- median(airquality4$Temp[1:51],na.rm=T)\nmedWind[2] <- median(airquality4$Wind[52:102],na.rm=T); medTemp[2] <- median(airquality4$Temp[52:102],na.rm=T)\nmedWind[3] <- median(airquality4$Wind[103:153],na.rm=T); medTemp[3] <- median(airquality4$Temp[103:153],na.rm=T)\nplot(medWind ~ medTemp, type=\"b\") \n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-16-2.png){width=672}\n:::\n\n```{.r .cell-code}\n#감소하는 Concave 한 곡선형태\n\nplot(y=log(Wind),x=Temp,main=\"Linearity of log Wind and temp\")\n(z1<- line(y=log(Wind),x=(Temp)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nline(y = log(Wind), x = (Temp))\n\nCoefficients:\n[1]   3.81332  -0.02016\n```\n:::\n\n```{.r .cell-code}\nabline(coef(z1))\nz1.ls <- lm(log(Wind) ~ Temp)\nabline(z1.ls$coef, lty=2,col=\"red\")\nlegend(x = 58, y = 1, c(\"R - Line\", \"Regression\"), \n       lty=c(1,2),lwd=2,col = c(\"black\",\"red\"),cex=0.7)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-16-3.png){width=672}\n:::\n\n```{.r .cell-code}\nplot(y=sqrt(Wind),x=Temp,main=\"Linearity of sqrt Wind and temp\")\n(z1<- line(y=sqrt(Wind),x=(Temp)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nline(y = sqrt(Wind), x = (Temp))\n\nCoefficients:\n[1]   5.51706  -0.03126\n```\n:::\n\n```{.r .cell-code}\nabline(coef(z1))\nz1.ls <- lm(sqrt(Wind) ~ Temp)\nabline(z1.ls$coef, lty=2,col=\"red\")\nlegend(x = 58, y = 2, c(\"R - Line\", \"Regression\"), \n       lty=c(1,2),lwd=2,col = c(\"black\",\"red\"),cex=0.7)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-16-4.png){width=672}\n:::\n\n```{.r .cell-code}\nt2=Temp^2\nplot(y=Wind,x=t2,main=\"Linearity of Wind and temp^2\")\n(z1<- line(y=(Wind),x=t2))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nline(y = (Wind), x = t2)\n\nCoefficients:\n[1]  17.456566  -0.001263\n```\n:::\n\n```{.r .cell-code}\nabline(coef(z1))\nz1.ls <- lm(Wind ~ t2)\nabline(z1.ls$coef, lty=2,col=\"red\")\nlegend(x = 3300, y = 5, c(\"R - Line\", \"Regression\"), \n       lty=c(1,2),lwd=2,col = c(\"black\",\"red\"),cex=0.7)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-16-5.png){width=672}\n:::\n\n```{.r .cell-code}\nplot(residuals(z1) ~ fitted(z1), main = \"Residual plot by rline\") #가장 적절해 보인다\nabline(0,0) \n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-16-6.png){width=672}\n:::\n\n```{.r .cell-code}\nplot(residuals(z2) ~ fitted(z2), main = \"Residual plot by rline\")\nabline(0,0) \n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-16-7.png){width=672}\n:::\n\n```{.r .cell-code}\nplot(residuals(z3) ~ fitted(z3), main = \"Residual plot by rline\")\nabline(0,0) \n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-16-8.png){width=672}\n:::\n\n```{.r .cell-code}\nboxplot(residuals(z1)) # 2 outliers\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-16-9.png){width=672}\n:::\n\n```{.r .cell-code}\nboxplot(residuals(z2)) # 3 outliers\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-16-10.png){width=672}\n:::\n\n```{.r .cell-code}\nboxplot(residuals(z3)) # 3 outliers\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-16-11.png){width=672}\n:::\n\n```{.r .cell-code}\nstem(residuals(z1))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  The decimal point is at the |\n\n  -8 | 5\n  -7 | \n  -6 | \n  -5 | 864\n  -4 | 44420\n  -3 | 9977766554331\n  -2 | 9999888886433220\n  -1 | 99877643221110000\n  -0 | 9888877554443321111100\n   0 | 0001112333345555557778889\n   1 | 11357899\n   2 | 0111244559\n   3 | 12224446699\n   4 | 1234467999\n   5 | 0357779\n   6 | 6\n   7 | 039\n   8 | \n   9 | 8\n```\n:::\n\n```{.r .cell-code}\nstem(residuals(z2))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  The decimal point is at the |\n\n  -4 | 0\n  -3 | 911\n  -2 | 6532110\n  -1 | 99888777776544444333222211100\n  -0 | 999888666665322110\n   0 | 0111222333455555566667788889\n   1 | 000122333444456789\n   2 | 11367\n   3 | 0128\n   4 | 03\n   5 | \n   6 | 1\n```\n:::\n\n```{.r .cell-code}\nstem(residuals(z3))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  The decimal point is 1 digit(s) to the right of the |\n\n  -4 | 10\n  -3 | 773100\n  -2 | 88754332111\n  -1 | 888877666666655444443211100\n  -0 | 999977654220\n   0 | 011223344567888899999\n   1 | 0002222233344445556889\n   2 | 12238\n   3 | 00128\n   4 | 55\n   5 | \n   6 | \n   7 | 15\n   8 | \n   9 | \n  10 | \n  11 | 8\n```\n:::\n\n```{.r .cell-code}\ncor.test(log(Wind),Temp,na.rm=T) #음의 상관관계\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPearson's product-moment correlation\n\ndata:  log(Wind) and Temp\nt = -6.0416, df = 151, p-value = 1.141e-08\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n -0.5606394 -0.3038034\nsample estimates:\n       cor \n-0.4412121 \n```\n:::\n\n```{.r .cell-code}\ncor.test(sqrt(Wind),Temp,na.rm=T) #음의 상관관계\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPearson's product-moment correlation\n\ndata:  sqrt(Wind) and Temp\nt = -6.3065, df = 151, p-value = 2.992e-09\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n -0.5737080 -0.3211886\nsample estimates:\n      cor \n-0.456596 \n```\n:::\n\n```{.r .cell-code}\ncor.test(Wind,t2,na.rm=T) #음의 상관관계\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPearson's product-moment correlation\n\ndata:  Wind and t2\nt = -6.3279, df = 151, p-value = 2.681e-09\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n -0.5747457 -0.3225764\nsample estimates:\n       cor \n-0.4578206 \n```\n:::\n\n```{.r .cell-code}\ndetach(airquality)\n```\n:::\n\n\nTemp와 Wind변수는 서로 음의 상관관계가 나타나는 것으로 보인다. Temp와 log(Wind)변수의 관계는 선형성이 잘 드러나는 것으로 보이며 Boxplot을 통해 확인한 두개의 Outlier들을 제거하면 잔차들도 잘 퍼져있는 것을 확인할 수 있다.\n\n### Temp\\~Solar.R\n\n\n::: {.cell}\n\n```{.r .cell-code}\nattach(airquality)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following objects are masked from airquality (pos = 3):\n\n    Day, Month, Ozone, Solar.R, Temp, Wind\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following objects are masked from airquality (pos = 4):\n\n    Day, Month, Ozone, Solar.R, Temp, Wind\n```\n:::\n\n```{.r .cell-code}\nplot(Temp~Solar.R,main=\"linearity of Temp ~ Solar.R\")\n\n(z <- line(x=Solar.R,y=Temp))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nline(x = Solar.R, y = Temp)\n\nCoefficients:\n[1]  75.42051   0.02051\n```\n:::\n\n```{.r .cell-code}\nabline(coef(z))\nz.ls <- lm(Temp~Solar.R)\nabline(z.ls$coef, lty=2,col=\"red\")\nlegend(x = 10, y = 95, c(\"R - Line\", \"Regression\"), \n       lty=c(1,2),lwd=2,col = c(\"black\",\"red\"),cex=0.7)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-17-1.png){width=672}\n:::\n\n```{.r .cell-code}\ncor.test(Temp,Solar.R,na.rm=T) #음의 상관관계\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPearson's product-moment correlation\n\ndata:  Temp and Solar.R\nt = 3.4437, df = 144, p-value = 0.0007518\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n 0.1187113 0.4194913\nsample estimates:\n      cor \n0.2758403 \n```\n:::\n\n```{.r .cell-code}\nairquality5=airquality[order(airquality$Solar.R),]\n\nmedSolar <- as.vector(3)\nmedTemp <- as.vector(3)\nmedSolar[1] <- median(airquality5$Solar.R[1:51],na.rm=T); medTemp[1] <- median(airquality5$Temp[1:51],na.rm=T)\nmedSolar[2] <- median(airquality5$Solar.R[52:102],na.rm=T); medTemp[2] <- median(airquality5$Temp[52:102],na.rm=T)\nmedSolar[3] <- median(airquality5$Solar.R[103:153],na.rm=T); medTemp[3] <- median(airquality5$Temp[103:153],na.rm=T)\nplot(medTemp ~ medSolar, type=\"b\") \n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-17-2.png){width=672}\n:::\n\n```{.r .cell-code}\n# Concave 한곡선 형태\n\nplot(y=log(Temp),x=Solar.R,main=\"Linearity of log Temp and Solar.R\")\n(z1<- line(y=log(Temp),x=Solar.R))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nline(y = log(Temp), x = Solar.R)\n\nCoefficients:\n[1]  4.323467  0.000263\n```\n:::\n\n```{.r .cell-code}\nabline(coef(z1))\nz1.ls <- lm(log(Temp) ~ Solar.R)\nabline(z1.ls$coef, lty=2,col=\"red\")\nlegend(x = 10, y =4.57, c(\"R - Line\", \"Regression\"), \n       lty=c(1,2),lwd=2,col = c(\"black\",\"red\"),cex=0.7)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-17-3.png){width=672}\n:::\n\n```{.r .cell-code}\nplot(y=sqrt(Temp),x=Solar.R,main=\"Linearity of sqrt Temp and Solar.R\")\n(z1<- line(y=sqrt(Temp),x=(Solar.R)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nline(y = sqrt(Temp), x = (Solar.R))\n\nCoefficients:\n[1]  8.685351  0.001161\n```\n:::\n\n```{.r .cell-code}\nabline(coef(z1))\nz1.ls <- lm(sqrt(Temp) ~ Solar.R)\nabline(z1.ls$coef, lty=2,col=\"red\")\nlegend(x = 10, y = 9.8, c(\"R - Line\", \"Regression\"), \n       lty=c(1,2),lwd=2,col = c(\"black\",\"red\"),cex=0.7)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-17-4.png){width=672}\n:::\n\n```{.r .cell-code}\ns2=Solar.R^2\nplot(y=Temp,x=s2,main=\"Linearity of Temp and Solar.R^2\")\n(z1<- line(y=Temp,x=s2))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nline(y = Temp, x = s2)\n\nCoefficients:\n[1]  7.654e+01  5.844e-05\n```\n:::\n\n```{.r .cell-code}\nabline(coef(z1))\nz1.ls <- lm(Temp ~ s2)\nabline(z1.ls$coef, lty=2,col=\"red\")\nlegend(x = 100, y =97, c(\"R - Line\", \"Regression\"), \n       lty=c(1,2),lwd=2,col = c(\"black\",\"red\"),cex=0.5)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-17-5.png){width=672}\n:::\n\n```{.r .cell-code}\nplot(residuals(z1) ~ fitted(z1), main = \"Residual plot by rline\") # 곡선 모양인 것으로 보인다.\nabline(0,0) \n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-17-6.png){width=672}\n:::\n\n```{.r .cell-code}\nplot(residuals(z2) ~ fitted(z2), main = \"Residual plot by rline\")\nabline(0,0) \n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-17-7.png){width=672}\n:::\n\n```{.r .cell-code}\nplot(residuals(z3) ~ fitted(z3), main = \"Residual plot by rline\")\nabline(0,0) \n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-17-8.png){width=672}\n:::\n\n```{.r .cell-code}\nboxplot(residuals(z1)) # 1 outliers\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-17-9.png){width=672}\n:::\n\n```{.r .cell-code}\nboxplot(residuals(z2)) # 2 outliers\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-17-10.png){width=672}\n:::\n\n```{.r .cell-code}\nboxplot(residuals(z3)) # 3 outliers\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-17-11.png){width=672}\n:::\n\n```{.r .cell-code}\nstem(residuals(z1))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  The decimal point is at the |\n\n  -22 | 7\n  -20 | 3\n  -18 | 98181\n  -16 | 5800\n  -14 | 866576\n  -12 | 6095\n  -10 | 86644\n   -8 | 75537\n   -6 | 76543\n   -4 | 6643166542\n   -2 | 87765308650\n   -0 | 8766543098766432\n    0 | 24455677711222\n    2 | 02377791233\n    4 | 12344457901134666\n    6 | 189003\n    8 | 44578159\n   10 | 1470138\n   12 | 5682\n   14 | 4554\n   16 | 2\n   18 | 1\n```\n:::\n\n```{.r .cell-code}\nstem(residuals(z2))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  The decimal point is at the |\n\n  -4 | 0\n  -3 | 911\n  -2 | 6532110\n  -1 | 99888777776544444333222211100\n  -0 | 999888666665322110\n   0 | 0111222333455555566667788889\n   1 | 000122333444456789\n   2 | 11367\n   3 | 0128\n   4 | 03\n   5 | \n   6 | 1\n```\n:::\n\n```{.r .cell-code}\nstem(residuals(z3))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  The decimal point is 1 digit(s) to the right of the |\n\n  -4 | 10\n  -3 | 773100\n  -2 | 88754332111\n  -1 | 888877666666655444443211100\n  -0 | 999977654220\n   0 | 011223344567888899999\n   1 | 0002222233344445556889\n   2 | 12238\n   3 | 00128\n   4 | 55\n   5 | \n   6 | \n   7 | 15\n   8 | \n   9 | \n  10 | \n  11 | 8\n```\n:::\n\n```{.r .cell-code}\ncor.test(log(Temp),Solar.R,na.rm=T)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPearson's product-moment correlation\n\ndata:  log(Temp) and Solar.R\nt = 3.471, df = 144, p-value = 0.0006847\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n 0.1208668 0.4212917\nsample estimates:\n      cor \n0.2778595 \n```\n:::\n\n```{.r .cell-code}\ncor.test(sqrt(Temp),Solar.R,na.rm=T)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPearson's product-moment correlation\n\ndata:  sqrt(Temp) and Solar.R\nt = 3.4587, df = 144, p-value = 0.0007142\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n 0.1198963 0.4204814\nsample estimates:\n      cor \n0.2769505 \n```\n:::\n\n```{.r .cell-code}\ncor.test(Temp,s2,na.rm=T)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPearson's product-moment correlation\n\ndata:  Temp and s2\nt = 2.2271, df = 144, p-value = 0.0275\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n 0.0206361 0.3349912\nsample estimates:\n      cor \n0.1824728 \n```\n:::\n\n```{.r .cell-code}\ndetach(airquality)\n```\n:::\n\n\nSolar.R변수와 Temp 변수는 서로 양의 상관관계를 가지고 있다. (다만 2차함수 곡선의 관계인 것으로 보인다.) 변환을 통해 그러한 경향성을 완화시키고자 하였는데 log변환의 경우 여전히 Residual Plot에서 곡선의 경향성이 남아있다 반면, Sqrt 변환은 위의 두개의 Outlier을 제외하면 곡선의 경향성이 다소 완화되어진 것으로 보인다.\n\n정리하면 세개의 변수들을 서로 상관성이 있는 것으로 보이며, multicollinearity issue가 발생할 수 있기 대문에 회귀분석을 진행할 때 유의해야 할 것으로 보인다. (wind \\<-- Temp \\<-- Solar.R, 한단계 거친 상관성)\n\n결측치 자료를 불완전 자료(incomplete data, missing data)라고 하고 불완전하지만 정보를 갖고 있으니 최대한 살려서 분석하려고 하는 시도는 당연한 것이다. missing 된 부분을 다른 자료들의 패턴을 이용하여 complete로 만들어 사용하려는 방법들이 Sampling (표본조사론) 분야에서 연구되고 있다. 당연히 Bayesian 방법도 가능하다. EDA 분야까지 응용되지는 않고 있다. (말 그대로 E=exploration, 있는 그대로 explore 해야지)\n\n# 3번\n\n## (가)\n\ntrees 자료를 multiple r-line으로 적합하여라.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nattach(trees)\n\ncor.test(log(Height),log(Girth))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPearson's product-moment correlation\n\ndata:  log(Height) and log(Girth)\nt = 3.3675, df = 29, p-value = 0.002155\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n 0.2165351 0.7446400\nsample estimates:\n      cor \n0.5301949 \n```\n:::\n\n```{.r .cell-code}\ncor.test(log(Height),log(Volume))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n\tPearson's product-moment correlation\n\ndata:  log(Height) and log(Volume)\nt = 4.5895, df = 29, p-value = 7.928e-05\nalternative hypothesis: true correlation is not equal to 0\n95 percent confidence interval:\n 0.3821245 0.8155363\nsample estimates:\n      cor \n0.6486377 \n```\n:::\n\n```{.r .cell-code}\nsummary(lm(log(Height)~log(Girth)+log(Volume),data=trees))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nlm(formula = log(Height) ~ log(Girth) + log(Volume), data = trees)\n\nResiduals:\n     Min       1Q   Median       3Q      Max \n-0.08628 -0.03084 -0.00146  0.02622  0.13465 \n\nCoefficients:\n            Estimate Std. Error t value Pr(>|t|)    \n(Intercept)  4.91689    0.22497  21.856  < 2e-16 ***\nlog(Girth)  -0.82177    0.19043  -4.315 0.000179 ***\nlog(Volume)  0.46196    0.08454   5.464 7.81e-06 ***\n---\nSignif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1\n\nResidual standard error: 0.05234 on 28 degrees of freedom\nMultiple R-squared:  0.6521,\tAdjusted R-squared:  0.6273 \nF-statistic: 26.24 on 2 and 28 DF,  p-value: 3.804e-07\n```\n:::\n\n```{.r .cell-code}\n# 1) Height ~ Volume --> Girth\nplot(log(Height)~log(Volume),main=\"Linearity of log Height ~ log Volume\")\n(z1 <- line(x=log(Volume),y=log(Height)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nline(x = log(Volume), y = log(Height))\n\nCoefficients:\n[1]  4.13492  0.06263\n```\n:::\n\n```{.r .cell-code}\nabline(coef(z1),lty=2,col=\"red\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-18-1.png){width=672}\n:::\n\n```{.r .cell-code}\nplot(residuals(z1) ~ fitted(z1), main = \"Residual plot by multiple rline: log Height ~ log Volume\")\nabline(0,0)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-18-2.png){width=672}\n:::\n\n```{.r .cell-code}\nplot(residuals(z1)~log(Girth),main=\"Linearity of Residuals ~ log Girth\")\n(z2 <- line(x=log(Girth),y=residuals(z1)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nline(x = log(Girth), y = residuals(z1))\n\nCoefficients:\n[1]  -0.02973   0.01057\n```\n:::\n\n```{.r .cell-code}\nabline(coef(z2),lty=2,col=\"red\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-18-3.png){width=672}\n:::\n\n```{.r .cell-code}\nplot(residuals(z2) ~ fitted(z2), main = \"Residual plot by multiple rline: Residual ~ log Girth\")\nabline(0,0)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-18-4.png){width=672}\n:::\n\n```{.r .cell-code}\nstem(residuals(z2)) # 0을 기준으로 대칭적인 종모양\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  The decimal point is 1 digit(s) to the left of the |\n\n  -1 | 8\n  -1 | 310\n  -0 | 9975\n  -0 | 3332100\n   0 | 0001111234\n   0 | 6689\n   1 | 01\n```\n:::\n\n```{.r .cell-code}\nboxplot(residuals(z2)) # outlier 1개\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-18-5.png){width=672}\n:::\n\n```{.r .cell-code}\n# 끝에 있는 한 점만 제외하면 전반적으로 Residual들이 적합이 잘 된 것으로 보인다.\n\nsum(residuals(z1)^2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.1480616\n```\n:::\n\n```{.r .cell-code}\n# 2) Height ~  Girth --> Volume \n\nplot(log(Height)~log(Girth),main=\"Linearity of log Height ~ log Girth\")\n(z3 <- line(x=log(Girth),y=log(Height)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nline(x = log(Girth), y = log(Height))\n\nCoefficients:\n[1]  3.987  0.137\n```\n:::\n\n```{.r .cell-code}\nabline(coef(z3),lty=2,col=\"red\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-18-6.png){width=672}\n:::\n\n```{.r .cell-code}\nplot(residuals(z3) ~ fitted(z3), main = \"Residual plot by multiple rline: log Height ~ log Girth\")\nabline(0,0)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-18-7.png){width=672}\n:::\n\n```{.r .cell-code}\nplot(y=residuals(z3),x=log(Volume),main=\"Linearity of Residuals ~ log Volume\")\n(z4 <- line(y=residuals(z3),x=log(Volume)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nline(y = residuals(z3), x = log(Volume))\n\nCoefficients:\n[1]  -0.037395   0.009474\n```\n:::\n\n```{.r .cell-code}\nabline(coef(z4),lty=2,col=\"red\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-18-8.png){width=672}\n:::\n\n```{.r .cell-code}\nplot(residuals(z4) ~ fitted(z4), main = \"Residual plot by multiple rline: Residual ~ log Volume\")\nabline(0,0)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-18-9.png){width=672}\n:::\n\n```{.r .cell-code}\n# 끝에 있는 한 점만 제외하면 전반적으로 Residual들이 적합이 잘 된 것으로 보인다.\n\nstem(residuals(z4)) #0 을 기준으로 대칭적인 종모양\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  The decimal point is 1 digit(s) to the left of the |\n\n  -1 | 8\n  -1 | 31\n  -0 | 99885\n  -0 | 2221000\n   0 | 011122234\n   0 | 6679\n   1 | 122\n```\n:::\n\n```{.r .cell-code}\nboxplot(residuals(z4)) # outlier 1개\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-18-10.png){width=672}\n:::\n\n```{.r .cell-code}\nsum(residuals(z3)^2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.1667806\n```\n:::\n\n```{.r .cell-code}\ndetach(trees)\n```\n:::\n\n\n두가지 방식 중 첫번째 방식이 더 적합해 보이는 것으로 보인다. 잔차 제곱의 합의 값이 첫번째 방식이 더 작게 나타나고 있기 때문이다. . 또한 회귀분석을 같이 놓고 돌렸을 때 계수의 값이 더 크게 나타나는 것을 확인할 수 있다.\n\n## (나)\n\nairquality 자료를 multiple r-line으로 적합하여라.\n\nOzone \\~ Temp ==\\> Wind ==\\> Solar.R (위에서 이유는 이미 언급함)\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(airquality)\n\nair2=airquality[!is.na(airquality$Ozone),]\nair2\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n    Ozone Solar.R Wind Temp Month Day\n1      41     190  7.4   67     5   1\n2      36     118  8.0   72     5   2\n3      12     149 12.6   74     5   3\n4      18     313 11.5   62     5   4\n6      28      NA 14.9   66     5   6\n7      23     299  8.6   65     5   7\n8      19      99 13.8   59     5   8\n9       8      19 20.1   61     5   9\n11      7      NA  6.9   74     5  11\n12     16     256  9.7   69     5  12\n13     11     290  9.2   66     5  13\n14     14     274 10.9   68     5  14\n15     18      65 13.2   58     5  15\n16     14     334 11.5   64     5  16\n17     34     307 12.0   66     5  17\n18      6      78 18.4   57     5  18\n19     30     322 11.5   68     5  19\n20     11      44  9.7   62     5  20\n21      1       8  9.7   59     5  21\n22     11     320 16.6   73     5  22\n23      4      25  9.7   61     5  23\n24     32      92 12.0   61     5  24\n28     23      13 12.0   67     5  28\n29     45     252 14.9   81     5  29\n30    115     223  5.7   79     5  30\n31     37     279  7.4   76     5  31\n38     29     127  9.7   82     6   7\n40     71     291 13.8   90     6   9\n41     39     323 11.5   87     6  10\n44     23     148  8.0   82     6  13\n47     21     191 14.9   77     6  16\n48     37     284 20.7   72     6  17\n49     20      37  9.2   65     6  18\n50     12     120 11.5   73     6  19\n51     13     137 10.3   76     6  20\n62    135     269  4.1   84     7   1\n63     49     248  9.2   85     7   2\n64     32     236  9.2   81     7   3\n66     64     175  4.6   83     7   5\n67     40     314 10.9   83     7   6\n68     77     276  5.1   88     7   7\n69     97     267  6.3   92     7   8\n70     97     272  5.7   92     7   9\n71     85     175  7.4   89     7  10\n73     10     264 14.3   73     7  12\n74     27     175 14.9   81     7  13\n76      7      48 14.3   80     7  15\n77     48     260  6.9   81     7  16\n78     35     274 10.3   82     7  17\n79     61     285  6.3   84     7  18\n80     79     187  5.1   87     7  19\n81     63     220 11.5   85     7  20\n82     16       7  6.9   74     7  21\n85     80     294  8.6   86     7  24\n86    108     223  8.0   85     7  25\n87     20      81  8.6   82     7  26\n88     52      82 12.0   86     7  27\n89     82     213  7.4   88     7  28\n90     50     275  7.4   86     7  29\n91     64     253  7.4   83     7  30\n92     59     254  9.2   81     7  31\n93     39      83  6.9   81     8   1\n94      9      24 13.8   81     8   2\n95     16      77  7.4   82     8   3\n96     78      NA  6.9   86     8   4\n97     35      NA  7.4   85     8   5\n98     66      NA  4.6   87     8   6\n99    122     255  4.0   89     8   7\n100    89     229 10.3   90     8   8\n101   110     207  8.0   90     8   9\n104    44     192 11.5   86     8  12\n105    28     273 11.5   82     8  13\n106    65     157  9.7   80     8  14\n108    22      71 10.3   77     8  16\n109    59      51  6.3   79     8  17\n110    23     115  7.4   76     8  18\n111    31     244 10.9   78     8  19\n112    44     190 10.3   78     8  20\n113    21     259 15.5   77     8  21\n114     9      36 14.3   72     8  22\n116    45     212  9.7   79     8  24\n117   168     238  3.4   81     8  25\n118    73     215  8.0   86     8  26\n120    76     203  9.7   97     8  28\n121   118     225  2.3   94     8  29\n122    84     237  6.3   96     8  30\n123    85     188  6.3   94     8  31\n124    96     167  6.9   91     9   1\n125    78     197  5.1   92     9   2\n126    73     183  2.8   93     9   3\n127    91     189  4.6   93     9   4\n128    47      95  7.4   87     9   5\n129    32      92 15.5   84     9   6\n130    20     252 10.9   80     9   7\n131    23     220 10.3   78     9   8\n132    21     230 10.9   75     9   9\n133    24     259  9.7   73     9  10\n134    44     236 14.9   81     9  11\n135    21     259 15.5   76     9  12\n136    28     238  6.3   77     9  13\n137     9      24 10.9   71     9  14\n138    13     112 11.5   71     9  15\n139    46     237  6.9   78     9  16\n140    18     224 13.8   67     9  17\n141    13      27 10.3   76     9  18\n142    24     238 10.3   68     9  19\n143    16     201  8.0   82     9  20\n144    13     238 12.6   64     9  21\n145    23      14  9.2   71     9  22\n146    36     139 10.3   81     9  23\n147     7      49 10.3   69     9  24\n148    14      20 16.6   63     9  25\n149    30     193  6.9   70     9  26\n151    14     191 14.3   75     9  28\n152    18     131  8.0   76     9  29\n153    20     223 11.5   68     9  30\n```\n:::\n\n```{.r .cell-code}\nair2=air2[!is.na(air2$Solar.R),]\n\ndim(air2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 111   6\n```\n:::\n\n```{.r .cell-code}\ncolSums(is.na(air2))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  Ozone Solar.R    Wind    Temp   Month     Day \n      0       0       0       0       0       0 \n```\n:::\n\n```{.r .cell-code}\nattach(air2)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following objects are masked from airquality (pos = 3):\n\n    Day, Month, Ozone, Solar.R, Temp, Wind\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following objects are masked from airquality (pos = 4):\n\n    Day, Month, Ozone, Solar.R, Temp, Wind\n```\n:::\n\n```{.r .cell-code}\n# 결측치들을 Drop해서 중간에 Fit에서 Length가 안 맞아서 생기는 오류를 해결하고자 하였음.\n\nplot(y=sqrt(Ozone),x=Temp,main=\"Linearity of sqrt Ozone ~ Temp\")\n(z <- line(x=Temp,y=sqrt(Ozone)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nline(x = Temp, y = sqrt(Ozone))\n\nCoefficients:\n[1]  -12.9829    0.2456\n```\n:::\n\n```{.r .cell-code}\nabline(coef(z),lty=2,col=\"red\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-19-1.png){width=672}\n:::\n\n```{.r .cell-code}\nplot(residuals(z) ~ fitted(z), main = \"Residual plot by multiple rline: sqrt Ozone ~ Temp\")\nabline(0,0)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-19-2.png){width=672}\n:::\n\n```{.r .cell-code}\nplot(y=residuals(z),x= Wind, main=\"Linearity of residuals ~ Wind\")\n(z1 <- line(x=Wind,y=residuals(z)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nline(x = Wind, y = residuals(z))\n\nCoefficients:\n[1]   1.1115  -0.1428\n```\n:::\n\n```{.r .cell-code}\nabline(coef(z1),lty=2,col=\"red\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-19-3.png){width=672}\n:::\n\n```{.r .cell-code}\nplot(residuals(z1) ~ fitted(z1), main = \"Residual plot by multiple rline: residuals ~ Wind\")\nabline(0,0)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-19-4.png){width=672}\n:::\n\n```{.r .cell-code}\nplot(y=residuals(z1),x=Solar.R,main=\"Linearity of residuals ~ Solar.R\")\n(z2 <- line(x=Solar.R,y=residuals(z1)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nline(x = Solar.R, y = residuals(z1))\n\nCoefficients:\n[1]  -1.128031   0.005224\n```\n:::\n\n```{.r .cell-code}\nabline(coef(z2),lty=2,col=\"red\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-19-5.png){width=672}\n:::\n\n```{.r .cell-code}\nplot(residuals(z2) ~ fitted(z2), main = \"Residual plot by multiple rline: residuals ~ Solar.R\")\nabline(0,0)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-19-6.png){width=672}\n:::\n\n```{.r .cell-code}\nsum(residuals(z2)^2) # 328.3632\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 328.3632\n```\n:::\n\n```{.r .cell-code}\ndetach(air2)\n```\n:::\n\n\nOzone \\~ Wind ==\\> Temp ==\\> Solar.R (회귀분석 회귀계수가 큰 순서대로 )\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(airquality)\n\nair2=airquality[!is.na(airquality$Ozone),]\nair2\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n    Ozone Solar.R Wind Temp Month Day\n1      41     190  7.4   67     5   1\n2      36     118  8.0   72     5   2\n3      12     149 12.6   74     5   3\n4      18     313 11.5   62     5   4\n6      28      NA 14.9   66     5   6\n7      23     299  8.6   65     5   7\n8      19      99 13.8   59     5   8\n9       8      19 20.1   61     5   9\n11      7      NA  6.9   74     5  11\n12     16     256  9.7   69     5  12\n13     11     290  9.2   66     5  13\n14     14     274 10.9   68     5  14\n15     18      65 13.2   58     5  15\n16     14     334 11.5   64     5  16\n17     34     307 12.0   66     5  17\n18      6      78 18.4   57     5  18\n19     30     322 11.5   68     5  19\n20     11      44  9.7   62     5  20\n21      1       8  9.7   59     5  21\n22     11     320 16.6   73     5  22\n23      4      25  9.7   61     5  23\n24     32      92 12.0   61     5  24\n28     23      13 12.0   67     5  28\n29     45     252 14.9   81     5  29\n30    115     223  5.7   79     5  30\n31     37     279  7.4   76     5  31\n38     29     127  9.7   82     6   7\n40     71     291 13.8   90     6   9\n41     39     323 11.5   87     6  10\n44     23     148  8.0   82     6  13\n47     21     191 14.9   77     6  16\n48     37     284 20.7   72     6  17\n49     20      37  9.2   65     6  18\n50     12     120 11.5   73     6  19\n51     13     137 10.3   76     6  20\n62    135     269  4.1   84     7   1\n63     49     248  9.2   85     7   2\n64     32     236  9.2   81     7   3\n66     64     175  4.6   83     7   5\n67     40     314 10.9   83     7   6\n68     77     276  5.1   88     7   7\n69     97     267  6.3   92     7   8\n70     97     272  5.7   92     7   9\n71     85     175  7.4   89     7  10\n73     10     264 14.3   73     7  12\n74     27     175 14.9   81     7  13\n76      7      48 14.3   80     7  15\n77     48     260  6.9   81     7  16\n78     35     274 10.3   82     7  17\n79     61     285  6.3   84     7  18\n80     79     187  5.1   87     7  19\n81     63     220 11.5   85     7  20\n82     16       7  6.9   74     7  21\n85     80     294  8.6   86     7  24\n86    108     223  8.0   85     7  25\n87     20      81  8.6   82     7  26\n88     52      82 12.0   86     7  27\n89     82     213  7.4   88     7  28\n90     50     275  7.4   86     7  29\n91     64     253  7.4   83     7  30\n92     59     254  9.2   81     7  31\n93     39      83  6.9   81     8   1\n94      9      24 13.8   81     8   2\n95     16      77  7.4   82     8   3\n96     78      NA  6.9   86     8   4\n97     35      NA  7.4   85     8   5\n98     66      NA  4.6   87     8   6\n99    122     255  4.0   89     8   7\n100    89     229 10.3   90     8   8\n101   110     207  8.0   90     8   9\n104    44     192 11.5   86     8  12\n105    28     273 11.5   82     8  13\n106    65     157  9.7   80     8  14\n108    22      71 10.3   77     8  16\n109    59      51  6.3   79     8  17\n110    23     115  7.4   76     8  18\n111    31     244 10.9   78     8  19\n112    44     190 10.3   78     8  20\n113    21     259 15.5   77     8  21\n114     9      36 14.3   72     8  22\n116    45     212  9.7   79     8  24\n117   168     238  3.4   81     8  25\n118    73     215  8.0   86     8  26\n120    76     203  9.7   97     8  28\n121   118     225  2.3   94     8  29\n122    84     237  6.3   96     8  30\n123    85     188  6.3   94     8  31\n124    96     167  6.9   91     9   1\n125    78     197  5.1   92     9   2\n126    73     183  2.8   93     9   3\n127    91     189  4.6   93     9   4\n128    47      95  7.4   87     9   5\n129    32      92 15.5   84     9   6\n130    20     252 10.9   80     9   7\n131    23     220 10.3   78     9   8\n132    21     230 10.9   75     9   9\n133    24     259  9.7   73     9  10\n134    44     236 14.9   81     9  11\n135    21     259 15.5   76     9  12\n136    28     238  6.3   77     9  13\n137     9      24 10.9   71     9  14\n138    13     112 11.5   71     9  15\n139    46     237  6.9   78     9  16\n140    18     224 13.8   67     9  17\n141    13      27 10.3   76     9  18\n142    24     238 10.3   68     9  19\n143    16     201  8.0   82     9  20\n144    13     238 12.6   64     9  21\n145    23      14  9.2   71     9  22\n146    36     139 10.3   81     9  23\n147     7      49 10.3   69     9  24\n148    14      20 16.6   63     9  25\n149    30     193  6.9   70     9  26\n151    14     191 14.3   75     9  28\n152    18     131  8.0   76     9  29\n153    20     223 11.5   68     9  30\n```\n:::\n\n```{.r .cell-code}\nair2=air2[!is.na(air2$Solar.R),]\n\ndim(air2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 111   6\n```\n:::\n\n```{.r .cell-code}\ncolSums(is.na(air2))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  Ozone Solar.R    Wind    Temp   Month     Day \n      0       0       0       0       0       0 \n```\n:::\n\n```{.r .cell-code}\nattach(air2)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following objects are masked from airquality (pos = 3):\n\n    Day, Month, Ozone, Solar.R, Temp, Wind\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following objects are masked from airquality (pos = 4):\n\n    Day, Month, Ozone, Solar.R, Temp, Wind\n```\n:::\n\n```{.r .cell-code}\n# 결측치들을 Drop해서 중간에 Fit에서 Length가 안 맞아서 생기는 오류를 해결하고자 하였음.\n\nplot(y=sqrt(Ozone),x=(Wind),main=\"Linearity of sqrt Ozone ~ Wind\")\n(z <- line(x=(Wind),y=sqrt(Ozone)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nline(x = (Wind), y = sqrt(Ozone))\n\nCoefficients:\n[1]  11.5705  -0.5507\n```\n:::\n\n```{.r .cell-code}\nabline(coef(z),lty=2,col=\"red\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-20-1.png){width=672}\n:::\n\n```{.r .cell-code}\nplot(residuals(z) ~ fitted(z), main = \"Residual plot by multiple rline: sqrt Ozone ~ Wind\")\nabline(0,0)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-20-2.png){width=672}\n:::\n\n```{.r .cell-code}\nplot(y=residuals(z),x=Temp,main=\"Linearity of residuals ~ Temp\")\n(z1 <- line(x=Temp,y=residuals(z)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nline(x = Temp, y = residuals(z))\n\nCoefficients:\n[1]  -9.2509   0.1155\n```\n:::\n\n```{.r .cell-code}\nabline(coef(z1),lty=2,col=\"red\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-20-3.png){width=672}\n:::\n\n```{.r .cell-code}\nplot(residuals(z1) ~ fitted(z1), main = \"Residual plot by multiple rline: residuals ~ Temp\")\nabline(0,0)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-20-4.png){width=672}\n:::\n\n```{.r .cell-code}\nplot(y=residuals(z1),x=Solar.R,main=\"Linearity of residuals ~ Solar.R\")\n(z2 <- line(x=Solar.R,y=residuals(z1)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nCall:\nline(x = Solar.R, y = residuals(z1))\n\nCoefficients:\n[1]  -1.212414   0.005828\n```\n:::\n\n```{.r .cell-code}\nabline(coef(z2),lty=2,col=\"red\")\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-20-5.png){width=672}\n:::\n\n```{.r .cell-code}\nplot(residuals(z2) ~ fitted(z2), main = \"Residual plot by multiple rline: residuals ~ Solar.R\")\nabline(0,0)\n```\n\n::: {.cell-output-display}\n![](index_files/figure-html/unnamed-chunk-20-6.png){width=672}\n:::\n\n```{.r .cell-code}\nsum(residuals(z2)^2) #360.3426\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 360.3426\n```\n:::\n\n```{.r .cell-code}\ndetach(air2)\n```\n:::\n\n\n아래의 방식보다 위의 방식에서 잔차제곱의 합이 작게 나타난다. 따라서 위의 방식에서의 적합이 더 잘 이루어졌음을 확인해볼 수 있다.\n\n주의: multiple R-line은 sequential 방법이다. simultaneous 방법으로 하면 다른 결과 나올 수 있다.\n",
    "supporting": [
      "index_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}