project:
  type: website

website:
  title: "Sangwon Ju's Personal Page"
  page-footer:
    background: light
    center:
        - text: "© 2022 Sangwon Ju"




  navbar:
    background: dark
    pinned: true
    logo: ./logo/policy.png
    page-navigation: true
    collapse-below: md

    left:
        - text: "About Me"
          file: index.qmd
        - sidebar:Research
        - sidebar:Data_Analytics_Projects
        - text: "CV (as of July 2022)"
          file: cv.rmd

    right:
        - icon: mailbox2
          href: "mailto: sangwon.ju@snu.ac.kr"
          aria-label: E-mail
        - icon: github
          href: https://github.com/SangwonJu
          aria-label: Github
        - icon: linkedin
          href: https://www.linkedin.com/in/sangwon-ju-37a6b0216/
          aria-label: Linkedin


  sidebar:
    - id: Research
      title: "Research"
      style: "floating"
      contents:
        - text: "Research Interests"
          href: research_interests.qmd
        - text: "Publications / Working Papers"
          href: publication.qmd



    - id: Data_Analytics_Projects
      title: "Data Analytics Projects"
      style: "floating"
      background: secondary
      collapse-level: 2
      contents:
      - section: Data Analytics for Public Data (2021 Fall)
        contents:
        - text: "Analysis 1: Number of local government employees"
          href: ./data_analytics/employees.qmd
        - text: "Analysis 2: Seasonal disparities in unemployment index"
          href: ./data_analytics/unemployment_index.qmd
        - text: "Analysis 3: Analysis of the FWA in public sector organizations using data mining techniques"
          href: ./data_analytics/FWA.ipynb

      - section: Exploratory Data Analysis (2021 Spring) [in Korean]
        contents:
        - text: "EDA Assignment 7"
          href: ./data_analytics/EDA7.rmd
        - text: "EDA Assignment 8"
          href: ./data_analytics/EDA8_Final.rmd

format:
  html:
    theme: Minty
    css: styles.css
    toc: true


execute:
  freeze: auto


editor: visual

