project:
  type: website
  output-dir: _site

website:
  title: "Sangwon Ju"
  repo-url: https://github.com/SangwonJu/Personal-Page
  page-footer:
    background: dark
    center:
        - text: "© 2022 Sangwon Ju"

  navbar:
    background: dark
    fontcolor: white
    page-navigation: true
    collapse-below: md

    left:
        - text: "About Me"
          file: index.qmd
        - text: "Curriculum Vitae"
          file: CV2.qmd
        - text: "Data Analytics"
          file: data_analytics.qmd


    right:
        - icon: mailbox2
          href: "mailto: sangwon.ju@snu.ac.kr"
          aria-label: E-mail
        - icon: github
          href: https://github.com/SangwonJu
          aria-label: Github
        - icon: linkedin
          href: https://www.linkedin.com/in/sangwon-ju-37a6b0216/
          aria-label: Linkedin


format:
  html:
    theme:
        - Sandstone
        - sandstone.scss
    toc: true
    linestretch: 1.5

execute:
  freeze: auto