project:
  type: website

website:
  title: "Sangwon Ju's Personal Page"
  page-footer:
    background: dark
    center:
        - text: "© 2022 Sangwon Ju"




  navbar:
    background: light

    pinned: true
    logo: ./logo/policy.png
    page-navigation: true
    collapse-below: md

    left:
        - text: "About Me"
          file: index.qmd
        - sidebar:Research
        - text: "Data Analytics"
          file: data_analytics.qmd
        - text: "CV (as of July 2022)"
          file: cv.qmd

    right:
        - icon: mailbox2
          href: "mailto: sangwon.ju@snu.ac.kr"
          aria-label: E-mail
        - icon: github
          href: https://github.com/SangwonJu
          aria-label: Github
        - icon: linkedin
          href: https://www.linkedin.com/in/sangwon-ju-37a6b0216/
          aria-label: Linkedin


  sidebar:

    - id: Research
      title: "Research"
      style: "floating"
      contents:
        - text: "Research Interests"
          href: research_interests.qmd
        - text: "Publications / Working Papers"
          href: publication.qmd

    - id: dummy
      title: "Research"
      contents:
        - text: "Research Interests"
          href: research_interests.qmd
        - text: "Publications / Working Papers"
          href: publication.qmd

format:
  html:
    theme:
        light: Simplex
        dark: darkly

    css: styles.css
    toc: true


execute:
  freeze: auto


editor: visual

