---
"title": Research
---

# Publication

::: justify
-  **Ju, S.,** Lee, J. & Kim, B.J. (2022). Evidence-Based Policy in Asian Countries: A Comparative Analysis of Evidence-Based Policy Implementation in Myanmar, Indonesia, Hong Kong, Japan, and South Korea. *Korean Society and Public Administration*, 33(3), 97-131. DOI: <https://doi.org/10.53865/KSPA.2022.11.33.3.97>
    -   Abstract: <br> The present study explores the process of evidence-based policy (EBP) implementation in five Asian countries including Myanmar, Indonesia, Hong Kong, Japan, and South Korea. Building on the model of Evidence-based Practice Implementation (EPIS framework; Aarons et al., 2011; Moullin et al., 2019), this study conducted an exploratory comparative case study on five policy cases--a single policy case from each of the five Asian countries--and evaluated the extent to which each policy case has accomplished each of the four levels (i.e., exploration, preparation, implementation, sustainment) of EBP implementation suggested by the EPIS framework. Our findings suggest that the evaluation of the five EBP cases in Asian countries ranged from level 1 (exploration) to level 2 (preparation) out of a total of four levels. We discuss the theoretical and practical implications of our findings.
    - Keywords: Evidence-Based Policy, The Model of Evidence-based Practice Implementation, Comparative Policy
Research, Collective Case Study, Asian countries 
:::

# Working Papers

::: justify
- Lee, J.\*, **Ju, S.**\* & Kim, B.J., Social Motivation and Policy Compliance in Crisis: Moderating Role of Ideological Self-Categorization in the United States and South Korea <br>
(\* First and Second Author Contributed Equally)
    - Abstract: <br> This article explores the role of social motivation for policy compliance in the context of uncertainty induced by the COVID-19 pandemic. The focus is on how citizens' calculative (out of deterrent fear) and normative (out of a sense of duty) compliance motivation are affected by their ideological self-categorization in response to coercive prevention policies. Results from a three-way interaction analysis using survey data from the United States and South Korea suggests potential role of ideological identification on the association between motivations for compliance and dissonance in compliance. The degree of the categorization effect was moderated by the individualistic-collectivistic cultural dimension of the two countries. By integrating the social identity approach into research on policy compliance, this article concludes that policymakers should consider citizens' propensity to conform to in-group norms when shaping the policy response to widespread crises as it plays a critical role in effectively managing their cooperation.
    - Keywords: social motivation, self-categorization theory, policy compliance, ideological identification
    
    
- **Ju, S. **& Kim, B.J., The Role of Information Technology on Improving Organizational Performance: Evidence from Korean Public Organizations <br>
(Preparation in manuscript, Target journal: *Government Information Quarterly*)  
    - Abstract: <br> In the last three decades, e-government researchers have focused on various aspects of information technology, including the technology itself, how organizations utilize it, and its application in diverse contexts. Nevertheless, there needs to be more theoretical discussion and empirical evidence on how these factors influence attaining strategic goals in public organizations. Thus, this study aims to examine how investing in IT resources can enhance the capabilities of public organizations and subsequently improve the organization's overall performance. Based on the resource-based view (RBV) and public value theory, this study empirically examines the influence of IT on public-sector organizations. To investigate the impact of IT investment on organizational performance, this article analyzed four-year archival panel data from 482 South Korean public enterprises and quasi-governmental institutions using a fixed-effects model and a random-effects ordered logit model. The findings indicate a positive relationship between total investment in IT and operational capabilities. Furthermore, investing in IT resources positively impacts organizational performance, with operational capabilities serving as a mediator. The analysis revealed that investing in infrastructure for capacity-building, when compared to software and hardware maintenance, improves performance more. The article contributes to understanding e-government performance by discussing how investing in information technology can improve organizational outcomes. It also emphasizes the importance of strategic IT investment in gaining a competitive advantage in the political reputation market. This study sheds light on the intricate connection between IT resources and public organizational performance.
    
    - Keywords: Public Sector IT Strategy, IT Resource, Organizational Performance, Public Value Theory, Resource Based View, E-Government
    
- **Ju, S.**, Exploring the Micro-Determinants of Evidence-Based Practice: The Influence of Organizational Identification on Managerial Epistemic Motivation <br>
(Gathering preliminary findings) <br>

    - Abstract: <br> The evidence-based practice has been recognized as a potential solution to the well-known academia-practice gap. Many studies, from the perspective of the research producer, assume that by presenting rigorous scientific evidence in easily accessible venues, this gap will diminish. However, in reality, many practitioners are still unaware of such evidence or skeptical of academics, leading to an underutilization of research. Thus, from the perspective of research users, this study investigates managerial psychological processes as a potential obstacle to bridging the academia–practice gap. Specifically, by extending the reasoning of motivated information processing, this study aims to explore how epistemic motivations, which influence the depth of managers' information processing, are shaped by pro-organizational motivations, which influence the direction of managers' information processing. We conducted the analysis with survey data collected from social workers employed at public service organizations in South Korea. The result provides preliminary evidence that managers with strong organizational identification define themselves through affiliation and subsequently channel their epistemic motivation toward systematic information processing, enabling them to make well-informed pro-organization decisions. In contrast to previous literature that has primarily focused on the role of research providers, we suggest that more theoretical and practical attention should be given to the practitioners’ cognitive styles and their interaction with motivations, particularly for managers who have the authority to influence decisions when implementing evidence-based practice in the public organizations.
    <br>

- **Ju, S.**, Public-Private Collaboration and Ambidexterity in Public Sector: Boundary Condition of Political Environment <br>
(Gathering preliminary findings) <br>

- Lee, B., **Ju, S.**, Lee, J., & Kim, B.J., Exploring the Challenges and Alternatives of SDGs Implementation:
Text-Mining on UN SDG Voluntary National Review of 6 Countries [in Korean] <br>
(Completed data analysis and Writing in progress)<br>
:::

# Academic Presentations

::: justify
- **Ju, S.** & Lee, J. (2024), How does Self-Categorization shape Compliance?: Political Ideology and COVID-19, *2024 ASPA Annual Conference: Building Resilient Communities*, Minneapolis, MN, April 2024.

- **Ju, S** (2024), Exploring the Micro-Determinants of Evidence-Based Practice: The Influence of Organizational Identification on Managerial Epistemic Motivation, *Seoul National University - Victoria University of Wellington 2024 Conference: Resilient Governance and Future-Proofing Public Administration*, Auckland, New Zealand, January 2024

-  **Ju, S.** & Lee, J. (2022), Evidence-Based Policy in Asian Countries: Applying Model of Evidence-Based Practice Implementation for Maturation Stage Analysis \[in Korean, Poster Session\], *2022 Korean Public Administration Summer Conference and Annual KAPA International Conference*, Yeosu, Korea, June 2022.
:::

