<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.1.189">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Sangwon Ju, SNU GSPA">
<meta name="dcterms.date" content="2022-10-12">

<title>Sangwon Ju’s Personal Page - Assignment 1</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<script src="../../site_libs/quarto-html/quarto.js"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-text-highlighting-styles">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" class="quarto-color-scheme" id="quarto-bootstrap" data-mode="light">
<link href="../../site_libs/bootstrap/bootstrap-dark.min.css" rel="prefetch" class="quarto-color-scheme quarto-color-alternate" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.6/require.min.js" integrity="sha512-c3Nl8+7g4LMSTdrm621y7kf9v3SDPnhxLNhcjFJbKECVnmZHTdo+IRO05sNLTH/D3vA6u1X32ehoLC7WFVdheg==" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
<script type="application/javascript">define('jquery', [],function() {return window.jQuery;})</script>

  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<link rel="stylesheet" href="styles.css">
</head>

<body class="nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-md navbar-dark ">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container">
    <a href="../../index.html" class="navbar-brand navbar-brand-logo">
    <img src="../.././logo/policy.png" alt="" class="navbar-logo">
    </a>
    <a class="navbar-brand" href="../../index.html">
    <span class="navbar-title">Sangwon Ju’s Personal Page</span>
    </a>
  </div>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
  <span class="navbar-toggler-icon"></span>
</button>
          <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav navbar-nav-scroll me-auto">
  <li class="nav-item">
    <a class="nav-link" href="../../index.html">About Me</a>
  </li>  
  <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle" href="#" id="nav-menu-research" role="button" data-bs-toggle="dropdown" aria-expanded="false">Research</a>
    <ul class="dropdown-menu" aria-labelledby="nav-menu-research">    
        <li>
    <a class="dropdown-item" href="../../research_interests.html">
 <span class="dropdown-text">Research Interests</span></a>
  </li>  
        <li>
    <a class="dropdown-item" href="../../publication.html">
 <span class="dropdown-text">Publications / Working Papers</span></a>
  </li>  
    </ul>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="../../data_analytics.html">Data Analytics</a>
  </li>  
  <li class="nav-item">
    <a class="nav-link" href="../../cv.html">CV (as of July 2022)</a>
  </li>  
</ul>
            <ul class="navbar-nav navbar-nav-scroll ms-auto">
  <li class="nav-item compact">
    <a class="nav-link" href="mailto: sangwon.ju@snu.ac.kr"><i class="bi bi-mailbox2" role="img" aria-label="E-mail">
</i> 
 </a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://github.com/SangwonJu"><i class="bi bi-github" role="img" aria-label="Github">
</i> 
 </a>
  </li>  
  <li class="nav-item compact">
    <a class="nav-link" href="https://www.linkedin.com/in/sangwon-ju-37a6b0216/"><i class="bi bi-linkedin" role="img" aria-label="Linkedin">
</i> 
 </a>
  </li>  
</ul>
              <div class="quarto-toggle-container">
                  <a href="" class="quarto-color-scheme-toggle nav-link" onclick="window.quartoToggleColorScheme(); return false;" title="Toggle dark mode"><i class="bi"></i></a>
              </div>
              <div id="quarto-search" class="" title="Search"></div>
          </div> <!-- /navcollapse -->
      </div> <!-- /container-fluid -->
    </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#준비" id="toc-준비" class="nav-link active" data-scroll-target="#준비">0. 준비</a></li>
  <li><a href="#question-1" id="toc-question-1" class="nav-link" data-scroll-target="#question-1">1. Question 1</a>
  <ul class="collapse">
  <li><a href="#loading-dataset" id="toc-loading-dataset" class="nav-link" data-scroll-target="#loading-dataset">Loading Dataset</a></li>
  <li><a href="#a" id="toc-a" class="nav-link" data-scroll-target="#a">(a)</a></li>
  <li><a href="#b" id="toc-b" class="nav-link" data-scroll-target="#b">(b)</a></li>
  <li><a href="#c" id="toc-c" class="nav-link" data-scroll-target="#c">(c)</a></li>
  <li><a href="#d" id="toc-d" class="nav-link" data-scroll-target="#d">(d)</a></li>
  </ul></li>
  <li><a href="#question-2" id="toc-question-2" class="nav-link" data-scroll-target="#question-2">2. Question 2</a>
  <ul class="collapse">
  <li><a href="#loading-dataset-1" id="toc-loading-dataset-1" class="nav-link" data-scroll-target="#loading-dataset-1">Loading Dataset</a></li>
  <li><a href="#a-1" id="toc-a-1" class="nav-link" data-scroll-target="#a-1">(a)</a></li>
  <li><a href="#b-1" id="toc-b-1" class="nav-link" data-scroll-target="#b-1">(b)</a></li>
  <li><a href="#c-1" id="toc-c-1" class="nav-link" data-scroll-target="#c-1">(c)</a></li>
  <li><a href="#d-1" id="toc-d-1" class="nav-link" data-scroll-target="#d-1">(d)</a></li>
  </ul></li>
  <li><a href="#question-3" id="toc-question-3" class="nav-link" data-scroll-target="#question-3">3. Question 3</a>
  <ul class="collapse">
  <li><a href="#loading-dataset-2" id="toc-loading-dataset-2" class="nav-link" data-scroll-target="#loading-dataset-2">Loading Dataset</a></li>
  <li><a href="#a-2" id="toc-a-2" class="nav-link" data-scroll-target="#a-2">(a)</a></li>
  <li><a href="#b-2" id="toc-b-2" class="nav-link" data-scroll-target="#b-2">(b)</a></li>
  <li><a href="#c-2" id="toc-c-2" class="nav-link" data-scroll-target="#c-2">(c)</a></li>
  <li><a href="#d-2" id="toc-d-2" class="nav-link" data-scroll-target="#d-2">(d)</a></li>
  </ul></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content page-columns page-full" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Assignment 1</h1>
  <div class="quarto-categories">
    <div class="quarto-category">Machine Learning &amp; Deep Learning for Data Science (2022 Fall)</div>
  </div>
  </div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Sangwon Ju, SNU GSPA </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">October 12, 2022</p>
    </div>
  </div>
    
  </div>
  

</header>

<p>Regression ~ Ridge, Lasso</p>
<h3 align="center" class="anchored">
Machine Learning &amp; Deep Learning for Data Science <br> Assignment 1
</h3>
<h5 align="right" class="anchored">
행정대학원 정책학전공 2021-29725 주상원
</h5>
<section id="준비" class="level1">
<h1>0. 준비</h1>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Loading Packages</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> os</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> IPython.display <span class="im">import</span> display, Math, Latex</span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> numpy <span class="im">as</span> np</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> pandas <span class="im">as</span> pd</span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> seaborn <span class="im">as</span> sns</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib.pyplot <span class="im">as</span> plt</span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> matplotlib <span class="im">as</span> mpl</span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> sklearn.linear_model <span class="im">as</span> skl_lm</span>
<span id="cb1-10"><a href="#cb1-10" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> scipy.stats <span class="im">import</span> pearsonr</span>
<span id="cb1-11"><a href="#cb1-11" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.metrics <span class="im">import</span> mean_squared_error, r2_score</span>
<span id="cb1-12"><a href="#cb1-12" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.datasets <span class="im">import</span> make_classification</span>
<span id="cb1-13"><a href="#cb1-13" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.model_selection <span class="im">import</span> train_test_split</span>
<span id="cb1-14"><a href="#cb1-14" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.model_selection <span class="im">import</span> KFold</span>
<span id="cb1-15"><a href="#cb1-15" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.model_selection <span class="im">import</span> cross_val_score</span>
<span id="cb1-16"><a href="#cb1-16" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.metrics <span class="im">import</span> mean_squared_error</span>
<span id="cb1-17"><a href="#cb1-17" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.metrics <span class="im">import</span> accuracy_score</span>
<span id="cb1-18"><a href="#cb1-18" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.metrics <span class="im">import</span> r2_score</span>
<span id="cb1-19"><a href="#cb1-19" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.linear_model <span class="im">import</span> LinearRegression</span>
<span id="cb1-20"><a href="#cb1-20" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.linear_model <span class="im">import</span> LogisticRegression</span>
<span id="cb1-21"><a href="#cb1-21" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.linear_model <span class="im">import</span> Ridge</span>
<span id="cb1-22"><a href="#cb1-22" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.linear_model <span class="im">import</span> RidgeCV</span>
<span id="cb1-23"><a href="#cb1-23" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.linear_model <span class="im">import</span> Lasso</span>
<span id="cb1-24"><a href="#cb1-24" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.linear_model <span class="im">import</span> LassoCV</span>
<span id="cb1-25"><a href="#cb1-25" aria-hidden="true" tabindex="-1"></a><span class="im">from</span> sklearn.preprocessing <span class="im">import</span> StandardScaler</span>
<span id="cb1-26"><a href="#cb1-26" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.api <span class="im">as</span> sm</span>
<span id="cb1-27"><a href="#cb1-27" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> statsmodels.formula.api <span class="im">as</span> smf</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Reference Repositiory: https://github.com/JWarmenhoven/ISLR-python</p>
</section>
<section id="question-1" class="level1">
<h1>1. Question 1</h1>
<p>[30 pts] In this problem, you will use the Carseats data set attached in the assignment (Carseats.csv) for linear regression.</p>
<section id="loading-dataset" class="level2">
<h2 class="anchored" data-anchor-id="loading-dataset">Loading Dataset</h2>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Set Work Directory</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Before Directory: </span><span class="sc">%s</span><span class="st">"</span><span class="op">%</span>os.getcwd())</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a>os.chdir(<span class="st">"E:/OneDrive - SNU/r"</span>)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"After Directory: </span><span class="sc">%s</span><span class="st">"</span><span class="op">%</span>os.getcwd())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Before Directory: e:\OneDrive - SNU\(B) 대학원\수업\2022 2학기\데이터사이언스를위한머신러닝과딥러닝\과제1
After Directory: E:\OneDrive - SNU\r</code></pre>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Read Dataset</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>carseats<span class="op">=</span>pd.read_csv(<span class="st">"Carseats.csv"</span>)</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>display(carseats.head(<span class="dv">5</span>))</span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Check if there is missing value</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Total missing variable: "</span>,carseats.isnull().<span class="bu">sum</span>().<span class="bu">sum</span>()) <span class="co"># no missing value</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>Sales</th>
      <th>CompPrice</th>
      <th>Income</th>
      <th>Advertising</th>
      <th>Population</th>
      <th>Price</th>
      <th>ShelveLoc</th>
      <th>Age</th>
      <th>Education</th>
      <th>Urban</th>
      <th>US</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>9.50</td>
      <td>138</td>
      <td>73</td>
      <td>11</td>
      <td>276</td>
      <td>120</td>
      <td>Bad</td>
      <td>42</td>
      <td>17</td>
      <td>Yes</td>
      <td>Yes</td>
    </tr>
    <tr>
      <th>1</th>
      <td>11.22</td>
      <td>111</td>
      <td>48</td>
      <td>16</td>
      <td>260</td>
      <td>83</td>
      <td>Good</td>
      <td>65</td>
      <td>10</td>
      <td>Yes</td>
      <td>Yes</td>
    </tr>
    <tr>
      <th>2</th>
      <td>10.06</td>
      <td>113</td>
      <td>35</td>
      <td>10</td>
      <td>269</td>
      <td>80</td>
      <td>Medium</td>
      <td>59</td>
      <td>12</td>
      <td>Yes</td>
      <td>Yes</td>
    </tr>
    <tr>
      <th>3</th>
      <td>7.40</td>
      <td>117</td>
      <td>100</td>
      <td>4</td>
      <td>466</td>
      <td>97</td>
      <td>Medium</td>
      <td>55</td>
      <td>14</td>
      <td>Yes</td>
      <td>Yes</td>
    </tr>
    <tr>
      <th>4</th>
      <td>4.15</td>
      <td>141</td>
      <td>64</td>
      <td>3</td>
      <td>340</td>
      <td>128</td>
      <td>Bad</td>
      <td>38</td>
      <td>13</td>
      <td>Yes</td>
      <td>No</td>
    </tr>
  </tbody>
</table>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Total missing variable:  0</code></pre>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Data types</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>carseats.info() </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>&lt;class 'pandas.core.frame.DataFrame'&gt;
RangeIndex: 400 entries, 0 to 399
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Sales        400 non-null    float64
 1   CompPrice    400 non-null    int64  
 2   Income       400 non-null    int64  
 3   Advertising  400 non-null    int64  
 4   Population   400 non-null    int64  
 5   Price        400 non-null    int64  
 6   ShelveLoc    400 non-null    object 
 7   Age          400 non-null    int64  
 8   Education    400 non-null    int64  
 9   Urban        400 non-null    object 
 10  US           400 non-null    object 
dtypes: float64(1), int64(7), object(3)
memory usage: 34.5+ KB</code></pre>
</div>
</div>
</section>
<section id="a" class="level2">
<h2 class="anchored" data-anchor-id="a">(a)</h2>
<p>[10 pts] Fit a multiple linear regression model to predict Sales using Price, Urban, and US. Report the R2 of the model.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Sales: float, Price: income, Urban and US: Categorical variable</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>carseats.US<span class="op">=</span>pd.Categorical(carseats.US, categories<span class="op">=</span>[<span class="st">"No"</span>, <span class="st">"Yes"</span>])</span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>carseats.Urban<span class="op">=</span>pd.Categorical(carseats.Urban, categories<span class="op">=</span>[<span class="st">"No"</span>, <span class="st">"Yes"</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb9-1"><a href="#cb9-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Fit a multiple linear regression model</span></span>
<span id="cb9-2"><a href="#cb9-2" aria-hidden="true" tabindex="-1"></a>estimate <span class="op">=</span> smf.ols(<span class="st">'Sales ~  Urban + US + Price'</span>, carseats).fit()</span>
<span id="cb9-3"><a href="#cb9-3" aria-hidden="true" tabindex="-1"></a>estimate.summary()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="6">

<table class="simpletable">
<caption>OLS Regression Results</caption>
<tbody><tr>
  <th>Dep. Variable:</th>          <td>Sales</td>      <th>  R-squared:         </th> <td>   0.239</td>
</tr>
<tr>
  <th>Model:</th>                   <td>OLS</td>       <th>  Adj. R-squared:    </th> <td>   0.234</td>
</tr>
<tr>
  <th>Method:</th>             <td>Least Squares</td>  <th>  F-statistic:       </th> <td>   41.52</td>
</tr>
<tr>
  <th>Date:</th>             <td>Sun, 09 Oct 2022</td> <th>  Prob (F-statistic):</th> <td>2.39e-23</td>
</tr>
<tr>
  <th>Time:</th>                 <td>09:07:43</td>     <th>  Log-Likelihood:    </th> <td> -927.66</td>
</tr>
<tr>
  <th>No. Observations:</th>      <td>   400</td>      <th>  AIC:               </th> <td>   1863.</td>
</tr>
<tr>
  <th>Df Residuals:</th>          <td>   396</td>      <th>  BIC:               </th> <td>   1879.</td>
</tr>
<tr>
  <th>Df Model:</th>              <td>     3</td>      <th>                     </th>     <td> </td>   
</tr>
<tr>
  <th>Covariance Type:</th>      <td>nonrobust</td>    <th>                     </th>     <td> </td>   
</tr>
</tbody></table>
<table class="simpletable">
<tbody><tr>
        <td></td>          <th>coef</th>     <th>std err</th>      <th>t</th>      <th>P&gt;|t|</th>  <th>[0.025</th>    <th>0.975]</th>  
</tr>
<tr>
  <th>Intercept</th>    <td>   13.0435</td> <td>    0.651</td> <td>   20.036</td> <td> 0.000</td> <td>   11.764</td> <td>   14.323</td>
</tr>
<tr>
  <th>Urban[T.Yes]</th> <td>   -0.0219</td> <td>    0.272</td> <td>   -0.081</td> <td> 0.936</td> <td>   -0.556</td> <td>    0.512</td>
</tr>
<tr>
  <th>US[T.Yes]</th>    <td>    1.2006</td> <td>    0.259</td> <td>    4.635</td> <td> 0.000</td> <td>    0.691</td> <td>    1.710</td>
</tr>
<tr>
  <th>Price</th>        <td>   -0.0545</td> <td>    0.005</td> <td>  -10.389</td> <td> 0.000</td> <td>   -0.065</td> <td>   -0.044</td>
</tr>
</tbody></table>
<table class="simpletable">
<tbody><tr>
  <th>Omnibus:</th>       <td> 0.676</td> <th>  Durbin-Watson:     </th> <td>   1.912</td>
</tr>
<tr>
  <th>Prob(Omnibus):</th> <td> 0.713</td> <th>  Jarque-Bera (JB):  </th> <td>   0.758</td>
</tr>
<tr>
  <th>Skew:</th>          <td> 0.093</td> <th>  Prob(JB):          </th> <td>   0.684</td>
</tr>
<tr>
  <th>Kurtosis:</th>      <td> 2.897</td> <th>  Cond. No.          </th> <td>    628.</td>
</tr>
</tbody></table><br><br>Notes:<br>[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Report R^2 of the model</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">'R^2: '</span>, <span class="bu">round</span>(estimate.rsquared,<span class="dv">3</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>R^2:  0.239</code></pre>
</div>
</div>
</section>
<section id="b" class="level2">
<h2 class="anchored" data-anchor-id="b">(b)</h2>
<p>[5 pts] Write out the model in equation form, being careful to handle the qualitative variables properly. Provide an interpretation of each coefficient in the model.</p>
<p><span class="math display">\[ Y= \beta_0 + \beta_1 X_1 + \beta_2 X_2 + \beta_3 X_3 + \epsilon \,, \epsilon \sim \,iid  \, N(0,\sigma^2)  \]</span> <span class="math display">\[ E(Y)= 13.0435 - 0.0219 X_1 + 1.2006 X_2 - 0.0545 X_3 \]</span></p>
<p>where</p>
<p><span class="math display">\[ Y = Sales \]</span></p>
<p><span class="math display">\[ \begin{equation*}
X_1 = \begin{cases}
             1  &amp; \text{if }\,Urban=Yes \\
             0  &amp; \text{if }\,Urban=No
       \end{cases}
\end{equation*}
\]</span></p>
<p><span class="math display">\[
\begin{equation*}
X_2 = \begin{cases}
             1  &amp; \text{if }\,US=Yes \\
             0  &amp; \text{if }\,US=No
       \end{cases}
\end{equation*}
\]</span></p>
<p><span class="math display">\[ X_3 = Price \]</span></p>
<ul>
<li>Interpreation of the coefficient</li>
</ul>
<ol type="1">
<li><span class="math inline">\(\beta_0\)</span> 13.0435: The overall average value of the Sales is 13.0435, if all other variables are equal to zero ( $ X_1,, X_2,, X_3 =0$ )</li>
<li><span class="math inline">\(\beta_1\)</span> -0.0219: The average Sales difference between Urban and Non Urban customers is estimated as -0.0219. (Even though the point estimates of the regression coefficient not equal to zero, the parameter estimate is not statistically significant under significance level of 0.05. Can’t reject null hypothesis of <span class="math inline">\(\beta_1=0\)</span>)</li>
<li><span class="math inline">\(\beta_2\)</span> 1.2006 : The average Sales difference between US and Non US customers is estimated as 1.2006.</li>
<li><span class="math inline">\(\beta_3\)</span> -0.0545 : Under <span class="math inline">\(X_1,\, X_2\)</span> (Urban and US dummy) are controlled, the one unit increase in Price results in -0.545 unit of Sales decrease.</li>
</ol>
</section>
<section id="c" class="level2">
<h2 class="anchored" data-anchor-id="c">(c)</h2>
<p>[5 pts] For which predictor variable j can you reject the null hypothesis H0 : <span class="math inline">\(β_j\)</span> = 0? for which there is evidence of association with the outcome.</p>
<ul>
<li><p>Under the significance level of 0.05, the parameter <span class="math inline">\(\beta_1\)</span> estimate for the variable <span class="math inline">\(X_1\)</span> (Urban or Non-Urban) is not statistically significant as p-value is over 0.05 (0.936) and t-statistic is under critical region.</p></li>
<li><p>Null: <span class="math inline">\(H_0\)</span>: <span class="math inline">\(\beta_1\)</span> = 0</p></li>
<li><p>Alternative: <span class="math inline">\(H_0\)</span>: <span class="math inline">\(\beta_1\)</span> <span class="math inline">\(\neq\)</span> 0</p></li>
</ul>
</section>
<section id="d" class="level2">
<h2 class="anchored" data-anchor-id="d">(d)</h2>
<p>[10 pts] Obtain 95% confidence intervals for the coefficient(s).</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb12"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a>estimate.conf_int(alpha<span class="op">=</span><span class="fl">0.05</span>, cols<span class="op">=</span><span class="va">None</span>).rename({<span class="dv">0</span>: <span class="st">'Lower CI'</span>, <span class="dv">1</span>: <span class="st">'Upper CI'</span>}, axis<span class="op">=</span><span class="st">'columns'</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="8">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>Lower CI</th>
      <th>Upper CI</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>Intercept</th>
      <td>11.763597</td>
      <td>14.323341</td>
    </tr>
    <tr>
      <th>Urban[T.Yes]</th>
      <td>-0.555973</td>
      <td>0.512141</td>
    </tr>
    <tr>
      <th>US[T.Yes]</th>
      <td>0.691304</td>
      <td>1.709841</td>
    </tr>
    <tr>
      <th>Price</th>
      <td>-0.064764</td>
      <td>-0.044154</td>
    </tr>
  </tbody>
</table>
</div>
</div>
</div>
</section>
</section>
<section id="question-2" class="level1">
<h1>2. Question 2</h1>
<p>In class, we used the example of the logistic regression model to predict the probability of default using income and balance on the Default data set attached in the assignment (Default.csv). In this problem, we will estimate the test error of this logistic regression model using the validation set approach. Do not forget to set a random seed before beginning your analysis.</p>
<section id="loading-dataset-1" class="level2">
<h2 class="anchored" data-anchor-id="loading-dataset-1">Loading Dataset</h2>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> random</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a>random.seed(<span class="dv">2022</span>)</span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-4"><a href="#cb13-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Read Dataset</span></span>
<span id="cb13-5"><a href="#cb13-5" aria-hidden="true" tabindex="-1"></a>default<span class="op">=</span>pd.read_csv(<span class="st">"Default.csv"</span>)</span>
<span id="cb13-6"><a href="#cb13-6" aria-hidden="true" tabindex="-1"></a>display(default.head(<span class="dv">5</span>))</span>
<span id="cb13-7"><a href="#cb13-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Check if there is missing value</span></span>
<span id="cb13-8"><a href="#cb13-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Total missing variable: "</span>, default.isnull().<span class="bu">sum</span>().<span class="bu">sum</span>()) <span class="co"># no missing value</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>default</th>
      <th>student</th>
      <th>balance</th>
      <th>income</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>No</td>
      <td>No</td>
      <td>729.526495</td>
      <td>44361.625074</td>
    </tr>
    <tr>
      <th>1</th>
      <td>No</td>
      <td>Yes</td>
      <td>817.180407</td>
      <td>12106.134700</td>
    </tr>
    <tr>
      <th>2</th>
      <td>No</td>
      <td>No</td>
      <td>1073.549164</td>
      <td>31767.138947</td>
    </tr>
    <tr>
      <th>3</th>
      <td>No</td>
      <td>No</td>
      <td>529.250605</td>
      <td>35704.493935</td>
    </tr>
    <tr>
      <th>4</th>
      <td>No</td>
      <td>No</td>
      <td>785.655883</td>
      <td>38463.495879</td>
    </tr>
  </tbody>
</table>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Total missing variable:  0</code></pre>
</div>
</div>
</section>
<section id="a-1" class="level2">
<h2 class="anchored" data-anchor-id="a-1">(a)</h2>
<p>[10 pts] Fit a logistic regression model that uses income and balance to predict default. Report the log-likelihood of the model.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a>default.info()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>&lt;class 'pandas.core.frame.DataFrame'&gt;
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   default  10000 non-null  object 
 1   student  10000 non-null  object 
 2   balance  10000 non-null  float64
 3   income   10000 non-null  float64
dtypes: float64(2), object(2)
memory usage: 312.6+ KB</code></pre>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a>display(default[<span class="st">'default'</span>].value_counts())</span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>display(default[<span class="st">'student'</span>].value_counts())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<pre><code>No     9667
Yes     333
Name: default, dtype: int64</code></pre>
</div>
<div class="cell-output cell-output-display">
<pre><code>No     7056
Yes    2944
Name: student, dtype: int64</code></pre>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb20"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Make dummy variable - No=0, Yes=1</span></span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>default.default<span class="op">=</span>pd.get_dummies(default.default, drop_first<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>default.student<span class="op">=</span>pd.get_dummies(default.student, drop_first<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>display(default[<span class="st">'default'</span>].value_counts())</span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>display(default[<span class="st">'student'</span>].value_counts())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<pre><code>0    9667
1     333
Name: default, dtype: int64</code></pre>
</div>
<div class="cell-output cell-output-display">
<pre><code>0    7056
1    2944
Name: student, dtype: int64</code></pre>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a>fig <span class="op">=</span> plt.figure(figsize<span class="op">=</span>(<span class="dv">10</span>,<span class="dv">5</span>))</span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>gs <span class="op">=</span> mpl.gridspec.GridSpec(<span class="dv">1</span>, <span class="dv">2</span>)</span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>ax1 <span class="op">=</span> plt.subplot(gs[<span class="dv">0</span>])</span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>ax2 <span class="op">=</span> plt.subplot(gs[<span class="dv">1</span>])</span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb23-6"><a href="#cb23-6" aria-hidden="true" tabindex="-1"></a>pal <span class="op">=</span> {<span class="dv">0</span> :<span class="st">'red'</span>, <span class="dv">1</span>:<span class="st">'blue'</span>}</span>
<span id="cb23-7"><a href="#cb23-7" aria-hidden="true" tabindex="-1"></a>sns.boxplot(x<span class="op">=</span><span class="st">'default'</span>, y<span class="op">=</span><span class="st">'balance'</span>, data<span class="op">=</span>default, orient<span class="op">=</span><span class="st">'vertical'</span>, ax<span class="op">=</span>ax1, palette<span class="op">=</span>pal)</span>
<span id="cb23-8"><a href="#cb23-8" aria-hidden="true" tabindex="-1"></a>sns.boxplot(x<span class="op">=</span><span class="st">'default'</span>, y<span class="op">=</span><span class="st">'income'</span>, data<span class="op">=</span>default, orient<span class="op">=</span><span class="st">'vertical'</span>, ax<span class="op">=</span>ax2, palette<span class="op">=</span>pal)</span>
<span id="cb23-9"><a href="#cb23-9" aria-hidden="true" tabindex="-1"></a>gs.tight_layout(plt.gcf())</span>
<span id="cb23-10"><a href="#cb23-10" aria-hidden="true" tabindex="-1"></a></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<p><img src="2021-29725_hw1-personal_files/figure-html/cell-14-output-1.png" class="img-fluid"></p>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a>estimate2 <span class="op">=</span> smf.logit(<span class="st">'default ~  income + balance'</span>, data<span class="op">=</span>default).fit()</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a>estimate2.summary()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Optimization terminated successfully.
         Current function value: 0.078948
         Iterations 10</code></pre>
</div>
<div class="cell-output cell-output-display" data-execution_count="14">

<table class="simpletable">
<caption>Logit Regression Results</caption>
<tbody><tr>
  <th>Dep. Variable:</th>        <td>default</td>     <th>  No. Observations:  </th>   <td> 10000</td>  
</tr>
<tr>
  <th>Model:</th>                 <td>Logit</td>      <th>  Df Residuals:      </th>   <td>  9997</td>  
</tr>
<tr>
  <th>Method:</th>                 <td>MLE</td>       <th>  Df Model:          </th>   <td>     2</td>  
</tr>
<tr>
  <th>Date:</th>            <td>Sun, 09 Oct 2022</td> <th>  Pseudo R-squ.:     </th>   <td>0.4594</td>  
</tr>
<tr>
  <th>Time:</th>                <td>09:07:44</td>     <th>  Log-Likelihood:    </th>  <td> -789.48</td> 
</tr>
<tr>
  <th>converged:</th>             <td>True</td>       <th>  LL-Null:           </th>  <td> -1460.3</td> 
</tr>
<tr>
  <th>Covariance Type:</th>     <td>nonrobust</td>    <th>  LLR p-value:       </th> <td>4.541e-292</td>
</tr>
</tbody></table>
<table class="simpletable">
<tbody><tr>
      <td></td>         <th>coef</th>     <th>std err</th>      <th>z</th>      <th>P&gt;|z|</th>  <th>[0.025</th>    <th>0.975]</th>  
</tr>
<tr>
  <th>Intercept</th> <td>  -11.5405</td> <td>    0.435</td> <td>  -26.544</td> <td> 0.000</td> <td>  -12.393</td> <td>  -10.688</td>
</tr>
<tr>
  <th>income</th>    <td> 2.081e-05</td> <td> 4.99e-06</td> <td>    4.174</td> <td> 0.000</td> <td>  1.1e-05</td> <td> 3.06e-05</td>
</tr>
<tr>
  <th>balance</th>   <td>    0.0056</td> <td>    0.000</td> <td>   24.835</td> <td> 0.000</td> <td>    0.005</td> <td>    0.006</td>
</tr>
</tbody></table><br><br>Possibly complete quasi-separation: A fraction 0.14 of observations can be<br>perfectly predicted. This might indicate that there is complete<br>quasi-separation. In this case some parameters will not be identified.
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb26-1"><a href="#cb26-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Log-likelihood of logit model: "</span>, <span class="bu">round</span>(estimate2.llf,<span class="dv">3</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Log-likelihood of logit model:  -789.483</code></pre>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb28-1"><a href="#cb28-1" aria-hidden="true" tabindex="-1"></a>estimate2.params</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="16">
<pre><code>Intercept   -11.540468
income        0.000021
balance       0.005647
dtype: float64</code></pre>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculate Odds</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>odds_ratio <span class="op">=</span> pd.DataFrame( {<span class="st">"Odds Ratio"</span>: estimate2.params,<span class="st">"Lower CI"</span>: estimate2.conf_int()[<span class="dv">0</span>],<span class="st">"Upper CI"</span>: estimate2.conf_int()[<span class="dv">1</span>]})</span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>odds_ratio <span class="op">=</span> np.exp(odds_ratio)</span>
<span id="cb30-4"><a href="#cb30-4" aria-hidden="true" tabindex="-1"></a>display (odds_ratio)</span>
<span id="cb30-5"><a href="#cb30-5" aria-hidden="true" tabindex="-1"></a>intercept<span class="op">=</span>odds_ratio.iloc[<span class="dv">0</span>,<span class="dv">0</span>]</span>
<span id="cb30-6"><a href="#cb30-6" aria-hidden="true" tabindex="-1"></a>P <span class="op">=</span> (intercept) <span class="op">/</span> (<span class="dv">1</span> <span class="op">+</span> intercept) </span>
<span id="cb30-7"><a href="#cb30-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"p_o: "</span>, <span class="bu">round</span>(P,<span class="dv">15</span>)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>Odds Ratio</th>
      <th>Lower CI</th>
      <th>Upper CI</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>Intercept</th>
      <td>0.000010</td>
      <td>0.000004</td>
      <td>0.000023</td>
    </tr>
    <tr>
      <th>income</th>
      <td>1.000021</td>
      <td>1.000011</td>
      <td>1.000031</td>
    </tr>
    <tr>
      <th>balance</th>
      <td>1.005663</td>
      <td>1.005215</td>
      <td>1.006111</td>
    </tr>
  </tbody>
</table>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>p_o:  9.728234005e-06</code></pre>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a>odds_ratio.iloc[<span class="dv">0</span>,<span class="dv">0</span>]</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display" data-execution_count="18">
<pre><code>9.728328644686842e-06</code></pre>
</div>
</div>
</section>
<section id="b-1" class="level2">
<h2 class="anchored" data-anchor-id="b-1">(b)</h2>
<p>[5 pts] Write out the model in equation form and provide an interpretation of each coefficient in the trained model.</p>
<p><span class="math display">\[ P(Y=1|X_1, X_2) = p = \frac{\exp(\beta_0 + \beta_1 X_1 + \beta_2 X_2 )}{1 + \exp (\beta_0 + \beta_1 X_1 + \beta_2 X_2 )}  \]</span> <span class="math display">\[ \ln(\frac{p}{1-p}) = \beta_0 + \beta_1 X_1 + \beta_2 X_2  = -11.5405 + 0.00002 X_1 + 0.0056 X_2  \]</span></p>
<p>where</p>
<p><span class="math display">\[
\begin{equation*}
Y = \begin{cases}
             1  &amp; \text{if }\,Default=Yes \\
             0  &amp; \text{if }\,Default=No \\
       \end{cases}
\end{equation*} \quad
\]</span> <span class="math display">\[
X_1 = Income,\,X_2 = Balance
\]</span></p>
<ul>
<li>Interpreation of the coefficient</li>
</ul>
<ol type="1">
<li><span class="math inline">\(\beta_0\)</span>= -11.5405 (odds ratio: 0.000010): The probability of having the outcome Default is 0.00000972823, if all other variables are equal to zero ($ X_1, , X_2 = 0 $)</li>
<li><span class="math inline">\(\beta_1\)</span>= 0.00002 (odds ratio: 1.000021): The one unit increase in Income, results in 1.000021 times increase in odds ratio of Default (increases odds of default by 0.0021%)</li>
<li><span class="math inline">\(\beta_2\)</span>= 0.0056 (odds ratio: 1.005663): The one unit increase in Balance, results in 1.005663 times increase in odds ratio of Default (increases odds of default by 0.5663%)</li>
</ol>
</section>
<section id="c-1" class="level2">
<h2 class="anchored" data-anchor-id="c-1">(c)</h2>
<p>[5 pts] Perform 5-fold cross-validation using the model in Part (a), and estimate the test error of this model.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>x <span class="op">=</span> np.array(default.loc[ : , [<span class="st">'income'</span>,<span class="st">'balance'</span>]]) <span class="co"># make array</span></span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a>y <span class="op">=</span> default.loc[:,<span class="st">'default'</span>]</span>
<span id="cb34-3"><a href="#cb34-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb34-4"><a href="#cb34-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Five-Fold cross-validation</span></span>
<span id="cb34-5"><a href="#cb34-5" aria-hidden="true" tabindex="-1"></a>k_fold<span class="op">=</span>KFold(n_splits <span class="op">=</span> <span class="dv">5</span>, shuffle <span class="op">=</span> <span class="va">True</span>, random_state<span class="op">=</span><span class="dv">2022</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Test error was calculated using Mean Squared Error <span class="math display">\[ \text {Test Error of 5 folds: } CV_5 = \sum_{k=1}^{5} \frac{n_k}{n} MSE_k \]</span></p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb35"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a>test_error <span class="op">=</span> []</span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> train_index, test_index <span class="kw">in</span> k_fold.split(x):</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>    x_train, x_test <span class="op">=</span> x[train_index], x[test_index]</span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>    y_train, y_test <span class="op">=</span> y[train_index], y[test_index]</span>
<span id="cb35-6"><a href="#cb35-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-7"><a href="#cb35-7" aria-hidden="true" tabindex="-1"></a>    model <span class="op">=</span> LogisticRegression() <span class="co"># Logistic Regression</span></span>
<span id="cb35-8"><a href="#cb35-8" aria-hidden="true" tabindex="-1"></a>    model.fit(x_train, y_train) <span class="co"># Model Training</span></span>
<span id="cb35-9"><a href="#cb35-9" aria-hidden="true" tabindex="-1"></a>    y_test_pred <span class="op">=</span> model.predict(x_test) </span>
<span id="cb35-10"><a href="#cb35-10" aria-hidden="true" tabindex="-1"></a>    test_error.append(<span class="dv">1</span><span class="op">-</span>accuracy_score(y_test_pred, y_test)) <span class="co"># Test Error of each five folds</span></span>
<span id="cb35-11"><a href="#cb35-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb35-12"><a href="#cb35-12" aria-hidden="true" tabindex="-1"></a><span class="co"># Estimating Test Error</span></span>
<span id="cb35-13"><a href="#cb35-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"The test error of each five folds: "</span>, np.<span class="bu">round</span>(test_error,<span class="dv">3</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>The test error of each five folds:  [0.031 0.025 0.026 0.029 0.031]</code></pre>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb37"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> LogisticRegression() <span class="co"># Logistic Regression</span></span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a>test_error<span class="op">=</span>cross_val_score(model, x, y, cv<span class="op">=</span>k_fold, scoring<span class="op">=</span><span class="st">'neg_mean_squared_error'</span>, n_jobs<span class="op">=-</span><span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a>size<span class="op">=</span>[]</span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> train_index, test_index <span class="kw">in</span> k_fold.split(x):</span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>    size.append(np.size(test_index))</span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"The observations per each split: "</span>, size)</span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb38-6"><a href="#cb38-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Using formula</span></span>
<span id="cb38-7"><a href="#cb38-7" aria-hidden="true" tabindex="-1"></a>testerror<span class="op">=</span>[]</span>
<span id="cb38-8"><a href="#cb38-8" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> folds <span class="kw">in</span> np.arange(<span class="dv">0</span>,<span class="dv">5</span>):</span>
<span id="cb38-9"><a href="#cb38-9" aria-hidden="true" tabindex="-1"></a>    testerror.append(np.negative(test_error)[folds]<span class="op">*</span>size[folds])</span>
<span id="cb38-10"><a href="#cb38-10" aria-hidden="true" tabindex="-1"></a>testerrorvalue<span class="op">=</span><span class="bu">round</span>(<span class="bu">sum</span>(testerror)<span class="op">/</span><span class="bu">len</span>(default),<span class="dv">4</span>)</span>
<span id="cb38-11"><a href="#cb38-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Test error of cross validation"</span>, testerrorvalue)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>The observations per each split:  [2000, 2000, 2000, 2000, 2000]
Test error of cross validation 0.0286</code></pre>
</div>
</div>
</section>
<section id="d-1" class="level2">
<h2 class="anchored" data-anchor-id="d-1">(d)</h2>
<p>[10 pts] Now consider a logistic regression model that predicts the probability of default using income, balance, and a dummy variable for student. Estimate the test error for this model using the 5-fold cross-validation set approach. Comment on whether or not including a dummy variable for student would lead to a reduction in the test error rate.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb40"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb40-1"><a href="#cb40-1" aria-hidden="true" tabindex="-1"></a>x1 <span class="op">=</span> default.loc[ : , [<span class="st">'income'</span>,<span class="st">'balance'</span>,<span class="st">'student'</span>]] <span class="co"># make array</span></span>
<span id="cb40-2"><a href="#cb40-2" aria-hidden="true" tabindex="-1"></a>y1 <span class="op">=</span> default.loc[:,<span class="st">'default'</span>]</span>
<span id="cb40-3"><a href="#cb40-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb40-4"><a href="#cb40-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Five-Fold cross-validation</span></span>
<span id="cb40-5"><a href="#cb40-5" aria-hidden="true" tabindex="-1"></a>k_fold<span class="op">=</span>KFold(n_splits <span class="op">=</span> <span class="dv">5</span>, shuffle <span class="op">=</span> <span class="va">True</span>,random_state<span class="op">=</span><span class="dv">2022</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a>model <span class="op">=</span> LogisticRegression() <span class="co"># Logistic Regression</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>test_error_withstu<span class="op">=</span>cross_val_score(model, x1, y1, cv<span class="op">=</span>k_fold, scoring<span class="op">=</span><span class="st">'neg_mean_squared_error'</span>, n_jobs<span class="op">=-</span><span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb42"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>size<span class="op">=</span>[]</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> train_index, test_index <span class="kw">in</span> k_fold.split(x):</span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>    size.append(np.size(test_index))</span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"The observations per each split: "</span>, size)</span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a><span class="co"># Using formula</span></span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a>testerror<span class="op">=</span>[]</span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a><span class="cf">for</span> folds <span class="kw">in</span> np.arange(<span class="dv">0</span>,<span class="dv">5</span>):</span>
<span id="cb42-9"><a href="#cb42-9" aria-hidden="true" tabindex="-1"></a>    testerror.append(np.negative(test_error_withstu)[folds]<span class="op">*</span>size[folds])</span>
<span id="cb42-10"><a href="#cb42-10" aria-hidden="true" tabindex="-1"></a>testerrorvalue_withstudents<span class="op">=</span><span class="bu">round</span>(<span class="bu">sum</span>(testerror)<span class="op">/</span><span class="bu">len</span>(default),<span class="dv">4</span>)</span>
<span id="cb42-11"><a href="#cb42-11" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Test error of cross validation with students"</span>, testerrorvalue_withstudents)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>The observations per each split:  [2000, 2000, 2000, 2000, 2000]
Test error of cross validation with students 0.0317</code></pre>
</div>
</div>
<p>Including a dummy variable for student would lead to almost no change in the test error rate. - Firstly, the strong negative linear correlation between student and income is statistically significant. Since the two variables are linearly correlatedm, even if the varaible student is inserted to the model it would lead to minor improvement in model prediction. (most of the areas that variable student can explain is also can be explained by variable income) - Secondly, the model’s predictive ability would be negatively affected by statistically learning from train-dataset. Being a student and whether client would be default is correlated and it is statistically significant. As we use generalized linear model there is high possibility that “multicollinearity” would make parameter estimate unstable.</p>
<ul>
<li>As expected, the test error value with student variable is little(0.0001) higher than without student varaible.</li>
</ul>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb44"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb44-1"><a href="#cb44-1" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Test error of cross validation"</span>, testerrorvalue)</span>
<span id="cb44-2"><a href="#cb44-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Test error of cross validation with students"</span>, testerrorvalue_withstudents)</span>
<span id="cb44-3"><a href="#cb44-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-4"><a href="#cb44-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Correlation </span></span>
<span id="cb44-5"><a href="#cb44-5" aria-hidden="true" tabindex="-1"></a>rho <span class="op">=</span> default.corr()</span>
<span id="cb44-6"><a href="#cb44-6" aria-hidden="true" tabindex="-1"></a>pval <span class="op">=</span> default.corr(method<span class="op">=</span><span class="kw">lambda</span> x, y: pearsonr(x, y)[<span class="dv">1</span>]) <span class="op">-</span> np.eye(<span class="op">*</span>rho.shape)</span>
<span id="cb44-7"><a href="#cb44-7" aria-hidden="true" tabindex="-1"></a>p <span class="op">=</span> pval.applymap(<span class="kw">lambda</span> x: <span class="st">''</span>.join([<span class="st">'*'</span> <span class="cf">for</span> t <span class="kw">in</span> [<span class="fl">0.01</span>,<span class="fl">0.05</span>,<span class="fl">0.1</span>] <span class="cf">if</span> x<span class="op">&lt;=</span>t]))</span>
<span id="cb44-8"><a href="#cb44-8" aria-hidden="true" tabindex="-1"></a>display(rho.<span class="bu">round</span>(<span class="dv">2</span>).astype(<span class="bu">str</span>) <span class="op">+</span> p) </span>
<span id="cb44-9"><a href="#cb44-9" aria-hidden="true" tabindex="-1"></a><span class="co"># significant negative linear relationship between student and income (rho=-0.75)</span></span>
<span id="cb44-10"><a href="#cb44-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb44-11"><a href="#cb44-11" aria-hidden="true" tabindex="-1"></a><span class="co"># Model including student variable</span></span>
<span id="cb44-12"><a href="#cb44-12" aria-hidden="true" tabindex="-1"></a>estimate3 <span class="op">=</span> smf.logit(<span class="st">'default ~  income + balance + student'</span>, data<span class="op">=</span>default).fit()</span>
<span id="cb44-13"><a href="#cb44-13" aria-hidden="true" tabindex="-1"></a>display(estimate3.summary2().tables[<span class="dv">1</span>])</span>
<span id="cb44-14"><a href="#cb44-14" aria-hidden="true" tabindex="-1"></a></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Test error of cross validation 0.0286
Test error of cross validation with students 0.0317</code></pre>
</div>
<div class="cell-output cell-output-display">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>default</th>
      <th>student</th>
      <th>balance</th>
      <th>income</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>default</th>
      <td>1.0***</td>
      <td>0.04***</td>
      <td>0.35***</td>
      <td>-0.02**</td>
    </tr>
    <tr>
      <th>student</th>
      <td>0.04***</td>
      <td>1.0***</td>
      <td>0.2***</td>
      <td>-0.75***</td>
    </tr>
    <tr>
      <th>balance</th>
      <td>0.35***</td>
      <td>0.2***</td>
      <td>1.0***</td>
      <td>-0.15***</td>
    </tr>
    <tr>
      <th>income</th>
      <td>-0.02**</td>
      <td>-0.75***</td>
      <td>-0.15***</td>
      <td>1.0***</td>
    </tr>
  </tbody>
</table>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Optimization terminated successfully.
         Current function value: 0.078577
         Iterations 10</code></pre>
</div>
<div class="cell-output cell-output-display">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>Coef.</th>
      <th>Std.Err.</th>
      <th>z</th>
      <th>P&gt;|z|</th>
      <th>[0.025</th>
      <th>0.975]</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>Intercept</th>
      <td>-10.869045</td>
      <td>0.492273</td>
      <td>-22.079320</td>
      <td>4.995499e-108</td>
      <td>-11.833882</td>
      <td>-9.904209</td>
    </tr>
    <tr>
      <th>income</th>
      <td>0.000003</td>
      <td>0.000008</td>
      <td>0.369808</td>
      <td>7.115254e-01</td>
      <td>-0.000013</td>
      <td>0.000019</td>
    </tr>
    <tr>
      <th>balance</th>
      <td>0.005737</td>
      <td>0.000232</td>
      <td>24.736506</td>
      <td>4.331521e-135</td>
      <td>0.005282</td>
      <td>0.006191</td>
    </tr>
    <tr>
      <th>student</th>
      <td>-0.646776</td>
      <td>0.236257</td>
      <td>-2.737595</td>
      <td>6.189022e-03</td>
      <td>-1.109831</td>
      <td>-0.183721</td>
    </tr>
  </tbody>
</table>
</div>
</div>
</div>
<p>correlation 출처: https://stackoverflow.com/questions/25571882/pandas-columns-correlation-with-statistical-significance</p>
</section>
</section>
<section id="question-3" class="level1 page-columns page-full">
<h1>3. Question 3</h1>
<p>[40 pts] In this problem, you will predict the number of applications received using the other variables in the College data set attached in the assignment (College.csv).</p>
<section id="loading-dataset-2" class="level2 page-columns page-full">
<h2 class="anchored" data-anchor-id="loading-dataset-2">Loading Dataset</h2>
<div class="cell page-columns page-full">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb47"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="im">import</span> random</span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a>random.seed(<span class="dv">2022</span>)</span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Read Dataset</span></span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>college<span class="op">=</span>pd.read_csv(<span class="st">"College.csv"</span>)</span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a>display(college.head(<span class="dv">5</span>))</span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Check if there is missing value</span></span>
<span id="cb47-8"><a href="#cb47-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Total missing variable: "</span>, college.isnull().<span class="bu">sum</span>().<span class="bu">sum</span>()) <span class="co"># no missing value</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display column-screen-inset-shaded">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>Unnamed: 0</th>
      <th>Private</th>
      <th>Apps</th>
      <th>Accept</th>
      <th>Enroll</th>
      <th>Top10perc</th>
      <th>Top25perc</th>
      <th>F.Undergrad</th>
      <th>P.Undergrad</th>
      <th>Outstate</th>
      <th>Room.Board</th>
      <th>Books</th>
      <th>Personal</th>
      <th>PhD</th>
      <th>Terminal</th>
      <th>S.F.Ratio</th>
      <th>perc.alumni</th>
      <th>Expend</th>
      <th>Grad.Rate</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>Abilene Christian University</td>
      <td>Yes</td>
      <td>1660</td>
      <td>1232</td>
      <td>721</td>
      <td>23</td>
      <td>52</td>
      <td>2885</td>
      <td>537</td>
      <td>7440</td>
      <td>3300</td>
      <td>450</td>
      <td>2200</td>
      <td>70</td>
      <td>78</td>
      <td>18.1</td>
      <td>12</td>
      <td>7041</td>
      <td>60</td>
    </tr>
    <tr>
      <th>1</th>
      <td>Adelphi University</td>
      <td>Yes</td>
      <td>2186</td>
      <td>1924</td>
      <td>512</td>
      <td>16</td>
      <td>29</td>
      <td>2683</td>
      <td>1227</td>
      <td>12280</td>
      <td>6450</td>
      <td>750</td>
      <td>1500</td>
      <td>29</td>
      <td>30</td>
      <td>12.2</td>
      <td>16</td>
      <td>10527</td>
      <td>56</td>
    </tr>
    <tr>
      <th>2</th>
      <td>Adrian College</td>
      <td>Yes</td>
      <td>1428</td>
      <td>1097</td>
      <td>336</td>
      <td>22</td>
      <td>50</td>
      <td>1036</td>
      <td>99</td>
      <td>11250</td>
      <td>3750</td>
      <td>400</td>
      <td>1165</td>
      <td>53</td>
      <td>66</td>
      <td>12.9</td>
      <td>30</td>
      <td>8735</td>
      <td>54</td>
    </tr>
    <tr>
      <th>3</th>
      <td>Agnes Scott College</td>
      <td>Yes</td>
      <td>417</td>
      <td>349</td>
      <td>137</td>
      <td>60</td>
      <td>89</td>
      <td>510</td>
      <td>63</td>
      <td>12960</td>
      <td>5450</td>
      <td>450</td>
      <td>875</td>
      <td>92</td>
      <td>97</td>
      <td>7.7</td>
      <td>37</td>
      <td>19016</td>
      <td>59</td>
    </tr>
    <tr>
      <th>4</th>
      <td>Alaska Pacific University</td>
      <td>Yes</td>
      <td>193</td>
      <td>146</td>
      <td>55</td>
      <td>16</td>
      <td>44</td>
      <td>249</td>
      <td>869</td>
      <td>7560</td>
      <td>4120</td>
      <td>800</td>
      <td>1500</td>
      <td>76</td>
      <td>72</td>
      <td>11.9</td>
      <td>2</td>
      <td>10922</td>
      <td>15</td>
    </tr>
  </tbody>
</table>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Total missing variable:  0</code></pre>
</div>
</div>
<p>Randomly split the data set into a training set and a test set by 90:10 ratio. <br> Data description: https://www.kaggle.com/faressayah/college-data</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb49"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb49-1"><a href="#cb49-1" aria-hidden="true" tabindex="-1"></a>college.info()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>&lt;class 'pandas.core.frame.DataFrame'&gt;
RangeIndex: 777 entries, 0 to 776
Data columns (total 19 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Unnamed: 0   777 non-null    object 
 1   Private      777 non-null    object 
 2   Apps         777 non-null    int64  
 3   Accept       777 non-null    int64  
 4   Enroll       777 non-null    int64  
 5   Top10perc    777 non-null    int64  
 6   Top25perc    777 non-null    int64  
 7   F.Undergrad  777 non-null    int64  
 8   P.Undergrad  777 non-null    int64  
 9   Outstate     777 non-null    int64  
 10  Room.Board   777 non-null    int64  
 11  Books        777 non-null    int64  
 12  Personal     777 non-null    int64  
 13  PhD          777 non-null    int64  
 14  Terminal     777 non-null    int64  
 15  S.F.Ratio    777 non-null    float64
 16  perc.alumni  777 non-null    int64  
 17  Expend       777 non-null    int64  
 18  Grad.Rate    777 non-null    int64  
dtypes: float64(1), int64(16), object(2)
memory usage: 115.5+ KB</code></pre>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Make dummy variable - No=0, Yes=1</span></span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a><span class="co"># Priavate: A factor with levels Yes and No indicating private or public university</span></span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a>college.Private<span class="op">=</span>pd.get_dummies(college.Private, drop_first<span class="op">=</span><span class="va">True</span>)</span>
<span id="cb51-4"><a href="#cb51-4" aria-hidden="true" tabindex="-1"></a>display(college[<span class="st">'Private'</span>].value_counts())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">
<pre><code>1    565
0    212
Name: Private, dtype: int64</code></pre>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Accept: Number of applications accepted</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>y<span class="op">=</span>college.iloc[:,<span class="dv">3</span>]</span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Sclaing - Standardization of Predictors</span></span>
<span id="cb53-5"><a href="#cb53-5" aria-hidden="true" tabindex="-1"></a>scaler <span class="op">=</span> StandardScaler()  </span>
<span id="cb53-6"><a href="#cb53-6" aria-hidden="true" tabindex="-1"></a>train_col<span class="op">=</span>np.array(college.columns)</span>
<span id="cb53-7"><a href="#cb53-7" aria-hidden="true" tabindex="-1"></a>x1 <span class="op">=</span> college[np.delete(train_col,[<span class="dv">0</span>,<span class="dv">3</span>]).tolist()]</span>
<span id="cb53-8"><a href="#cb53-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-9"><a href="#cb53-9" aria-hidden="true" tabindex="-1"></a>x<span class="op">=</span>pd.DataFrame(scaler.fit_transform(x1[x1.columns[<span class="bu">range</span>(<span class="dv">1</span>,x1.shape[<span class="dv">1</span>])]].to_numpy()))</span>
<span id="cb53-10"><a href="#cb53-10" aria-hidden="true" tabindex="-1"></a>x.columns<span class="op">=</span>x1.columns[<span class="bu">range</span>(<span class="dv">1</span>,x1.shape[<span class="dv">1</span>])]</span>
<span id="cb53-11"><a href="#cb53-11" aria-hidden="true" tabindex="-1"></a>x.insert(loc<span class="op">=</span><span class="dv">0</span>,column<span class="op">=</span><span class="st">"Private"</span>, value<span class="op">=</span>x1[<span class="st">"Private"</span>])</span>
<span id="cb53-12"><a href="#cb53-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb53-13"><a href="#cb53-13" aria-hidden="true" tabindex="-1"></a><span class="co"># train test split</span></span>
<span id="cb53-14"><a href="#cb53-14" aria-hidden="true" tabindex="-1"></a>x_train, x_test, y_train, y_test <span class="op">=</span> train_test_split(x, y, test_size<span class="op">=</span><span class="fl">0.1</span>, shuffle<span class="op">=</span><span class="va">True</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<p>Ridge: <span class="math display">\[ \sum_{i=1}^{n} (y_i-\beta_0-\sum_{j=1}^p \beta_j x_{ij})^2 + \lambda \sum_{j=1}^p \beta_j^2 = RSS + \lambda \sum_{j=1}^p \beta_j^2 \]</span></p>
<p>Lasso: <span class="math display">\[ \sum_{i=1}^{n} (y_i-\beta_0-\sum_{j=1}^p \beta_j x_{ij})^2 + \lambda \sum_{j=1}^p |\beta_j| = RSS + \lambda \sum_{j=1}^p |\beta_j| \]</span></p>
<p>In this sense, <span class="math inline">\(\hat{\beta^R_{i,j}}\)</span> will depend not only on the value of <span class="math inline">\(\lambda\)</span>, but also on the scaling of the jth predictor (and other predictors). (RSS + <span class="math inline">\(\beta\)</span>) <br> Therefore, it is best to apply ridge regression after <span class="math inline">\(standardizing\,the\,predictors\)</span> using the formula <span class="math display">\[\tilde{x_{ij}}=\frac{x_ij}{\sqrt{\frac{1}{n} \sum_{i=1}^n(\bar{x_{ij}}-\bar{x_j})^2}}\]</span> (ISLR, p.&nbsp;239)</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb54"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb54-1"><a href="#cb54-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Dataframe Dimensions</span></span>
<span id="cb54-2"><a href="#cb54-2" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"# of rows: "</span>, college.shape[<span class="dv">0</span>])</span>
<span id="cb54-3"><a href="#cb54-3" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"# of train rows: "</span>, x_train.shape[<span class="dv">0</span>])</span>
<span id="cb54-4"><a href="#cb54-4" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"# of test rows: "</span>, x_test.shape[<span class="dv">0</span>])</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code># of rows:  777
# of train rows:  699
# of test rows:  78</code></pre>
</div>
</div>
</section>
<section id="a-2" class="level2">
<h2 class="anchored" data-anchor-id="a-2">(a)</h2>
<p>[10 pts] Fit a linear model using least squares on the training set, and report the test error obtained.</p>
<p>The test error was calculated using Mean Squared Error <span class="math display">\[ MSE_{train} = \frac{1}{699} \sum_{i=1}^{699} (\hat{Y_i} - Y_i)^2\]</span> <span class="math display">\[ MSE_{test} = \frac{1}{78} \sum_{i=1}^{78} (\hat{Y_i} - Y_i)^2\]</span></p>
<p>Linear Regression: scale equivariant - multiplying <span class="math inline">\(X_j\)</span> by a constant <span class="math inline">\(c\)</span> simply leads to a scale equivariant scaling of the least squares coefficient estimates by a factor of <span class="math inline">\(\frac{1}{c}\)</span>. In other words, regardless of how the <span class="math inline">\(j_th\)</span> predictor is scaled, <span class="math inline">\(X_{j}\beta_j\)</span> will remain the same (ISLR, p.&nbsp;239). Therefore, this assignment going to use standardized predictors for the model (for convenience).</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb56"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb56-1"><a href="#cb56-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Model </span></span>
<span id="cb56-2"><a href="#cb56-2" aria-hidden="true" tabindex="-1"></a>regr<span class="op">=</span>LinearRegression()</span>
<span id="cb56-3"><a href="#cb56-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-4"><a href="#cb56-4" aria-hidden="true" tabindex="-1"></a>model_ols<span class="op">=</span> regr.fit(x_train,y_train)</span>
<span id="cb56-5"><a href="#cb56-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-6"><a href="#cb56-6" aria-hidden="true" tabindex="-1"></a>y_train_pred<span class="op">=</span>model_ols.predict(x_train)</span>
<span id="cb56-7"><a href="#cb56-7" aria-hidden="true" tabindex="-1"></a>y_test_pred<span class="op">=</span>model_ols.predict(x_test)</span>
<span id="cb56-8"><a href="#cb56-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-9"><a href="#cb56-9" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Training R squared: "</span>, <span class="bu">round</span>(regr.score(x_train,y_train),<span class="dv">3</span>))</span>
<span id="cb56-10"><a href="#cb56-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Test R squared: "</span>, <span class="bu">round</span>(regr.score(x_test,y_test),<span class="dv">3</span>))</span>
<span id="cb56-11"><a href="#cb56-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb56-12"><a href="#cb56-12" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Training Error: "</span>, <span class="bu">round</span>(np.mean((y_train_pred<span class="op">-</span>y_train)<span class="op">**</span><span class="dv">2</span>),<span class="dv">3</span>))</span>
<span id="cb56-13"><a href="#cb56-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Test Error: "</span>, <span class="bu">round</span>(np.mean((y_test_pred<span class="op">-</span>y_test)<span class="op">**</span><span class="dv">2</span>),<span class="dv">3</span>))</span>
<span id="cb56-14"><a href="#cb56-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Test Error: "</span>, <span class="bu">round</span>(mean_squared_error(y_test_pred,y_test),<span class="dv">3</span>)) <span class="co"># alternate way </span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Training R squared:  0.952
Test R squared:  0.963
Training Error:  291415.502
Test Error:  192960.565
Test Error:  192960.565</code></pre>
</div>
</div>
</section>
<section id="b-2" class="level2">
<h2 class="anchored" data-anchor-id="b-2">(b)</h2>
<p>[10 pts] Fit a ridge regression model on the training set, with λ chosen by 10-fold cross-validation. Report the test error obtained.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb58"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb58-1"><a href="#cb58-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ridge regression with default λ=1.0</span></span>
<span id="cb58-2"><a href="#cb58-2" aria-hidden="true" tabindex="-1"></a>ridreg <span class="op">=</span> Ridge()</span>
<span id="cb58-3"><a href="#cb58-3" aria-hidden="true" tabindex="-1"></a>model_ridge<span class="op">=</span>ridreg.fit(x_train, y_train)</span>
<span id="cb58-4"><a href="#cb58-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb58-5"><a href="#cb58-5" aria-hidden="true" tabindex="-1"></a>y_train_pred<span class="op">=</span>model_ridge.predict(x_train)</span>
<span id="cb58-6"><a href="#cb58-6" aria-hidden="true" tabindex="-1"></a>y_test_pred<span class="op">=</span>model_ridge.predict(x_test)</span>
<span id="cb58-7"><a href="#cb58-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Training Error: "</span>, <span class="bu">round</span>(mean_squared_error(y_train_pred,y_train),<span class="dv">3</span>))  </span>
<span id="cb58-8"><a href="#cb58-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Test Error: "</span>, <span class="bu">round</span>(mean_squared_error(y_test_pred,y_test),<span class="dv">3</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Training Error:  291472.521
Test Error:  191707.194</code></pre>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ridge regression with 10-fold cross validation</span></span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>k_fold<span class="op">=</span>KFold(n_splits <span class="op">=</span> <span class="dv">10</span>, shuffle <span class="op">=</span> <span class="va">True</span>, random_state<span class="op">=</span><span class="dv">2022</span>) <span class="co"># set random seed</span></span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a><span class="co"># lambdas = np.arange(1,100, 1)</span></span>
<span id="cb60-5"><a href="#cb60-5" aria-hidden="true" tabindex="-1"></a><span class="co"># lambdas = np.arange(1,20, 0.5) </span></span>
<span id="cb60-6"><a href="#cb60-6" aria-hidden="true" tabindex="-1"></a>lambdas <span class="op">=</span> np.arange(<span class="dv">2</span>,<span class="dv">10</span>, <span class="fl">0.1</span>)   </span>
<span id="cb60-7"><a href="#cb60-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-8"><a href="#cb60-8" aria-hidden="true" tabindex="-1"></a><span class="co"># ridge</span></span>
<span id="cb60-9"><a href="#cb60-9" aria-hidden="true" tabindex="-1"></a>ridreg_cv <span class="op">=</span> RidgeCV(alphas<span class="op">=</span>lambdas, cv<span class="op">=</span>k_fold) </span>
<span id="cb60-10"><a href="#cb60-10" aria-hidden="true" tabindex="-1"></a>model_ridge_cv<span class="op">=</span>ridreg_cv.fit(x_train, y_train)</span>
<span id="cb60-11"><a href="#cb60-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-12"><a href="#cb60-12" aria-hidden="true" tabindex="-1"></a>y_train_pred<span class="op">=</span>model_ridge_cv.predict(x_train)</span>
<span id="cb60-13"><a href="#cb60-13" aria-hidden="true" tabindex="-1"></a>y_test_pred<span class="op">=</span>model_ridge_cv.predict(x_test)</span>
<span id="cb60-14"><a href="#cb60-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-15"><a href="#cb60-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Training Error (with 10 folds): "</span>, <span class="bu">round</span>(mean_squared_error(y_train_pred,y_train),<span class="dv">3</span>))  </span>
<span id="cb60-16"><a href="#cb60-16" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Test Error (with 10 folds): "</span>, <span class="bu">round</span>(mean_squared_error(y_test_pred,y_test),<span class="dv">3</span>))</span>
<span id="cb60-17"><a href="#cb60-17" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb60-18"><a href="#cb60-18" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Training R Squared: "</span>, <span class="bu">round</span>(r2_score(y_train, y_train_pred),<span class="dv">2</span>))</span>
<span id="cb60-19"><a href="#cb60-19" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Testing R Squared: "</span>, <span class="bu">round</span>(r2_score(y_test, y_test_pred),<span class="dv">2</span>))</span>
<span id="cb60-20"><a href="#cb60-20" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Optimal Lambda: "</span>, model_ridge_cv.alpha_)</span>
<span id="cb60-21"><a href="#cb60-21" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Coefficients: "</span>, model_ridge_cv.coef_)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Training Error (with 10 folds):  293156.156
Test Error (with 10 folds):  186375.172
Training R Squared:  0.95
Testing R Squared:  0.96
Optimal Lambda:  6.400000000000004
Coefficients:  [ 154.40316381 1606.59850184  942.98496287 -488.95762002  187.39331727
   63.85717783  -67.20841469  260.99875502  -16.86522954    4.24805295
  -32.17722811   75.26537243   12.02353776  -22.46635632  -83.30446315
 -161.72446977  -18.19291394]</code></pre>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb62"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb62-1"><a href="#cb62-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Coefficients with λ=6.41</span></span>
<span id="cb62-2"><a href="#cb62-2" aria-hidden="true" tabindex="-1"></a>display(pd.DataFrame({<span class="st">"Variable"</span>:x_train.columns,<span class="st">"Coefficients"</span>:model_ridge_cv.coef_}))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>Variable</th>
      <th>Coefficients</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>Private</td>
      <td>154.403164</td>
    </tr>
    <tr>
      <th>1</th>
      <td>Apps</td>
      <td>1606.598502</td>
    </tr>
    <tr>
      <th>2</th>
      <td>Enroll</td>
      <td>942.984963</td>
    </tr>
    <tr>
      <th>3</th>
      <td>Top10perc</td>
      <td>-488.957620</td>
    </tr>
    <tr>
      <th>4</th>
      <td>Top25perc</td>
      <td>187.393317</td>
    </tr>
    <tr>
      <th>5</th>
      <td>F.Undergrad</td>
      <td>63.857178</td>
    </tr>
    <tr>
      <th>6</th>
      <td>P.Undergrad</td>
      <td>-67.208415</td>
    </tr>
    <tr>
      <th>7</th>
      <td>Outstate</td>
      <td>260.998755</td>
    </tr>
    <tr>
      <th>8</th>
      <td>Room.Board</td>
      <td>-16.865230</td>
    </tr>
    <tr>
      <th>9</th>
      <td>Books</td>
      <td>4.248053</td>
    </tr>
    <tr>
      <th>10</th>
      <td>Personal</td>
      <td>-32.177228</td>
    </tr>
    <tr>
      <th>11</th>
      <td>PhD</td>
      <td>75.265372</td>
    </tr>
    <tr>
      <th>12</th>
      <td>Terminal</td>
      <td>12.023538</td>
    </tr>
    <tr>
      <th>13</th>
      <td>S.F.Ratio</td>
      <td>-22.466356</td>
    </tr>
    <tr>
      <th>14</th>
      <td>perc.alumni</td>
      <td>-83.304463</td>
    </tr>
    <tr>
      <th>15</th>
      <td>Expend</td>
      <td>-161.724470</td>
    </tr>
    <tr>
      <th>16</th>
      <td>Grad.Rate</td>
      <td>-18.192914</td>
    </tr>
  </tbody>
</table>
</div>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb63"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb63-1"><a href="#cb63-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ridge regression with optimal λ=6.41</span></span>
<span id="cb63-2"><a href="#cb63-2" aria-hidden="true" tabindex="-1"></a>ridreg <span class="op">=</span> Ridge(alpha<span class="op">=</span><span class="fl">6.41</span>)</span>
<span id="cb63-3"><a href="#cb63-3" aria-hidden="true" tabindex="-1"></a>model_ridge<span class="op">=</span>ridreg.fit(x_train, y_train)</span>
<span id="cb63-4"><a href="#cb63-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb63-5"><a href="#cb63-5" aria-hidden="true" tabindex="-1"></a>y_train_pred<span class="op">=</span>model_ridge.predict(x_train)</span>
<span id="cb63-6"><a href="#cb63-6" aria-hidden="true" tabindex="-1"></a>y_test_pred<span class="op">=</span>model_ridge.predict(x_test)</span>
<span id="cb63-7"><a href="#cb63-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Training Error: "</span>, <span class="bu">round</span>(mean_squared_error(y_train_pred,y_train),<span class="dv">3</span>))  </span>
<span id="cb63-8"><a href="#cb63-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Test Error: "</span>, <span class="bu">round</span>(mean_squared_error(y_test_pred,y_test),<span class="dv">3</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Training Error:  293160.8
Test Error:  186366.688</code></pre>
</div>
</div>
</section>
<section id="c-2" class="level2">
<h2 class="anchored" data-anchor-id="c-2">(c)</h2>
<p>[10 pts] Fit a lasso model on the training set, with λ chosen by 10-fold crossvalidation. Report the test error obtained, along with the number of non-zero coefficient estimates.</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb65"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb65-1"><a href="#cb65-1" aria-hidden="true" tabindex="-1"></a><span class="co"># lasso regression with default λ=1.0</span></span>
<span id="cb65-2"><a href="#cb65-2" aria-hidden="true" tabindex="-1"></a>lassoreg <span class="op">=</span> Lasso()</span>
<span id="cb65-3"><a href="#cb65-3" aria-hidden="true" tabindex="-1"></a>model_lasso<span class="op">=</span>lassoreg.fit(x_train, y_train)</span>
<span id="cb65-4"><a href="#cb65-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb65-5"><a href="#cb65-5" aria-hidden="true" tabindex="-1"></a>y_train_pred<span class="op">=</span>model_lasso.predict(x_train)</span>
<span id="cb65-6"><a href="#cb65-6" aria-hidden="true" tabindex="-1"></a>y_test_pred<span class="op">=</span>model_lasso.predict(x_test)</span>
<span id="cb65-7"><a href="#cb65-7" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Training Error: "</span>, <span class="bu">round</span>(mean_squared_error(y_train_pred,y_train),<span class="dv">3</span>))  </span>
<span id="cb65-8"><a href="#cb65-8" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Test Error: "</span>, <span class="bu">round</span>(mean_squared_error(y_test_pred,y_test),<span class="dv">3</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Training Error:  291537.881
Test Error:  190072.628</code></pre>
</div>
</div>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb67"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb67-1"><a href="#cb67-1" aria-hidden="true" tabindex="-1"></a><span class="co"># ridge regression with 10-fold cross validation</span></span>
<span id="cb67-2"><a href="#cb67-2" aria-hidden="true" tabindex="-1"></a>k_fold<span class="op">=</span>KFold(n_splits <span class="op">=</span> <span class="dv">10</span>, shuffle <span class="op">=</span> <span class="va">True</span>,random_state<span class="op">=</span><span class="dv">2022</span>) <span class="co"># set random seed</span></span>
<span id="cb67-3"><a href="#cb67-3" aria-hidden="true" tabindex="-1"></a>max_iter <span class="op">=</span> <span class="dv">15000</span></span>
<span id="cb67-4"><a href="#cb67-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-5"><a href="#cb67-5" aria-hidden="true" tabindex="-1"></a><span class="co"># lambdas = np.arange(0.1,10,0.01) # Smallest Test Error calculated at 2.97 </span></span>
<span id="cb67-6"><a href="#cb67-6" aria-hidden="true" tabindex="-1"></a>lambdas <span class="op">=</span> np.arange(<span class="dv">4</span>,<span class="dv">50</span>,<span class="fl">0.1</span>) </span>
<span id="cb67-7"><a href="#cb67-7" aria-hidden="true" tabindex="-1"></a>    </span>
<span id="cb67-8"><a href="#cb67-8" aria-hidden="true" tabindex="-1"></a>lassoreg_cv <span class="op">=</span> LassoCV(alphas<span class="op">=</span>lambdas, cv<span class="op">=</span>k_fold, max_iter<span class="op">=</span>max_iter) </span>
<span id="cb67-9"><a href="#cb67-9" aria-hidden="true" tabindex="-1"></a>model_lasso_cv<span class="op">=</span>lassoreg_cv.fit(x_train, y_train)</span>
<span id="cb67-10"><a href="#cb67-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-11"><a href="#cb67-11" aria-hidden="true" tabindex="-1"></a>y_train_pred<span class="op">=</span>model_lasso_cv.predict(x_train)</span>
<span id="cb67-12"><a href="#cb67-12" aria-hidden="true" tabindex="-1"></a>y_test_pred<span class="op">=</span>model_lasso_cv.predict(x_test)</span>
<span id="cb67-13"><a href="#cb67-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-14"><a href="#cb67-14" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Training Error (with 10 folds): "</span>, <span class="bu">round</span>(mean_squared_error(y_train_pred,y_train),<span class="dv">3</span>))  </span>
<span id="cb67-15"><a href="#cb67-15" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Test Error (with 10 folds): "</span>, <span class="bu">round</span>(mean_squared_error(y_test_pred,y_test),<span class="dv">3</span>))</span>
<span id="cb67-16"><a href="#cb67-16" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb67-17"><a href="#cb67-17" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Training R Squared: "</span>, <span class="bu">round</span>(r2_score(y_train, y_train_pred),<span class="dv">2</span>))</span>
<span id="cb67-18"><a href="#cb67-18" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Testing R Squared: "</span>, <span class="bu">round</span>(r2_score(y_test, y_test_pred),<span class="dv">2</span>))</span>
<span id="cb67-19"><a href="#cb67-19" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Optimal Lambda: "</span>, model_lasso_cv.alpha_)</span>
<span id="cb67-20"><a href="#cb67-20" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Coefficients: "</span>, model_lasso_cv.coef_)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Training Error (with 10 folds):  292747.201
Test Error (with 10 folds):  181011.81
Training R Squared:  0.95
Testing R Squared:  0.97
Optimal Lambda:  4.0
Coefficients:  [ 126.65222298 1632.17789857  979.5277818  -487.43215826  179.97073683
   -0.          -61.36589383  252.50632841   -8.20028126    0.
  -25.42427626   69.09512846    6.55921777  -15.98829039  -71.29649584
 -156.34592682  -13.15656712]</code></pre>
</div>
</div>
<p>FYI: https://scikit-learn.org/stable/modules/grid_search.html#specifying-an-objective-metric <br> By default, parameter search uses the score function of the estimator to evaluate a parameter setting. (sklearn.metrics.r2_score for regression)</p>
<p>Even though the 10-fold cross-validation r2 score is lowest when <span class="math inline">\(\lambda=3\)</span>, I chose the lambda with less r2 score. Since the purpose of using lasso regression is selecting features (variable selection), lower lambdas are not estimating coefficients with 0. (so I used lambda with 4 which is closest to optimal lambda with some feature’s coefficients are exactly equal to zero)</p>
<div class="cell">
<details>
<summary>Code</summary>
<div class="sourceCode cell-code" id="cb69"><pre class="sourceCode python code-with-copy"><code class="sourceCode python"><span id="cb69-1"><a href="#cb69-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Coefficients with λ=4</span></span>
<span id="cb69-2"><a href="#cb69-2" aria-hidden="true" tabindex="-1"></a>coefs<span class="op">=</span>pd.DataFrame({<span class="st">"Variable"</span>:x_train.columns,<span class="st">"Coefficients"</span>:np.<span class="bu">round</span>(model_lasso_cv.coef_,<span class="dv">3</span>)})</span>
<span id="cb69-3"><a href="#cb69-3" aria-hidden="true" tabindex="-1"></a>display(coefs)</span>
<span id="cb69-4"><a href="#cb69-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-5"><a href="#cb69-5" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Training Error (with 10 folds): "</span>, <span class="bu">round</span>(mean_squared_error(y_train_pred,y_train),<span class="dv">3</span>))  </span>
<span id="cb69-6"><a href="#cb69-6" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Test Error (with 10 folds): "</span>, <span class="bu">round</span>(mean_squared_error(y_test_pred,y_test),<span class="dv">3</span>),<span class="st">"</span><span class="ch">\n</span><span class="st">"</span>)</span>
<span id="cb69-7"><a href="#cb69-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-8"><a href="#cb69-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-9"><a href="#cb69-9" aria-hidden="true" tabindex="-1"></a><span class="co"># Variables selected</span></span>
<span id="cb69-10"><a href="#cb69-10" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Variables selected"</span>)</span>
<span id="cb69-11"><a href="#cb69-11" aria-hidden="true" tabindex="-1"></a>display(coefs[coefs[<span class="st">'Coefficients'</span>]<span class="op">!=</span><span class="dv">0</span>]) </span>
<span id="cb69-12"><a href="#cb69-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb69-13"><a href="#cb69-13" aria-hidden="true" tabindex="-1"></a><span class="bu">print</span>(<span class="st">"Variables not selected"</span>)</span>
<span id="cb69-14"><a href="#cb69-14" aria-hidden="true" tabindex="-1"></a>display(coefs[coefs[<span class="st">'Coefficients'</span>]<span class="op">==</span><span class="dv">0</span>].Variable.to_numpy())</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-display">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>Variable</th>
      <th>Coefficients</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>Private</td>
      <td>126.652</td>
    </tr>
    <tr>
      <th>1</th>
      <td>Apps</td>
      <td>1632.178</td>
    </tr>
    <tr>
      <th>2</th>
      <td>Enroll</td>
      <td>979.528</td>
    </tr>
    <tr>
      <th>3</th>
      <td>Top10perc</td>
      <td>-487.432</td>
    </tr>
    <tr>
      <th>4</th>
      <td>Top25perc</td>
      <td>179.971</td>
    </tr>
    <tr>
      <th>5</th>
      <td>F.Undergrad</td>
      <td>-0.000</td>
    </tr>
    <tr>
      <th>6</th>
      <td>P.Undergrad</td>
      <td>-61.366</td>
    </tr>
    <tr>
      <th>7</th>
      <td>Outstate</td>
      <td>252.506</td>
    </tr>
    <tr>
      <th>8</th>
      <td>Room.Board</td>
      <td>-8.200</td>
    </tr>
    <tr>
      <th>9</th>
      <td>Books</td>
      <td>0.000</td>
    </tr>
    <tr>
      <th>10</th>
      <td>Personal</td>
      <td>-25.424</td>
    </tr>
    <tr>
      <th>11</th>
      <td>PhD</td>
      <td>69.095</td>
    </tr>
    <tr>
      <th>12</th>
      <td>Terminal</td>
      <td>6.559</td>
    </tr>
    <tr>
      <th>13</th>
      <td>S.F.Ratio</td>
      <td>-15.988</td>
    </tr>
    <tr>
      <th>14</th>
      <td>perc.alumni</td>
      <td>-71.296</td>
    </tr>
    <tr>
      <th>15</th>
      <td>Expend</td>
      <td>-156.346</td>
    </tr>
    <tr>
      <th>16</th>
      <td>Grad.Rate</td>
      <td>-13.157</td>
    </tr>
  </tbody>
</table>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Training Error (with 10 folds):  292747.201
Test Error (with 10 folds):  181011.81 

Variables selected</code></pre>
</div>
<div class="cell-output cell-output-display">

<div>

<table class="dataframe table table-sm table-striped">
  <thead>
    <tr>
      <th></th>
      <th>Variable</th>
      <th>Coefficients</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>0</th>
      <td>Private</td>
      <td>126.652</td>
    </tr>
    <tr>
      <th>1</th>
      <td>Apps</td>
      <td>1632.178</td>
    </tr>
    <tr>
      <th>2</th>
      <td>Enroll</td>
      <td>979.528</td>
    </tr>
    <tr>
      <th>3</th>
      <td>Top10perc</td>
      <td>-487.432</td>
    </tr>
    <tr>
      <th>4</th>
      <td>Top25perc</td>
      <td>179.971</td>
    </tr>
    <tr>
      <th>6</th>
      <td>P.Undergrad</td>
      <td>-61.366</td>
    </tr>
    <tr>
      <th>7</th>
      <td>Outstate</td>
      <td>252.506</td>
    </tr>
    <tr>
      <th>8</th>
      <td>Room.Board</td>
      <td>-8.200</td>
    </tr>
    <tr>
      <th>10</th>
      <td>Personal</td>
      <td>-25.424</td>
    </tr>
    <tr>
      <th>11</th>
      <td>PhD</td>
      <td>69.095</td>
    </tr>
    <tr>
      <th>12</th>
      <td>Terminal</td>
      <td>6.559</td>
    </tr>
    <tr>
      <th>13</th>
      <td>S.F.Ratio</td>
      <td>-15.988</td>
    </tr>
    <tr>
      <th>14</th>
      <td>perc.alumni</td>
      <td>-71.296</td>
    </tr>
    <tr>
      <th>15</th>
      <td>Expend</td>
      <td>-156.346</td>
    </tr>
    <tr>
      <th>16</th>
      <td>Grad.Rate</td>
      <td>-13.157</td>
    </tr>
  </tbody>
</table>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>Variables not selected</code></pre>
</div>
<div class="cell-output cell-output-display">
<pre><code>array(['F.Undergrad', 'Books'], dtype=object)</code></pre>
</div>
</div>
<p>Coefficients of variable “F.Undergrad”, “Books” are equal to zero with lambda 4</p>
</section>
<section id="d-2" class="level2">
<h2 class="anchored" data-anchor-id="d-2">(d)</h2>
<p>[10 pts] Comment on the results obtained.</p>
<ul>
<li>How accurately can you predict the number of college applications received? <br></li>
<li>Is there much difference among the test errors resulting from these three approaches? <br></li>
</ul>
<table class="table">
<colgroup>
<col style="width: 33%">
<col style="width: 33%">
<col style="width: 33%">
</colgroup>
<thead>
<tr class="header">
<th>Methods</th>
<th>Score</th>
<th>Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>OLS</td>
<td>Test Mean Squared Error</td>
<td>192960.565</td>
</tr>
<tr class="even">
<td>Ridge</td>
<td>Test Mean Squared Error (with 10 folds)</td>
<td>186366.688</td>
</tr>
<tr class="odd">
<td>Lasso</td>
<td>Test Mean Squared Error (with 10 folds + variable selection)</td>
<td>181011.81</td>
</tr>
</tbody>
</table>
<p>The lowest mean squared error was calculated using Lasso regression with two variables’ coeficients are equal to zero. The test error of Lasso is lower compared to OLS (11948.76), Ridge (6593.88).</p>
<ul>
<li>Which model would you use?</li>
</ul>
<p>The ridge and lasso regression is a shirinkage methods that constrains and regularizes the coefficient estimates. It is true that these two models are improving the fit compared to OLS, but they are not without potential disadvantages. They comprised a unbiasedness of the OLS and reduce variance, which may result in overfitting. Therefore, with caution, the lasso regression would be selected. Lasso regression can be used as a techniques to selecting important predictors out of an comparatively less important predictors.</p>


</section>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const disableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'prefetch';
    }
  }
  const enableStylesheet = (stylesheets) => {
    for (let i=0; i < stylesheets.length; i++) {
      const stylesheet = stylesheets[i];
      stylesheet.rel = 'stylesheet';
    }
  }
  const manageTransitions = (selector, allowTransitions) => {
    const els = window.document.querySelectorAll(selector);
    for (let i=0; i < els.length; i++) {
      const el = els[i];
      if (allowTransitions) {
        el.classList.remove('notransition');
      } else {
        el.classList.add('notransition');
      }
    }
  }
  const toggleColorMode = (alternate) => {
    // Switch the stylesheets
    const alternateStylesheets = window.document.querySelectorAll('link.quarto-color-scheme.quarto-color-alternate');
    manageTransitions('#quarto-margin-sidebar .nav-link', false);
    if (alternate) {
      enableStylesheet(alternateStylesheets);
      for (const sheetNode of alternateStylesheets) {
        if (sheetNode.id === "quarto-bootstrap") {
          toggleBodyColorMode(sheetNode);
        }
      }
    } else {
      disableStylesheet(alternateStylesheets);
      toggleBodyColorPrimary();
    }
    manageTransitions('#quarto-margin-sidebar .nav-link', true);
    // Switch the toggles
    const toggles = window.document.querySelectorAll('.quarto-color-scheme-toggle');
    for (let i=0; i < toggles.length; i++) {
      const toggle = toggles[i];
      if (toggle) {
        if (alternate) {
          toggle.classList.add("alternate");     
        } else {
          toggle.classList.remove("alternate");
        }
      }
    }
    // Hack to workaround the fact that safari doesn't
    // properly recolor the scrollbar when toggling (#1455)
    if (navigator.userAgent.indexOf('Safari') > 0 && navigator.userAgent.indexOf('Chrome') == -1) {
      manageTransitions("body", false);
      window.scrollTo(0, 1);
      setTimeout(() => {
        window.scrollTo(0, 0);
        manageTransitions("body", true);
      }, 40);  
    }
  }
  const isFileUrl = () => { 
    return window.location.protocol === 'file:';
  }
  const hasAlternateSentinel = () => {  
    let styleSentinel = getColorSchemeSentinel();
    if (styleSentinel !== null) {
      return styleSentinel === "alternate";
    } else {
      return false;
    }
  }
  const setStyleSentinel = (alternate) => {
    const value = alternate ? "alternate" : "default";
    if (!isFileUrl()) {
      window.localStorage.setItem("quarto-color-scheme", value);
    } else {
      localAlternateSentinel = value;
    }
  }
  const getColorSchemeSentinel = () => {
    if (!isFileUrl()) {
      const storageValue = window.localStorage.getItem("quarto-color-scheme");
      return storageValue != null ? storageValue : localAlternateSentinel;
    } else {
      return localAlternateSentinel;
    }
  }
  let localAlternateSentinel = 'default';
  // Dark / light mode switch
  window.quartoToggleColorScheme = () => {
    // Read the current dark / light value 
    let toAlternate = !hasAlternateSentinel();
    toggleColorMode(toAlternate);
    setStyleSentinel(toAlternate);
  };
  // Ensure there is a toggle, if there isn't float one in the top right
  if (window.document.querySelector('.quarto-color-scheme-toggle') === null) {
    const a = window.document.createElement('a');
    a.classList.add('top-right');
    a.classList.add('quarto-color-scheme-toggle');
    a.href = "";
    a.onclick = function() { try { window.quartoToggleColorScheme(); } catch {} return false; };
    const i = window.document.createElement("i");
    i.classList.add('bi');
    a.appendChild(i);
    window.document.body.appendChild(a);
  }
  // Switch to dark mode if need be
  if (hasAlternateSentinel()) {
    toggleColorMode(true);
  } 
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
      <div class="nav-footer-center">
        <ul class="footer-items list-unstyled">
    <li class="nav-item">
 © 2022 Sangwon Ju
  </li>  
</ul>
      </div>
  </div>
</footer>



</body></html>