{
  "hash": "9f9fb048189b7f3b896de399d8d8c622",
  "result": {
    "markdown": "---\ntitle: \"EDA Assignment 5: Chapter 7\"\nauthor: \"Sangwon Ju, Yonsei Public Administration\"\ndate: 'may/11/2021'\npage-layout: full\nformat: \n    html\ncategories: \n    \"Exploratory Data Analysis (2021 Spring) [in Korean]\"\nimage: \"image.png\"\n---\n\n\n7장. 2원 자료, 빈도 표의 탐색\n\n# 추가과제: titanic\n\n## 1)\n\nOn your own; The survival rates differ in Children?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmosaicplot(~ Age+Sex+Survived, data = Titanic,color = c(\"brown\",\"darkgreen\"))\n```\n\n::: {.cell-output-display}\n![](과제5_files/figure-html/unnamed-chunk-1-1.png){width=672}\n:::\n:::\n\n\n성인 집단에서는 여성과 남성 사이의 생존율에는 큰 차이가 보여지고 있는데에 비해, 어린아이들의 집단에서는 여성과 남성의 생존율이 큰 차이가 있지 않는 것으로 보인다. 일반적인 상황에서 선원들의 통제가 잘 이루어지지 않는 경우 여성들과 아이들의 생존율이 매우 낮아지지만, 타이타닉호 사건 때는 승객들에 대한 통제도와 선원들의 상선사관들의 명령 복종정도가 높았기 때문에 여자와 아이들 먼저 규칙에 의해 남자아이들의 생존율이 성인 남자의 생존율에 비해서 상당히 높게 나타났다.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmosaicplot(~ Class + Age  + Survived, data = Titanic, color = c(\"brown\",\"darkgreen\"))\n```\n\n::: {.cell-output-display}\n![](과제5_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n:::\n\n\n1등석과 2등석의 아이들은 1명빼고 전부 살아남았지만, 3등실에서 구조되지 못한 어린이는 구조된 수의 거의 두 배에 가까웠다. 3등석의 아이들이 1등석과 2등석에 비해서 살아남기 힘들었던 이유는 배 안의 구조가 복잡했기 때문이다. 3등석에는 영어를 잘 하지 못하는 승객들도 많았기에 갑판과 적절한 의사소통을 하지못해 밖으로 나가는 것을 실패한 사람들이 많다는 점에서 그 이유를 찾을 수 있다.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nmosaicplot(~ Sex + Class + Age + Survived, data = Titanic, color = c(\"brown\",\"darkgreen\"))\n```\n\n::: {.cell-output-display}\n![](과제5_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\n모든 요인을 합친 그래프이다. 1등석, 2등석 모두 어린아이들이 어른에 비해, 여자들이 남자들에 비해 생존확률이 월등히 높다. 3등석의 경우에도 여자 아이들이 남자아이들에 비해서 생존 확률이 월등히 높았다는 점에서 \"여자와 아이\"먼저 원칙이 지켜지고 있음이 확인되고 있다. 함장 로버트 샐먼드(Robert Salmond) 해군 대령 이하 육해군 장병들은 갑판에 부동 자세로 도열한 채로 질서를 유지하였기 대문에 규칙이 지켜질 수 있었고, 승객들은 명령에 복종할 수 밖에 없었던 것으로 보인다.\n\n# 1번\n\n아래 자료를 분석하여라. The data are part of a larger experiments to determine the effectiveness of blast furnace slags (고로 슬랙) as agricultural liming materials (중화작업) on three types of soil, sandy loams(I), sandy clay loam(II), and loamy sand(III). The treatments were all applied at 4000 lbs per acre, and what was measured was the corn yield in bushels per acre.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntreatment=c(11.1,32.6,63.3,15.3,40.8,65.0,22.7,52.1,58.8,23.8,52.8,61.4,25.6,63.1,41.1,31.2,59.5,78.1,25.8,55.3,60.2)\nm=mean(treatment)\nm\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 44.74286\n```\n:::\n\n```{.r .cell-code}\ntreatment=as.data.frame(matrix(treatment,byrow=T,ncol=3))\nnames(treatment)=c(\"sandy loams(I)\", \"sandy clay loam(II)\", \"loamy sand(III)\")\nrownames(treatment)=c(\"None\",\"Coarse slag\",\"Mediaum slag\",\"Agricultural slag\",\"Agricultural limestone\",\"Agricultural slag + minor limestone\",\"Agricultural limestone + minor elements\")\ntreatment\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                                        sandy loams(I) sandy clay loam(II)\nNone                                              11.1                32.6\nCoarse slag                                       15.3                40.8\nMediaum slag                                      22.7                52.1\nAgricultural slag                                 23.8                52.8\nAgricultural limestone                            25.6                63.1\nAgricultural slag + minor limestone               31.2                59.5\nAgricultural limestone + minor elements           25.8                55.3\n                                        loamy sand(III)\nNone                                               63.3\nCoarse slag                                        65.0\nMediaum slag                                       58.8\nAgricultural slag                                  61.4\nAgricultural limestone                             41.1\nAgricultural slag + minor limestone                78.1\nAgricultural limestone + minor elements            60.2\n```\n:::\n:::\n\n\n행은 blast furnace slags의 유형 / 열은 토양의 종류를 의미한다. 고로 슬랙과 토양이 농업 중화 작업에 영향을 미치고 있는데 각각이 영향을 미치는 정도에 대해서 분석을 진행해보고자 한다.\n\n고로 슬랙을 i, 토양을 j로 표기하고 i와 j에 따른 중화작업의 효과를 y_ij로 나타내고자 한다. y_ij에 대한 Additivity Model y_ij=μ (all) + α_i (row_effect) + β_j (column_effect) + e_ij (residual), e\\~(0,sigma), i=(1,...,7),j=(1,...,3)을 고려한다. (All, Common, Constant )\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntreatment=c(11.1,32.6,63.3,15.3,40.8,65.0,22.7,52.1,58.8,23.8,52.8,61.4,25.6,63.1,41.1,31.2,59.5,78.1,25.8,55.3,60.2)\nm=mean(treatment)\nm\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 44.74286\n```\n:::\n\n```{.r .cell-code}\ntreatment=as.data.frame(matrix(treatment,byrow=T,ncol=3))\nnames(treatment)=c(\"sandy loams(I)\", \"sandy clay loam(II)\", \"loamy sand(III)\")\nrownames(treatment)=c(\"None\",\"Coarse slag\",\"Mediaum slag\",\"Agricultural slag\",\"Agricultural limestone\",\"Agricultural slag + minor limestone\",\"Agricultural limestone + minor elements\")\ntreatment\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                                        sandy loams(I) sandy clay loam(II)\nNone                                              11.1                32.6\nCoarse slag                                       15.3                40.8\nMediaum slag                                      22.7                52.1\nAgricultural slag                                 23.8                52.8\nAgricultural limestone                            25.6                63.1\nAgricultural slag + minor limestone               31.2                59.5\nAgricultural limestone + minor elements           25.8                55.3\n                                        loamy sand(III)\nNone                                               63.3\nCoarse slag                                        65.0\nMediaum slag                                       58.8\nAgricultural slag                                  61.4\nAgricultural limestone                             41.1\nAgricultural slag + minor limestone                78.1\nAgricultural limestone + minor elements            60.2\n```\n:::\n\n```{.r .cell-code}\ntreatment_polished=medpolish(treatment)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n1: 109.3\n2: 84.6\nFinal: 84.6\n```\n:::\n\n```{.r .cell-code}\ntreatment_polished\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nMedian Polish Results (Dataset: \"treatment\")\n\nOverall: 52.8\n\nRow Effects:\n                                   None                             Coarse slag \n                                  -13.4                                    -9.2 \n                           Mediaum slag                       Agricultural slag \n                                   -1.8                                     0.0 \n                 Agricultural limestone     Agricultural slag + minor limestone \n                                    1.1                                     6.7 \nAgricultural limestone + minor elements \n                                    1.3 \n\nColumn Effects:\n     sandy loams(I) sandy clay loam(II)     loamy sand(III) \n              -28.3                 0.0                 8.6 \n\nResiduals:\n                                        sandy loams(I) sandy clay loam(II)\nNone                                               0.0                -6.8\nCoarse slag                                        0.0                -2.8\nMediaum slag                                       0.0                 1.1\nAgricultural slag                                 -0.7                 0.0\nAgricultural limestone                             0.0                 9.2\nAgricultural slag + minor limestone                0.0                 0.0\nAgricultural limestone + minor elements            0.0                 1.2\n                                        loamy sand(III)\nNone                                               15.3\nCoarse slag                                        12.8\nMediaum slag                                       -0.8\nAgricultural slag                                   0.0\nAgricultural limestone                            -21.4\nAgricultural slag + minor limestone                10.0\nAgricultural limestone + minor elements            -2.5\n```\n:::\n\n```{.r .cell-code}\n# medpolish()를 이용하여 중간값 다듬기를 진행하였는데 maxiter=1일 때는 수렴하지 않았다는 경고 메시지를 확인할 수 있었고 maxiter를 설정하지 않고 분석한 결과 maxiter=2에서 결과 값이 나오는 것을 확인하였다.\n\nplot(treatment_polished)\n# 0의 값들이 상당히 많은 것이 확인되고 있다. 0 라인 밖에 있는 점들은 딱 6개만 확인되고 있기 때문에 따로 선을 그리기가 어렵다.\n\nplot(treatment_polished)\nabline(0,-10) # 적절하지 않다. \nabline(0,10) # 적절하지 않다. \nabline(lm(as.vector(treatment_polished$residuals) ~ \n            as.vector(outer(treatment_polished$row,treatment_polished$col, \"*\")/treatment_polished$overall)),col=\"orange\")\n```\n\n::: {.cell-output-display}\n![](과제5_files/figure-html/unnamed-chunk-5-1.png){width=672}\n:::\n\n```{.r .cell-code}\nlm(as.vector(treatment_polished$residuals) ~ \n     as.vector(outer(treatment_polished$row,treatment_polished$col, \"*\")/treatment_polished$overall))[1]\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n$coefficients\n                                                                                     (Intercept) \n                                                                                       0.8341529 \nas.vector(outer(treatment_polished$row, treatment_polished$col, \"*\")/treatment_polished$overall) \n                                                                                      -0.5110273 \n```\n:::\n\n```{.r .cell-code}\n# 기울기 -0.5110이므로 1과는 다르다. (log 변환의 필요성이 떨어진다.)\n# 직선을 그리기가 어렵다. (경향성이 따로 보이지는 않아보인다.)\n\n# Plot에서 어떠한 의미있는 패턴이 나타나지 않기 때문에 변환이 요구되지 않는 것으로 보인다.\n\nboxplot(treatment_polished$residuals)\n```\n\n::: {.cell-output-display}\n![](과제5_files/figure-html/unnamed-chunk-5-2.png){width=672}\n:::\n\n```{.r .cell-code}\n# Residual 값을 가지고 boxplot을 그려보았는데 sandy loams에는 outlier 1개, sandy clay loam에는 outlier 2개, loamy sand에는 outlier 1개이다.\n\n# 행 효과 크기 순으로 재정렬한 잔차표\nround(treatment_polished$residuals[order(treatment_polished$row),],1)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                                        sandy loams(I) sandy clay loam(II)\nNone                                               0.0                -6.8\nCoarse slag                                        0.0                -2.8\nMediaum slag                                       0.0                 1.1\nAgricultural slag                                 -0.7                 0.0\nAgricultural limestone                             0.0                 9.2\nAgricultural limestone + minor elements            0.0                 1.2\nAgricultural slag + minor limestone                0.0                 0.0\n                                        loamy sand(III)\nNone                                               15.3\nCoarse slag                                        12.8\nMediaum slag                                       -0.8\nAgricultural slag                                   0.0\nAgricultural limestone                            -21.4\nAgricultural limestone + minor elements            -2.5\nAgricultural slag + minor limestone                10.0\n```\n:::\n\n```{.r .cell-code}\n# Check Decomposition\ndecomposed=(treatment_polished$overall + outer(treatment_polished$row,treatment_polished$col, \"+\") + treatment_polished$residuals)\nall(round(decomposed,1)==treatment)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] TRUE\n```\n:::\n\n```{.r .cell-code}\n# 가법성 모형이 확인되어지고 있다.\n\n# Comparison Values\nround(outer(treatment_polished$row,treatment_polished$col, \"*\")/treatment_polished$overall,2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                                        sandy loams(I) sandy clay loam(II)\nNone                                              7.18                   0\nCoarse slag                                       4.93                   0\nMediaum slag                                      0.96                   0\nAgricultural slag                                 0.00                   0\nAgricultural limestone                           -0.59                   0\nAgricultural slag + minor limestone              -3.59                   0\nAgricultural limestone + minor elements          -0.70                   0\n                                        loamy sand(III)\nNone                                              -2.18\nCoarse slag                                       -1.50\nMediaum slag                                      -0.29\nAgricultural slag                                  0.00\nAgricultural limestone                             0.18\nAgricultural slag + minor limestone                1.09\nAgricultural limestone + minor elements            0.21\n```\n:::\n\n```{.r .cell-code}\n# Comparison value 기준으로 0값이 총 9개 확인됨. 그런데 더 많은 값들이 Additivity Plot의 x축과 y축 근처에 존재하는 것으로 보아 몇몇 피팅에서 벗어난 값을 제외하면 대부분 0근처에서 존재하고 있는 것이 확인된다. \n\n# 필요 없지만 그려서 확인하기\n# Log 변환 모형과 비교해보기\ntreatment_polished2=medpolish(log(treatment))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n1: 2.631752\n2: 2.157306\nFinal: 2.157306\n```\n:::\n\n```{.r .cell-code}\ntreatment_polished2\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nMedian Polish Results (Dataset: \"log(treatment)\")\n\nOverall: 3.966511\n\nRow Effects:\n                                   None                             Coarse slag \n                            -0.48219890                             -0.25782911 \n                           Mediaum slag                       Agricultural slag \n                            -0.04326798                              0.00000000 \n                 Agricultural limestone     Agricultural slag + minor limestone \n                             0.07290677                              0.24058022 \nAgricultural limestone + minor elements \n                             0.04626172 \n\nColumn Effects:\n     sandy loams(I) sandy clay loam(II)     loamy sand(III) \n         -0.7968256           0.0000000           0.1508986 \n\nResiduals:\n                                        sandy loams(I) sandy clay loam(II)\nNone                                        -0.2805416            0.000000\nCoarse slag                                 -0.1840036            0.000000\nMediaum slag                                -0.0040527            0.029922\nAgricultural slag                            0.0000000            0.000000\nAgricultural limestone                       0.0000000            0.105303\nAgricultural slag + minor limestone          0.0301523           -0.121115\nAgricultural limestone + minor elements      0.0344272            0.000000\n                                        loamy sand(III)\nNone                                           0.512674\nCoarse slag                                    0.314807\nMediaum slag                                   0.000000\nAgricultural slag                              0.000000\nAgricultural limestone                        -0.474308\nAgricultural slag + minor limestone            0.000000\nAgricultural limestone + minor elements       -0.065999\n```\n:::\n\n```{.r .cell-code}\nplot(treatment_polished2)\n```\n\n::: {.cell-output-display}\n![](과제5_files/figure-html/unnamed-chunk-5-3.png){width=672}\n:::\n\n```{.r .cell-code}\nouter(treatment_polished2$row,treatment_polished2$col, \"*\")/treatment_polished2$overall\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                                        sandy loams(I) sandy clay loam(II)\nNone                                       0.096868108                   0\nCoarse slag                                0.051794846                   0\nMediaum slag                               0.008692030                   0\nAgricultural slag                          0.000000000                   0\nAgricultural limestone                    -0.014646116                   0\nAgricultural slag + minor limestone       -0.048329747                   0\nAgricultural limestone + minor elements   -0.009293437                   0\n                                        loamy sand(III)\nNone                                       -0.018344373\nCoarse slag                                -0.009808636\nMediaum slag                               -0.001646051\nAgricultural slag                           0.000000000\nAgricultural limestone                      0.002773604\nAgricultural slag + minor limestone         0.009152433\nAgricultural limestone + minor elements     0.001759942\n```\n:::\n\n```{.r .cell-code}\n# Log 변환 이전과 이후의 Residual 값들을 비교하였을 때 한개 값을 제외하면 변환이전의 값들이 더 0 근처에 모여있다는 점에서 변환 이전의 데이터를 사용하고자 한다.\nstem(treatment_polished$residuals);stem(treatment_polished2$residuals)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  The decimal point is 1 digit(s) to the right of the |\n\n  -2 | 1\n  -1 | \n  -0 | 73311\n   0 | 000000000119\n   1 | 035\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  The decimal point is 1 digit(s) to the left of the |\n\n  -4 | 7\n  -2 | 8\n  -0 | 8270\n   0 | 0000000003331\n   2 | 1\n   4 | 1\n```\n:::\n:::\n\n\nRaw Data를 활용하여 Column Effect(토양)와 Row Effect(고로 슬랙)를 시각화해보고자 한다.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Row Effect \nbarplot(treatment_polished$row, ylim=c(-15,15), main=\"Agriculutre Slag의 효과\")\n```\n\n::: {.cell-output-display}\n![](과제5_files/figure-html/unnamed-chunk-6-1.png){width=672}\n:::\n\n```{.r .cell-code}\ntreatment_polished$row\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                                   None                             Coarse slag \n                                  -13.4                                    -9.2 \n                           Mediaum slag                       Agricultural slag \n                                   -1.8                                     0.0 \n                 Agricultural limestone     Agricultural slag + minor limestone \n                                    1.1                                     6.7 \nAgricultural limestone + minor elements \n                                    1.3 \n```\n:::\n\n```{.r .cell-code}\n# Column Effect\nbarplot(treatment_polished$col, ylim=c(-30,10) , main=\"Soil의 효과\")\n```\n\n::: {.cell-output-display}\n![](과제5_files/figure-html/unnamed-chunk-6-2.png){width=672}\n:::\n\n```{.r .cell-code}\ntreatment_polished$col\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n     sandy loams(I) sandy clay loam(II)     loamy sand(III) \n              -28.3                 0.0                 8.6 \n```\n:::\n:::\n\n\n먼저, Row Effect에 대해서 분석해보고자 한다. 6가지의 처치 중 Agricultural slag + minor limestone이 6.7으로 가장 효과적인 것으로 보이며, Coarce Slag이 덜 효과적인 것이 확인된다. 나머지 처리들도 전부 토양 중성화에 어느정도 효과적인 것으로 보인다. y축의 단위가 무엇인지 정확히 알 수 없기에 단순히 중화수준이 높게 나온다고 좋다고 말할 수는 없지만 (왜냐하면 토양 산도는 너무 높아져도 너무 낮아져도 안되고 적정수준을 유지해야하기 때문이다.) 중화작업엔 Agricultural slag + minor limestone이 효과적인 것으로 보인다. 다음은 Column Effect에 대해서 분석해보고자 한다. 3가지 토양 종류 중 loamy sand에서 중화 효과가 가장 좋고,sandy loams의 중화효과는 나쁘게 나타난다. 위에서 언급하였듯이 결과변수의 단위가 정확히 무엇인지 언급되어있지 않기 때문에 단순히 loamy sand가 sandy loams에 비해서 더 좋다고 이야기 하기 힘들다. 하지만 토양 중성화가 강하게 요구되는 작물의 경우 loamy sand에서 키우는 것이 가장 효과적일 것으로 보인다. 토양효과가 가장 적은 sangy clay loam에서 각 treatment들의 효과를 비교하면 더 잘 드러나게 될 것으로 보인다.\n\n각 Soil을 묶어서 보았을 때에는 Agricultural slag + minor limestone이 중화효과가 가장 높게 나타났지만, Sandy loams에서는 Agricultural slag + minor limestone을 사용하더라도 중화효과가 거의 나타나지 않을 수도 있다. 또한 loamy sand의 중화효과가 가장 높게 나타났음에도 불구하고 Agricultural limestone을 사용할 경우에 중화효과에 부정적인 영향을 줄 수 있다는 것을 확인하는 것이 필요하다. 따라서, 자신의 작물을 키우는 Soil에 적합한 slag을 선택하는 것이 최적의 중화효과를 달성하는데 있어서 가장 적절할 것으로 보인다.\\\n우선, 자신의 농장이 Sandy Loams일 경우 Agricultural Slag을 사용해서는 안되고, Slag을 사용하였을 때 사용하지 않았을 때에 비해 중화효과는 큰 차이가 없을 것이다. 자신의 농장이 Sandy Clay Loams일 경우 Agricultural limestone이 가장 효과적이다. 자신의 농장이 Loamy sand일 경우 Agricultural limestone은 중화에 부정적인 영향을 미칠 뿐만 아니라 아무런 처치를 하지 않았을 때 중화효과가 가장 높게 나타난다. 따라서, Slag의 Treatment는 자신의 농장이 sandy clay loams토양으로 이루어져 있을 때에만 agricultural limestone 위주로 사용하는 것이 좋고 나머지 토양에서는 treatment가 효과가 없거나 부정적인 효과를 보일 수 있으므로 사용하지 않는 것이 바람직 할 것으로 보인다.\n\n# 2번\n\n교과서 7.4절 버클리 대학교 대학원 지원자 자료의 분석 내용을 그대로 따라 실행하고 분석하여라. (본인이 책을 읽고 이해한 후 책을 덮고 이해한 분석 내용을 본인의 문자으로 적어 내면 됨. 거의 똑같아도 됨.) 인터넷에서 심프슨의 역설에 대한 예를 세 개 찾아보아라.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(UCBAdmissions) # 3차원 배열\nadm=UCBAdmissions\nadm\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n, , Dept = A\n\n          Gender\nAdmit      Male Female\n  Admitted  512     89\n  Rejected  313     19\n\n, , Dept = B\n\n          Gender\nAdmit      Male Female\n  Admitted  353     17\n  Rejected  207      8\n\n, , Dept = C\n\n          Gender\nAdmit      Male Female\n  Admitted  120    202\n  Rejected  205    391\n\n, , Dept = D\n\n          Gender\nAdmit      Male Female\n  Admitted  138    131\n  Rejected  279    244\n\n, , Dept = E\n\n          Gender\nAdmit      Male Female\n  Admitted   53     94\n  Rejected  138    299\n\n, , Dept = F\n\n          Gender\nAdmit      Male Female\n  Admitted   22     24\n  Rejected  351    317\n```\n:::\n\n```{.r .cell-code}\n#결측치 확인\nis.na(adm) # 없음\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n, , Dept = A\n\n          Gender\nAdmit       Male Female\n  Admitted FALSE  FALSE\n  Rejected FALSE  FALSE\n\n, , Dept = B\n\n          Gender\nAdmit       Male Female\n  Admitted FALSE  FALSE\n  Rejected FALSE  FALSE\n\n, , Dept = C\n\n          Gender\nAdmit       Male Female\n  Admitted FALSE  FALSE\n  Rejected FALSE  FALSE\n\n, , Dept = D\n\n          Gender\nAdmit       Male Female\n  Admitted FALSE  FALSE\n  Rejected FALSE  FALSE\n\n, , Dept = E\n\n          Gender\nAdmit       Male Female\n  Admitted FALSE  FALSE\n  Rejected FALSE  FALSE\n\n, , Dept = F\n\n          Gender\nAdmit       Male Female\n  Admitted FALSE  FALSE\n  Rejected FALSE  FALSE\n```\n:::\n\n```{.r .cell-code}\n(Tab1<-adm[1,,]) # Admitted\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n        Dept\nGender     A   B   C   D   E   F\n  Male   512 353 120 138  53  22\n  Female  89  17 202 131  94  24\n```\n:::\n\n```{.r .cell-code}\n(Tab2<-adm[2,,]) # Rejected\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n        Dept\nGender     A   B   C   D   E   F\n  Male   313 207 205 279 138 351\n  Female  19   8 391 244 299 317\n```\n:::\n\n```{.r .cell-code}\n(Tab=Tab1+Tab2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n        Dept\nGender     A   B   C   D   E   F\n  Male   825 560 325 417 191 373\n  Female 108  25 593 375 393 341\n```\n:::\n\n```{.r .cell-code}\nTab3=addmargins(Tab)\n\n\n# List 다루기 힘들어서 변환\nTab=matrix(Tab,byrow=F,ncol=6)\ncolnames(Tab)=c(LETTERS[1:6])\nrownames(Tab)=c(\"Male\",\"Female\")\nTab\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n         A   B   C   D   E   F\nMale   825 560 325 417 191 373\nFemale 108  25 593 375 393 341\n```\n:::\n\n```{.r .cell-code}\n# 학과별 남여 지원 비율 비교\npTab=prop.table(Tab,2)\npTab\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n               A          B         C         D         E        F\nMale   0.8842444 0.95726496 0.3540305 0.5265152 0.3270548 0.522409\nFemale 0.1157556 0.04273504 0.6459695 0.4734848 0.6729452 0.477591\n```\n:::\n\n```{.r .cell-code}\nbarplot(Tab,legend=rownames(Tab),ylab=\"count\",main=\"All Applicants w/ exact per dpt\",col=c(\"skyblue\",\"hotpink\"))\n```\n\n::: {.cell-output-display}\n![](과제5_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n\n```{.r .cell-code}\nbarplot(pTab*100,legend=rownames(Tab),ylab=\"%\",main=\"All Applicants w/ proportional per dpt\",col=c(\"skyblue\",\"hotpink\")) \n```\n\n::: {.cell-output-display}\n![](과제5_files/figure-html/unnamed-chunk-7-2.png){width=672}\n:::\n\n```{.r .cell-code}\nlibrary(ghibli)\nghibli_palettes$MarnieLight1\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n<colors>\n#95918EFF #AF9699FF #80C7C9FF #8EBBD2FF #E3D1C3FF #B3DDEBFF #F3E8CCFF \n```\n:::\n\n```{.r .cell-code}\n# 성별 학과 지원 비율 비교\npTab2=prop.table(Tab,1)\npTab2\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                A          B         C         D          E         F\nMale   0.30657748 0.20810108 0.1207729 0.1549610 0.07097733 0.1386102\nFemale 0.05885559 0.01362398 0.3231608 0.2043597 0.21416894 0.1858311\n```\n:::\n\n```{.r .cell-code}\nbarplot(t(Tab),beside=T,legend=colnames(Tab),ylab=\"count\",main=\"All Applicants w/ exact per sex\",col=ghibli_palettes$MarnieLight1[2:7])\n```\n\n::: {.cell-output-display}\n![](과제5_files/figure-html/unnamed-chunk-7-3.png){width=672}\n:::\n\n```{.r .cell-code}\nbarplot(t(pTab2)*100,beside=T,legend=colnames(Tab),ylab=\"%\",main=\"All Applicants w/ proportional per sex\",col=ghibli_palettes$MarnieLight1[2:7],ylim=c(0,35)) \n```\n\n::: {.cell-output-display}\n![](과제5_files/figure-html/unnamed-chunk-7-4.png){width=672}\n:::\n\n```{.r .cell-code}\n# 남성들의 경우 A과나 B과에 50% 이상 배정되어 있는 것에 비해 여성들의 경우 대부분(90%) C,D,E,F과에 재학중인 것이 확인된다.\n\n# 성별 합격률 비교\n\nTab.M<-adm[,1,]\nTab.M\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n          Dept\nAdmit        A   B   C   D   E   F\n  Admitted 512 353 120 138  53  22\n  Rejected 313 207 205 279 138 351\n```\n:::\n\n```{.r .cell-code}\nTab.F<-adm[,2,]\nTab.F\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n          Dept\nAdmit        A   B   C   D   E   F\n  Admitted  89  17 202 131  94  24\n  Rejected  19   8 391 244 299 317\n```\n:::\n\n```{.r .cell-code}\n(Tab.M=matrix(Tab.M,byrow=F,ncol=6))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n     [,1] [,2] [,3] [,4] [,5] [,6]\n[1,]  512  353  120  138   53   22\n[2,]  313  207  205  279  138  351\n```\n:::\n\n```{.r .cell-code}\ncolnames(Tab.M)=c(LETTERS[1:6])\nrownames(Tab.M)=c(\"Admitted\",\"Rejected\")\nTab.M\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n           A   B   C   D   E   F\nAdmitted 512 353 120 138  53  22\nRejected 313 207 205 279 138 351\n```\n:::\n\n```{.r .cell-code}\np.Tab.M=prop.table(Tab.M,2)\nbarplot(p.Tab.M*100,legend=rownames(Tab.M),ylab=\"%\",main=\"Male Admission\",col=c(\"skyblue\",\"hotpink\"))\n```\n\n::: {.cell-output-display}\n![](과제5_files/figure-html/unnamed-chunk-7-5.png){width=672}\n:::\n\n```{.r .cell-code}\nTab.M=cbind(Tab.M,apply(Tab.M,1,sum))\nTab.M=rbind(Tab.M,apply(Tab.M,2,sum))\nTab.M[1,7]/Tab.M[3,7] #전체합격률\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.4451877\n```\n:::\n\n```{.r .cell-code}\nTab.M=rbind(Tab.M,round((Tab.M[1,]/Tab.M[3,])*100,2)) # 마지막줄 과별 합격률 %\nTab.M\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n              A      B      C      D      E     F        \nAdmitted 512.00 353.00 120.00 138.00  53.00  22.0 1198.00\nRejected 313.00 207.00 205.00 279.00 138.00 351.0 1493.00\n         825.00 560.00 325.00 417.00 191.00 373.0 2691.00\n          62.06  63.04  36.92  33.09  27.75   5.9   44.52\n```\n:::\n\n```{.r .cell-code}\n(Tab.F=matrix(Tab.F,byrow=F,ncol=6))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n     [,1] [,2] [,3] [,4] [,5] [,6]\n[1,]   89   17  202  131   94   24\n[2,]   19    8  391  244  299  317\n```\n:::\n\n```{.r .cell-code}\ncolnames(Tab.F)=c(LETTERS[1:6])\nrownames(Tab.F)=c(\"Admitted\",\"Rejected\")\nTab.F\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n          A  B   C   D   E   F\nAdmitted 89 17 202 131  94  24\nRejected 19  8 391 244 299 317\n```\n:::\n\n```{.r .cell-code}\np.Tab.F=prop.table(Tab.F,2)\nbarplot(p.Tab.F*100,legend=rownames(Tab.F),ylab=\"%\",main=\"Female Admission\",col=c(\"skyblue\",\"hotpink\"))\n```\n\n::: {.cell-output-display}\n![](과제5_files/figure-html/unnamed-chunk-7-6.png){width=672}\n:::\n\n```{.r .cell-code}\nTab.F=cbind(Tab.F,apply(Tab.F,1,sum))\nTab.F=rbind(Tab.F,apply(Tab.F,2,sum))\nTab.F[1,7]/Tab.F[3,7] #전체합격률\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.3035422\n```\n:::\n\n```{.r .cell-code}\nTab.F=rbind(Tab.F,round((Tab.F[1,]/Tab.F[3,])*100,2)) # 마지막줄 과별 합격률 %\nTab.F\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n              A  B      C      D      E      F        \nAdmitted  89.00 17 202.00 131.00  94.00  24.00  557.00\nRejected  19.00  8 391.00 244.00 299.00 317.00 1278.00\n         108.00 25 593.00 375.00 393.00 341.00 1835.00\n          82.41 68  34.06  34.93  23.92   7.04   30.35\n```\n:::\n\n```{.r .cell-code}\n#전체 합격률에서는 남자가 높은 것이 확인되어지지만, 학과별로 보았을 때에는 여자의 합격률이 다소 높은 것이 확인되어 진다.\n#심프슨의 역설\n# 각 부분에 대한 평균이 크다고 해서 전체에 대한 평균까지 크지는 않다는 의미이다. 영국의 통계학자 에드워드 심슨이 정리한 역설로(심프슨의 역설이라고도 한다) 각각의 변수에 신경 쓰지 않고 전체 통계 결과를 유추하다 일어나는 오류이다.\n# 계량경제학에서 자주 사용되는 개념인 내생성!\n\n# 모자이크 플롯\nmosaicplot(~Dept+Gender,data=adm,color=ghibli_palettes$MononokeLight[2:3], main=\"Dept, Gender\")\n```\n\n::: {.cell-output-display}\n![](과제5_files/figure-html/unnamed-chunk-7-7.png){width=672}\n:::\n\n```{.r .cell-code}\nmosaicplot(~Gender+Dept,data=adm,color=ghibli_palettes$MononokeLight[2:3], main=\"Gender, Dept\")\n```\n\n::: {.cell-output-display}\n![](과제5_files/figure-html/unnamed-chunk-7-8.png){width=672}\n:::\n\n```{.r .cell-code}\n# 성비가 학과별로 유의미하게 다른 것이 확인되어 진다.\n\n# 모자이크 플롯\nmosaicplot(~Dept+Admit,data=adm[,1,],color=ghibli_palettes$MononokeLight[2:3], main=\"Male, Admit~Dept\")\n```\n\n::: {.cell-output-display}\n![](과제5_files/figure-html/unnamed-chunk-7-9.png){width=672}\n:::\n\n```{.r .cell-code}\nmosaicplot(~Dept+Admit,data=adm[,2,],color=ghibli_palettes$MononokeLight[2:3], main=\"Female, Admit~Dept\")\n```\n\n::: {.cell-output-display}\n![](과제5_files/figure-html/unnamed-chunk-7-10.png){width=672}\n:::\n\n```{.r .cell-code}\n# 학과별로 합격률이 매우 다르다. A에서 F로 갈 수록 합격률이 급격하게 감소하고 있는 것이 확인되어진다.\n\n# 모자이크 플롯\nmosaicplot(~Dept+Admit+Gender,data=adm,color=ghibli_palettes$MononokeLight[1:2], main=\"Admit, Dept, Gender\")\n```\n\n::: {.cell-output-display}\n![](과제5_files/figure-html/unnamed-chunk-7-11.png){width=672}\n:::\n\n```{.r .cell-code}\n# 학과 내에서는 성별로 합격률 차이가 거의 나지 않는다.\nmosaicplot(~Admit+Gender,data=adm,color=ghibli_palettes$MononokeLight[1:2], main=\"Admit,Gender\")\n```\n\n::: {.cell-output-display}\n![](과제5_files/figure-html/unnamed-chunk-7-12.png){width=672}\n:::\n\n```{.r .cell-code}\n# 그럼에도 불구하고 합격여부에 관해서 성 차이가 있는 것처럼 착시현상을 보인다.\n# 이러한 착시현상이 발생하는 이유는 여성들의 이공계 기피에 의해 발생한다. (각 학과별로는 그렇지 않은데 전체로는 합격률이 낮은 것 처럼 보임)\n```\n:::\n\n\n## 심프슨 역설의 예시\n\n1.  미국 중위소득의 감소 https://economix.blogs.nytimes.com/2013/05/01/can-every-group-be-worse-than-average-yes/ 2000년 이래로 미국의 중위소득은 인플레이션을 고려하더라도 1%만큼 증가한 것이 확인된다. 그러나, 고등학교 중퇴자 집단, 고등학교 졸업자 집단, 전문대학 졸업자 집단 그리고 4년제 대학 졸업자 및 대학원 졸업자 집단의 소득은 모두 감소하였다. (모든 교육 하위집단에서 중위소득은 2000년도보다 낮은 수준으로 확인되어진다.) 그러한 요인이 발생한 이유는 교육수준에 따른 하위집단에 속하는 인구 비율이 달라졌기 때문이다. (2000년 이래로 13년동안 대학교 졸업자수는 더 낮은 교육을 받은 사람들에 비해서 더 많이 증가했지만, 그들의 임금은 종합적으로 보았을 때 1.2%정도 훨씬 더 천천히 감소하였기 때문이다. ) 전체적인 관점에서는 임금이 증가하였다는 결론을 낼 수 있지만, 개인의 관점에서는 임금이 오히려 감소하였다고 보는 것이 가능하다.\n\n2.  벨기에의 COVID-19 사망률 (성별, 나이)\n\nhttps://link.springer.com/article/10.1007/s11192-020-03830-w https://www.medrxiv.org/content/10.1101/2020.06.20.20136234v2\n\n\n::: {.cell}\n\n```{.r .cell-code}\nbelgium=matrix(c(0,0,0.02,0.01,0.29,0.14,2.92,1.61,5.56,3.35,13.20,11.07,1.18,1.31),byrow=T,ncol=2)\nbel=array(belgium,c(7,2),dimnames=list(age=c(\"0~24\",\"25~44\",\"45~64\",\"65~74\",\"75~84\",\"85 and older\",\"All Ages\"),gender=c(\"Male\",\"Female\")))\nbel\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n              gender\nage             Male Female\n  0~24          0.00   0.00\n  25~44         0.02   0.01\n  45~64         0.29   0.14\n  65~74         2.92   1.61\n  75~84         5.56   3.35\n  85 and older 13.20  11.07\n  All Ages      1.18   1.31\n```\n:::\n:::\n\n\nR.R.'s local Flemish newspaper, De Standaard에서 2020년 6월 기사 인용. 모든 나이 Group들에서 남성의 COVID-19 감염 후 사망률이 높게 측정되고 있음에도 불구하고 전체 인구를 고려하였을 때 여성의 COVID-19 감염 후 사망률이 오히려 높게 나타나는 결과로 이어짐. 이러한 결과가 나타나는 인구는 벨기에에서는 남자노인들보다 여자 노인들이 훨신 더 많기 때문임으로 보인다.\n\n3.  Titanic Dataset\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Titanic\ntdf <- as.data.frame(Titanic)\nTita <- tdf[rep(1:nrow(tdf), tdf$Freq), -5]\n\n\nlibrary(reshape2)\nA=dcast(Tita,Class~Survived)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nUsing Survived as value column: use value.var to override.\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nAggregation function missing: defaulting to length\n```\n:::\n\n```{.r .cell-code}\nA$\"prop(%)\"=round(A$Yes/(A$No+A$Yes),4)*100\nA\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  Class  No Yes prop(%)\n1   1st 122 203   62.46\n2   2nd 167 118   41.40\n3   3rd 528 178   25.21\n4  Crew 673 212   23.95\n```\n:::\n\n```{.r .cell-code}\nB=dcast(Tita,Class~Survived+Sex)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nUsing Survived as value column: use value.var to override.\nAggregation function missing: defaulting to length\n```\n:::\n\n```{.r .cell-code}\nB$\"Maleprop(%)\"=round(B$Yes_Male/(B$Yes_Male+B$No_Male),4)*100\nB$\"Femaleprop(%)\"=round(B$Yes_Female/(B$Yes_Female+B$No_Female),4)*100\n\n\nFinal=B[,c(4,2,6,5,3,7)]\nrownames(Final)=A$Class\n\nA;Final\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  Class  No Yes prop(%)\n1   1st 122 203   62.46\n2   2nd 167 118   41.40\n3   3rd 528 178   25.21\n4  Crew 673 212   23.95\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n     Yes_Male No_Male Maleprop(%) Yes_Female No_Female Femaleprop(%)\n1st        62     118       34.44        141         4         97.24\n2nd        25     154       13.97         93        13         87.74\n3rd        88     422       17.25         90       106         45.92\nCrew      192     670       22.27         20         3         86.96\n```\n:::\n\n```{.r .cell-code}\n# 3등석과 선원들 비교 비교\n\nmosaicplot(~Class+Survived,Titanic,color=T,main=\"Class~Survived\")\n```\n\n::: {.cell-output-display}\n![](과제5_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n\n```{.r .cell-code}\nmosaicplot(~Class+Survived+Sex,Titanic,color=T,main=\"Class~Survived Under Sex\")\n```\n\n::: {.cell-output-display}\n![](과제5_files/figure-html/unnamed-chunk-9-2.png){width=672}\n:::\n:::\n\n\n3등석과 선원들의 생존률을 비교해보자. 남성과 여성 모두 선원들이 3등석 승객들에 비해 생존확률이 높았음에도 불구하고 (남성 승객 17.25% \\< 선원 22.27% , 여성 승객 45.92% \\< 선원 86.96%) 성별에 상관없이 모든 데이터를 비교하였을 때 3등석 승객들의 생존확률이 선원들의 생존확률보다 높은 것으로 나타난다. (승객 25.21% \\> 선원 23.95%) 이것의 요인으로는 내생변수 (숨겨진 변수)가 그러한 결과가 나타나는데 영향을 미쳤음을 확인할 수 있다. 3등석의 여성의 비율이 선원의 여성의 비율에 비해서 훨씬 높다는 것을 확인할 수 있다. 3등석 승객들과 선원들의 성비의 차이가 이러한 결과로 이어지게 되었음을 확인할 수 있다.\n\n# 3번\n\n\\[노부모 부양에 대한 태도 자료\\] 1988년 자료 (유인물 첨부 파일) 와 KOSIS 싸이트의 최근 자료를 비교하여 분석하라. KOSIS에서 여러 주제별 통계가 있는 데, 있을 만한 곳을 계속 찾아 들어간다. 나이별 부양책임 주체에 대한 부분만 분석한다.\n\n-   Median Polish와 barplot 병행\n-   two-way plot 과 Coded plot 등 손으로 그려야 하는 부분은 오려 붙여 제출한다. 제출하고, YSCEC에 올리는 파일에는 이 부분이 빠져 있어도 된다.\n\n## (1) 1988년 과 최근 자료를 각각 분석한다.\n\n## (2) 1988년 자료와 KOSIS 최근 자료의 범주가 약간 다른 점에 주의하면서 이들의 시간차(약 30여년)에 따른 태도의 변화를 서로 비교하여 분석한다.\n\n\n::: {.cell}\n\n```{.r .cell-code}\npop1988=matrix(c(16.4,14.5,0.8,44.4,17.4,6.5,16.8,16.3,0.4,43.5,17.1,5.9,19.5,17.6,0.4,38.9,18.5,5.1,29.0,18.8,0.5,31.1,16.4,4.2,36.6,21.2,0.3,25.6,12.6,3.7,48.1,20.2,0.4,19.8,8.1,3.4),byrow=T,ncol=6)\npop1988=as.data.frame(pop1988)\ncolnames(pop1988)=c(\"장남\",\"아들모두\",\"딸\",\"아들딸모두\",\"자립\",\"사회및기타\")\nrownames(pop1988)=c(\"15~19세\",\"20~29세\",\"30~39세\",\"40~49세\",\"50~59세\",\"60세이상\")\npop1988\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n         장남 아들모두  딸 아들딸모두 자립 사회및기타\n15~19세  16.4     14.5 0.8       44.4 17.4        6.5\n20~29세  16.8     16.3 0.4       43.5 17.1        5.9\n30~39세  19.5     17.6 0.4       38.9 18.5        5.1\n40~49세  29.0     18.8 0.5       31.1 16.4        4.2\n50~59세  36.6     21.2 0.3       25.6 12.6        3.7\n60세이상 48.1     20.2 0.4       19.8  8.1        3.4\n```\n:::\n\n```{.r .cell-code}\npop2018=data.frame(\n  stringsAsFactors = FALSE,\n                연령 = c(\"13∼19세\",\"20∼29세\",\"30∼39세\",\n                       \"40∼49세\",\"50∼59세\",\"60세이상\"),\n                자립 = c(17.5, 19.2, 17.3, 16.9, 17.8, 25),\n                장남 = c(0.6, 0.6, 0.8, 1.1, 1.3, 2.9),\n              아들모두 = c(1.2, 0.7, 0.9, 0.8, 0.8, 1.6),\n                 딸 = c(0.4, 0.3, 0.2, 0.2, 0.2, 0.4),\n             모든_자녀 = c(26.4, 21, 19.1, 18, 17.6, 17.4),\n                능력 = c(3.9, 4.7, 4.6, 4.4, 4.7, 6),\n            가족정부사회 = c(45.8, 49.5, 52.4, 53.1, 51.7, 38.8),\n              정부사회 = c(4.2, 4, 4.7, 5.5, 5.9, 7.9)\n)\nrownames(pop2018)=pop2018$연령\npop2018=pop2018[,c(2:9)]\n\n\npop2020=data.frame(\n  stringsAsFactors = FALSE,\n                        연령 = c(\"15∼19세\",\n                               \"20∼29세\",\"30∼39세\",\"40∼49세\",\"50∼59세\",\"60세이상\",\n                               \"65세이상\"),\n            부모_스스로 = c(11.1, 11.6, 14.4, 11, 10.7, 16, 17),\n                가족 = c(27.2, 21.8, 19.4, 19.4, 19.2, 26, 27.3),\n        가족정부사회가_함께 = c(58.9, 64.4, 63.7, 66.5, 66.5, 52.8, 49.9),\n             정부_사회 = c(2.7, 2.2, 2.5, 3.1, 3.6, 5.2, 5.8),\n                기타 = c(0.1, 0, 0, 0, 0, 0, 0)\n        )\nrownames(pop2020)=c(pop2020$연령)\npop2020=pop2020[,c(2:6)]\n\n\n\n\npop1988; pop2018; pop2020 #2010년도 데이터부터 65세 이상 데이터가 추가됨\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n         장남 아들모두  딸 아들딸모두 자립 사회및기타\n15~19세  16.4     14.5 0.8       44.4 17.4        6.5\n20~29세  16.8     16.3 0.4       43.5 17.1        5.9\n30~39세  19.5     17.6 0.4       38.9 18.5        5.1\n40~49세  29.0     18.8 0.5       31.1 16.4        4.2\n50~59세  36.6     21.2 0.3       25.6 12.6        3.7\n60세이상 48.1     20.2 0.4       19.8  8.1        3.4\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n         자립 장남 아들모두  딸 모든_자녀 능력 가족정부사회 정부사회\n13∼19세 17.5  0.6      1.2 0.4      26.4  3.9         45.8      4.2\n20∼29세 19.2  0.6      0.7 0.3      21.0  4.7         49.5      4.0\n30∼39세 17.3  0.8      0.9 0.2      19.1  4.6         52.4      4.7\n40∼49세 16.9  1.1      0.8 0.2      18.0  4.4         53.1      5.5\n50∼59세 17.8  1.3      0.8 0.2      17.6  4.7         51.7      5.9\n60세이상 25.0  2.9      1.6 0.4      17.4  6.0         38.8      7.9\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n         부모_스스로 가족 가족정부사회가_함께 정부_사회 기타\n15∼19세        11.1 27.2                58.9       2.7  0.1\n20∼29세        11.6 21.8                64.4       2.2  0.0\n30∼39세        14.4 19.4                63.7       2.5  0.0\n40∼49세        11.0 19.4                66.5       3.1  0.0\n50∼59세        10.7 19.2                66.5       3.6  0.0\n60세이상        16.0 26.0                52.8       5.2  0.0\n65세이상        17.0 27.3                49.9       5.8  0.0\n```\n:::\n\n```{.r .cell-code}\n# 2020년도의 경우 가족 형태가 바뀌면서 노인 부양을 담당하는 주체가 변경되어 column name들이 변경되어진 것으로 보인다.\n```\n:::\n\n\n총 세개 시점의 데이터가 존재한다. 만약 그 데이터들이 가법적 모형을 따를경우 다음과 같은 모형으로 표현할 수 있을 것이다. y_ijk=μk+α_ik+β_jk+e_ijk ,e_ijk\\~(0,σ),i=(1,...,6) (row effect),j=(1,...,5 or 6 or 8)(column effect), k=(1,2,3) (Time)을 고려한다. 1988데이터는 row \\* col = 6*6 2010데이터는 row* col = 6*8 2020데이터는 row* col = 6\\*5 개의 효과를 가짐\n\n\n::: {.cell}\n\n```{.r .cell-code}\npop1988_polished=medpolish(pop1988)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n1: 155.4\n2: 144.8\nFinal: 144.8\n```\n:::\n\n```{.r .cell-code}\npop1988_polished\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nMedian Polish Results (Dataset: \"pop1988\")\n\nOverall: 17.45\n\nRow Effects:\n 15~19세  20~29세  30~39세  40~49세  50~59세 60세이상 \n   0.525    0.175    0.125   -0.125   -0.625   -0.725 \n\nColumn Effects:\n      장남   아들모두         딸 아들딸모두       자립 사회및기타 \n      6.80       0.75     -17.00      17.55      -0.75     -12.80 \n\nResiduals:\n           장남 아들모두     딸 아들딸모두   자립 사회및기타\n15~19세  -8.375   -4.225 -0.175      8.875  0.175      1.325\n20~29세  -7.625   -2.075 -0.225      8.325  0.225      1.075\n30~39세  -4.875   -0.725 -0.175      3.775  1.675      0.325\n40~49세   4.875    0.725  0.175     -3.775 -0.175     -0.325\n50~59세  12.975    3.625  0.475     -8.775 -3.475     -0.325\n60세이상 24.575    2.725  0.675    -14.475 -7.875     -0.525\n```\n:::\n\n```{.r .cell-code}\npop2018_polished=medpolish(pop2018)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n1: 63.8\n2: 58.5\nFinal: 58.4\n```\n:::\n\n```{.r .cell-code}\npop2018_polished$residuals=round(pop2018_polished$residuals,5)\npop2018_polished$col=round(pop2018_polished$col,5)\npop2018_polished$row=round(pop2018_polished$row,5)\npop2018_polished\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nMedian Polish Results (Dataset: \"pop2018\")\n\nOverall: 4.85\n\nRow Effects:\n13∼19세 20∼29세 30∼39세 40∼49세 50∼59세 60세이상 \n-0.36250  0.00000  0.00000  0.00000  0.06875  1.11250 \n\nColumn Effects:\n        자립         장남     아들모두           딸    모든_자녀         능력 \n    12.94688     -3.81875     -4.08438     -4.65000     13.70000     -0.23438 \n가족정부사회     정부사회 \n    45.71562      0.25000 \n\nResiduals:\n             자립     장남 아들모두       딸 모든_자녀     능력 가족정부사회\n13∼19세  0.06562 -0.06875  0.79688  0.56250    8.2125 -0.35312      -4.4031\n20∼29세  1.40312 -0.43125 -0.06562  0.10000    2.4500  0.08438      -1.0656\n30∼39세 -0.49687 -0.23125  0.13438  0.00000    0.5500 -0.01562       1.8344\n40∼49세 -0.89688  0.06875  0.03438  0.00000   -0.5500 -0.21562       2.5344\n50∼59세 -0.06562  0.20000 -0.03438 -0.06875   -1.0188  0.01562       1.0656\n60세이상  6.09063  0.75625 -0.27812 -0.91250   -2.2625  0.27187     -12.8781\n         정부사회\n13∼19세 -0.53750\n20∼29세 -1.10000\n30∼39세 -0.40000\n40∼49세  0.40000\n50∼59세  0.73125\n60세이상  1.68750\n```\n:::\n\n```{.r .cell-code}\npop2020_polished=medpolish(pop2020)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n1: 86.5\n2: 76\nFinal: 76\n```\n:::\n\n```{.r .cell-code}\npop2020_polished$residuals=round(pop2020_polished$residuals,5)\npop2020_polished$col=round(pop2020_polished$col,5)\npop2020_polished$row=round(pop2020_polished$row,5)\npop2020_polished\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nMedian Polish Results (Dataset: \"pop2020\")\n\nOverall: 11.7\n\nRow Effects:\n15∼19세 20∼29세 30∼39세 40∼49세 50∼59세 60세이상 65세이상 \n     0.0     -0.1      0.2     -0.1     -0.1      2.9      3.5 \n\nColumn Effects:\n        부모_스스로                가족 가족정부사회가_함께           정부_사회 \n                0.0                10.2                51.8                -9.4 \n               기타 \n              -11.6 \n\nResiduals:\n         부모_스스로 가족 가족정부사회가_함께 정부_사회 기타\n15∼19세        -0.6  5.3                -4.6       0.4  0.0\n20∼29세         0.0  0.0                 1.0       0.0  0.0\n30∼39세         2.5 -2.7                 0.0       0.0 -0.3\n40∼49세        -0.6 -2.4                 3.1       0.9  0.0\n50∼59세        -0.9 -2.6                 3.1       1.4  0.0\n60세이상         1.4  1.2               -13.6       0.0 -3.0\n65세이상         1.8  1.9               -17.1       0.0 -3.6\n```\n:::\n:::\n\n\nMedian Polish의 시행과 이후 Tukey Additivity Plot & 잔차 분석\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 1988년\nplot(pop1988_polished)\nabline(0,1,col=\"red\",lty=2) #직선이 경향성을 정확히 보인다고 보기 어렵다.\nabline(lm(as.vector(pop1988_polished$residuals) ~ \n            as.vector(outer(pop1988_polished$row,pop1988_polished$col, \"*\")/pop1988_polished$overall)),col=\"orange\",lty=2)\n```\n\n::: {.cell-output-display}\n![](과제5_files/figure-html/unnamed-chunk-12-1.png){width=70%}\n:::\n\n```{.r .cell-code}\nlm(as.vector(pop1988_polished$residuals) ~ \n     as.vector(outer(pop1988_polished$row,pop1988_polished$col, \"*\")/pop1988_polished$overall))[1]\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n$coefficients\n                                                                               (Intercept) \n                                                                                 0.2173017 \nas.vector(outer(pop1988_polished$row, pop1988_polished$col, \"*\")/pop1988_polished$overall) \n                                                                                 2.8429224 \n```\n:::\n\n```{.r .cell-code}\n# 회귀 직선의 기울기가 2.8429224 이므로 1과 같다고 보기 어렵다.  따라서 로그 변환을 해서는 안된다.\n\n# 잔차의 Boxplot을 통해서 분석할 경우 \nboxplot(pop1988_polished$residuals) #Outlier는 보이지 않았다. 따라서 제거할 값은 보이지 않는다.\n```\n\n::: {.cell-output-display}\n![](과제5_files/figure-html/unnamed-chunk-12-2.png){width=70%}\n:::\n\n```{.r .cell-code}\n# 행 효과 크기 순으로 재정렬한 잔차표\nround(pop1988_polished$residuals[order(pop1988_polished$row),],1) \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n         장남 아들모두   딸 아들딸모두 자립 사회및기타\n60세이상 24.6      2.7  0.7      -14.5 -7.9       -0.5\n50~59세  13.0      3.6  0.5       -8.8 -3.5       -0.3\n40~49세   4.9      0.7  0.2       -3.8 -0.2       -0.3\n30~39세  -4.9     -0.7 -0.2        3.8  1.7        0.3\n20~29세  -7.6     -2.1 -0.2        8.3  0.2        1.1\n15~19세  -8.4     -4.2 -0.2        8.9  0.2        1.3\n```\n:::\n\n```{.r .cell-code}\n# 나이가 많을수록 아들, 특히 장남이 부모님을 부양하고자 하는 경우가 많다. (60세이상의 집단의 잔차 24.6)\n# 나이가 적을수록 모든 자녀(아들,딸)이 부모님 부양을 분담하고자 하는 경향성이 나타난다.\n\n# Check Decomposition\ndecomposed_88=(pop1988_polished$overall + outer(pop1988_polished$row,pop1988_polished$col, \"+\") + pop1988_polished$residuals)\nall(round(decomposed_88,3)==pop1988)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] TRUE\n```\n:::\n\n```{.r .cell-code}\n# 가법성 모형이 확인되어지고 있다.\n# Comparison Values\nround(outer(pop1988_polished$row,pop1988_polished$col, \"*\")/pop1988_polished$overall,2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n          장남 아들모두    딸 아들딸모두  자립 사회및기타\n15~19세   0.20     0.02 -0.51       0.53 -0.02      -0.39\n20~29세   0.07     0.01 -0.17       0.18 -0.01      -0.13\n30~39세   0.05     0.01 -0.12       0.13 -0.01      -0.09\n40~49세  -0.05    -0.01  0.12      -0.13  0.01       0.09\n50~59세  -0.24    -0.03  0.61      -0.63  0.03       0.46\n60세이상 -0.28    -0.03  0.71      -0.73  0.03       0.53\n```\n:::\n\n```{.r .cell-code}\n# Comparison value 기준으로 0 값이 확인되지는 않는다. 그러나 대다수는 0근처에 존재하고 있으므로 Fitting에서 많이 벗어나지 않았다.\n\nstem(pop1988_polished$residuals) # Gap이 있는 것을 제외하고는 전체적으로 대칭적으로 보인다.\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  The decimal point is 1 digit(s) to the right of the |\n\n  -1 | 4\n  -0 | 98885\n  -0 | 443211000000\n   0 | 0000011112344\n   0 | 589\n   1 | 3\n   1 | \n   2 | \n   2 | 5\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# 2018년\nplot(pop2018_polished) \nabline(0,1,col=\"red\",lty=2) #직선이 경향성을 정확히 보인다고 보기 어렵다.\nabline(lm(as.vector(pop2018_polished$residuals) ~ \n            as.vector(outer(pop2018_polished$row,pop2018_polished$col, \"*\")/pop2018_polished$overall)),col=\"orange\",lty=2)\n```\n\n::: {.cell-output-display}\n![](과제5_files/figure-html/unnamed-chunk-13-1.png){width=70%}\n:::\n\n```{.r .cell-code}\nlm(as.vector(pop2018_polished$residuals) ~ \n     as.vector(outer(pop2018_polished$row,pop2018_polished$col, \"*\")/pop2018_polished$overall))[1]\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n$coefficients\n                                                                               (Intercept) \n                                                                                 0.2056009 \nas.vector(outer(pop2018_polished$row, pop2018_polished$col, \"*\")/pop2018_polished$overall) \n                                                                                -0.8088495 \n```\n:::\n\n```{.r .cell-code}\n# 회귀 직선의 기울기가  -0.8088495 이므로 1과 같다고 보기 어렵다. 따라서 로그 변환을 해서는 안된다.\n\n# 잔차의 Boxplot을 통해서 분석할 경우 \n\nboxplot(pop2018_polished$residuals) #Residual들의 Outlier가 확인되어진다 (5개). 만약 제거된다면 Additivity plot이 어떻게 변할까?\n```\n\n::: {.cell-output-display}\n![](과제5_files/figure-html/unnamed-chunk-13-2.png){width=70%}\n:::\n\n```{.r .cell-code}\npop2018_polished2=pop2018_polished\npop2018_polished2$residuals[,1][6]=mean(pop2018_polished$residuals[,1])\npop2018_polished2$residuals[,3][1]=mean(pop2018_polished$residuals[,3])\npop2018_polished2$residuals[,5][1]=mean(pop2018_polished$residuals[,5])\nboxplot(pop2018_polished2$residuals)\n```\n\n::: {.cell-output-display}\n![](과제5_files/figure-html/unnamed-chunk-13-3.png){width=70%}\n:::\n\n```{.r .cell-code}\nplot(pop2018_polished2)  # 경향성이 크게 바뀌지 않기 때문에 Raw Data 사용\n```\n\n::: {.cell-output-display}\n![](과제5_files/figure-html/unnamed-chunk-13-4.png){width=70%}\n:::\n\n```{.r .cell-code}\n# 행 효과 크기 순으로 재정렬한 잔차표\nround(pop2018_polished$residuals[order(pop2018_polished$row),],1) \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n         자립 장남 아들모두   딸 모든_자녀 능력 가족정부사회 정부사회\n13∼19세  0.1 -0.1      0.8  0.6       8.2 -0.4         -4.4     -0.5\n20∼29세  1.4 -0.4     -0.1  0.1       2.5  0.1         -1.1     -1.1\n30∼39세 -0.5 -0.2      0.1  0.0       0.6  0.0          1.8     -0.4\n40∼49세 -0.9  0.1      0.0  0.0      -0.6 -0.2          2.5      0.4\n50∼59세 -0.1  0.2      0.0 -0.1      -1.0  0.0          1.1      0.7\n60세이상  6.1  0.8     -0.3 -0.9      -2.3  0.3        -12.9      1.7\n```\n:::\n\n```{.r .cell-code}\n# 나이에 따른 경향성이 거의 나타나지 않는 것으로 보인다. \n\n# Check Decomposition\ndecomposed_18=(pop2018_polished$overall + outer(pop2018_polished$row,pop2018_polished$col, \"+\") + pop2018_polished$residuals)\nall(round(decomposed_18,2)==pop2018)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] TRUE\n```\n:::\n\n```{.r .cell-code}\n# 가법성 모형이 확인되어지고 있다.\n\n# Comparison Values\nround(outer(pop2018_polished$row,pop2018_polished$col, \"*\")/pop2018_polished$overall,2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n          자립  장남 아들모두    딸 모든_자녀  능력 가족정부사회 정부사회\n13∼19세 -0.97  0.29     0.31  0.35     -1.02  0.02        -3.42    -0.02\n20∼29세  0.00  0.00     0.00  0.00      0.00  0.00         0.00     0.00\n30∼39세  0.00  0.00     0.00  0.00      0.00  0.00         0.00     0.00\n40∼49세  0.00  0.00     0.00  0.00      0.00  0.00         0.00     0.00\n50∼59세  0.18 -0.05    -0.06 -0.07      0.19  0.00         0.65     0.00\n60세이상  2.97 -0.88    -0.94 -1.07      3.14 -0.05        10.49     0.06\n```\n:::\n\n```{.r .cell-code}\n# Comparison value 기준으로 23개의 0이 발견됨. 대다수의 값들이 0근처에 존재하고 있으므로 Fitting에서 많이 벗어나지 않았다. \n\nstem(pop2018_polished$residuals) # Gap이 있는데 이건 Boxplot을 통해 확인된 outlier들을 재확인해준다.\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  The decimal point is at the |\n\n  -12 | 9\n  -10 | \n   -8 | \n   -6 | \n   -4 | 4\n   -2 | 3\n   -0 | 11099655444322111100\n    0 | 000011111234667881478\n    2 | 55\n    4 | \n    6 | 1\n    8 | 2\n```\n:::\n\n```{.r .cell-code}\n# 대다수의 값들이 0 근처에 몰려있다. \n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# 2020년\nplot(pop2020_polished) \nabline(0,1,col=\"red\",lty=2) #직선이 경향성을 정확히 보인다고 보기 어렵다.\nabline(lm(as.vector(pop2020_polished$residuals) ~ \n            as.vector(outer(pop2020_polished$row,pop2020_polished$col, \"*\")/pop2020_polished$overall)),col=\"orange\",lty=2)\n```\n\n::: {.cell-output-display}\n![](과제5_files/figure-html/unnamed-chunk-14-1.png){width=70%}\n:::\n\n```{.r .cell-code}\nlm(as.vector(pop2020_polished$residuals) ~ \n     as.vector(outer(pop2020_polished$row,pop2020_polished$col, \"*\")/pop2020_polished$overall))[1]\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n$coefficients\n                                                                               (Intercept) \n                                                                                -0.2362669 \nas.vector(outer(pop2020_polished$row, pop2020_polished$col, \"*\")/pop2020_polished$overall) \n                                                                                -0.8937232 \n```\n:::\n\n```{.r .cell-code}\n# 회귀 직선의 기울기가 -0.9335803 이므로 1과 같다고 보기 어렵다. 따라서 로그 변환을 해서는 안된다.\n\n# Boxplot으로 Outlier Check\nboxplot(pop2020_polished$residuals)  #Outlier는 보이지 않았다. 따라서 제거할 값은 보이지 않는다.\n```\n\n::: {.cell-output-display}\n![](과제5_files/figure-html/unnamed-chunk-14-2.png){width=70%}\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n# 행 효과 크기 순으로 재정렬한 잔차표\nround(pop2020_polished$residuals[order(pop2020_polished$row),],1) \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n         부모_스스로 가족 가족정부사회가_함께 정부_사회 기타\n20∼29세         0.0  0.0                 1.0       0.0  0.0\n40∼49세        -0.6 -2.4                 3.1       0.9  0.0\n50∼59세        -0.9 -2.6                 3.1       1.4  0.0\n15∼19세        -0.6  5.3                -4.6       0.4  0.0\n30∼39세         2.5 -2.7                 0.0       0.0 -0.3\n60세이상         1.4  1.2               -13.6       0.0 -3.0\n65세이상         1.8  1.9               -17.1       0.0 -3.6\n```\n:::\n:::\n\n\n60세 이상 집단과 30\\~39세 집단에서는 본인 스스로 부모님을 부양해야 한다고 생각하고 있는 것으로 보인다. 60대 집단의 경우 정부 사회 등 외부에 의존하기보다는 본인이 직접 노후 대비를 해야한다는 인식이 있는 것으로 보인다. 1988년 조사에서 노인 집단에서 장남이 부모 부양을 담당해야 한다고 생각했던 것에서 변화한 것으로 보인다. 반면 40대 50대는 가족정부사회와 함께 부모를 부양해야 한다는 인식이 많다. (본인이 직접 본인 부모의 노후 대비를 담당해야하는 상황이기 때문에 이러한 경향성이 나타나는 것으로 예측된다.)\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Check Decomposition\ndecomposed_20=(pop2020_polished$overall + outer(pop2020_polished$row,pop2020_polished$col, \"+\") + pop2020_polished$residuals)\nall(round(decomposed_20,1)==pop2020)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] TRUE\n```\n:::\n\n```{.r .cell-code}\n# 가법성 모형이 확인되어지고 있다.\n\n# Comparison Values\nround(outer(pop2020_polished$row,pop2020_polished$col, \"*\")/pop2020_polished$overall,2)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n         부모_스스로  가족 가족정부사회가_함께 정부_사회  기타\n15∼19세           0  0.00                0.00      0.00  0.00\n20∼29세           0 -0.09               -0.44      0.08  0.10\n30∼39세           0  0.17                0.89     -0.16 -0.20\n40∼49세           0 -0.09               -0.44      0.08  0.10\n50∼59세           0 -0.09               -0.44      0.08  0.10\n60세이상           0  2.53               12.84     -2.33 -2.88\n65세이상           0  3.05               15.50     -2.81 -3.47\n```\n:::\n\n```{.r .cell-code}\n# Comparison value 기준으로 0값이 총 5개 확인됨. \n# 대다수의 값들이 Additivity Plot의 x축과 y축 근처에 존재하는 것으로 보아 몇몇 피팅에서 벗어난 값을 제외하면 대부분 0근처에서 존재하고 있는 것이 확인된다. \n\nstem(pop2020_polished$residuals) \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  The decimal point is at the |\n\n  -16 | 1\n  -14 | \n  -12 | 6\n  -10 | \n   -8 | \n   -6 | \n   -4 | 6\n   -2 | 60764\n   -0 | 9663\n    0 | 0000000000049024489\n    2 | 511\n    4 | 3\n```\n:::\n\n```{.r .cell-code}\n# Gap이 있음에도 Boxplot 상으로는 Outlier는 보이지 않았다. 3~4개 값을 제외 하면 잔차들이 0근처에 잘 모여있는 것이 확인된다.\n\n#log 변환해서 경향성이 있는지 확인하기 (어느정도 y=x 경향성을 따르는 것이 아닐까?)\npop20202=pop2020\npop20202$기타=ifelse(pop20202$기타==0,0.1,pop20202$기타) # 책에서 사용하던 기법 활용 (log0은 존재하지 않기에)\nk=medpolish(log(pop20202))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n1: 5.073833\n2: 4.168534\nFinal: 4.168534\n```\n:::\n\n```{.r .cell-code}\nplot(k) \n```\n\n::: {.cell-output-display}\n![](과제5_files/figure-html/unnamed-chunk-16-1.png){width=70%}\n:::\n\n```{.r .cell-code}\nstem(k$residuals) #Gap이 줄어들은 것은 사실이지만 아직도 존재함 & 변환이전이후 둘다 대칭성은 차이 없음\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  The decimal point is 1 digit(s) to the left of the |\n\n  -5 | 3\n  -4 | 30\n  -3 | \n  -2 | 974\n  -1 | 5\n  -0 | 8653\n   0 | 000000000001445689\n   1 | 00\n   2 | 228\n   3 | 3\n```\n:::\n\n```{.r .cell-code}\nboxplot(k$residuals) #원래 Oulier가 없었는데 변환이후 생기게 됨 \n```\n\n::: {.cell-output-display}\n![](과제5_files/figure-html/unnamed-chunk-16-2.png){width=70%}\n:::\n\n```{.r .cell-code}\n# 따라서 로그 변환을 하지 않고 원래 자료를 기준으로 그대로 분석할 예정임. \n```\n:::\n\n\nRaw Data를 활용하여 연도별 Column Effect(부양책임)와 Row Effect(나이)를 시각화해보고자 한다.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 1988\n# Row Effect \nbarplot(pop1988_polished$row, ylim=c(-1,1), main=\"나이_1988년\")\n```\n\n::: {.cell-output-display}\n![](과제5_files/figure-html/unnamed-chunk-17-1.png){width=70%}\n:::\n\n```{.r .cell-code}\npop1988_polished$row\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n 15~19세  20~29세  30~39세  40~49세  50~59세 60세이상 \n   0.525    0.175    0.125   -0.125   -0.625   -0.725 \n```\n:::\n\n```{.r .cell-code}\n# Column Effect\nbarplot(pop1988_polished$col, ylim=c(-20,20), main=\"부양유형_1988년\")\n```\n\n::: {.cell-output-display}\n![](과제5_files/figure-html/unnamed-chunk-17-2.png){width=70%}\n:::\n\n```{.r .cell-code}\npop1988_polished$col\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n      장남   아들모두         딸 아들딸모두       자립 사회및기타 \n      6.80       0.75     -17.00      17.55      -0.75     -12.80 \n```\n:::\n:::\n\n\nRow 젊은 사람들일 수록 부모님을 부양하는 것을 부담스럽지 않게 여기다가 나이를 먹음에 따라 직접 부담을 지게되면서 어려움을 느끼거나 타인에게 부양을 요구하는 것을 부담스럽게 여기는 것으로 보인다.\n\nColumn 1988년도에도 장남 또는 맏며느리인 경우 딸 또는 사위일 때에 비해 부모님 부양에 대해서 긍정적인 태도를 보였던 것으로 보인다.모든 자녀,아들과 딸이 그러한 부담을 분담하고자 하는 인식이 가장 많았다는 점에서 1988년에도 부모님 부양을 한 집안에서 책임지는 것은 쉽지 않았다는 것을 확인할 수 있다.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 2018\n# Row Effect \nbarplot(pop2018_polished$row, ylim=c(-0.5,1.5), main=\"나이_2018년\")\n```\n\n::: {.cell-output-display}\n![](과제5_files/figure-html/unnamed-chunk-18-1.png){width=70%}\n:::\n\n```{.r .cell-code}\npop2018_polished$row\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n13∼19세 20∼29세 30∼39세 40∼49세 50∼59세 60세이상 \n-0.36250  0.00000  0.00000  0.00000  0.06875  1.11250 \n```\n:::\n\n```{.r .cell-code}\n# Column Effect\nbarplot(pop2018_polished$col, ylim=c(-10,50), main=\"부양유형_2018년\")\n```\n\n::: {.cell-output-display}\n![](과제5_files/figure-html/unnamed-chunk-18-2.png){width=70%}\n:::\n\n```{.r .cell-code}\npop2018_polished$col\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n        자립         장남     아들모두           딸    모든_자녀         능력 \n    12.94688     -3.81875     -4.08438     -4.65000     13.70000     -0.23438 \n가족정부사회     정부사회 \n    45.71562      0.25000 \n```\n:::\n:::\n\n\nRow 1988년도와는 달리 2018년에는 15\\~19세의 경우 모든 연령대중에서 부모님 부양에 대한 인식이 가장 좋지 못한 것으로 확인된다. 나머지 나이대에서는 60대를 제외 하면 나이에 따른 인식에 대한 영향이 크게 나타나지 않는 것으로 보인다. 직접적으로 부양을 받는 세대인 은퇴를 앞둔 60대의 입장에서는 본인의 은퇴이후의 삶에 대한 고민이 반영되었기 때문에 부모부양에 대한 강한 인식을 보이고 있지만, 이외의 세대에서는 부양에 대한 인식이 그렇게 높지 않은 것이 확인되어 진다.\n\nColumn 남녀 평등 교육이 시작되면서 장남들이 부양을 전적으로 책임져야한다는 인식은 감소하게 된 것으로 보인다. 또한 여성들의 부모님 부양에 대한 부정적 인식도 다소 감소한 것으로 보인다. 설령 여유가 있더라도 한 사람이 모든 부양을 책임지라는 인식 보다는 자립하거나 자녀들이 분담하여 부모님을 부양하고자 하는 인식이 강해진 것을 확인할 수 있다. 정부와 사회의 외부집단에 부모님 부양을 전적으로 의존하기 보다는 가족이 일정정도는 기여하여야 한다는 인식이 높은 것으로 나타난다.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 2020\n# Row Effect \nbarplot(pop2020_polished$row, ylim=c(-1,4), main=\"나이_2020년\")\n```\n\n::: {.cell-output-display}\n![](과제5_files/figure-html/unnamed-chunk-19-1.png){width=70%}\n:::\n\n```{.r .cell-code}\npop2020_polished$row\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n15∼19세 20∼29세 30∼39세 40∼49세 50∼59세 60세이상 65세이상 \n     0.0     -0.1      0.2     -0.1     -0.1      2.9      3.5 \n```\n:::\n\n```{.r .cell-code}\n# Column Effect\nbarplot(pop2020_polished$col, ylim=c(-10,60), main=\"부양유형_2020년\")\n```\n\n::: {.cell-output-display}\n![](과제5_files/figure-html/unnamed-chunk-19-2.png){width=70%}\n:::\n\n```{.r .cell-code}\npop2020_polished$col\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n        부모_스스로                가족 가족정부사회가_함께           정부_사회 \n                0.0                10.2                51.8                -9.4 \n               기타 \n              -11.6 \n```\n:::\n:::\n\n\nRow 앞의 자료들과 엄밀한 비교가 하기 어려운 것이 Column의 항목들이 바뀌었기 때문이다. 2020년도 데이터는 가족에 의한 부양 항목들이 세분화되지 않았기 때문에 해석에 유의가 필요하다. 직접적으로 부양을 받는 세대인 은퇴를 앞둔 60대의 입장에서는 본인의 은퇴이후의 삶에 대한 고민이 반영되었기 때문에 부모부양에 대한 강한 인식을 보이고 있지만, 이외의 세대에서는 부양에 대한 인식이 그렇게 높지 않은 것이 확인되어 진다.\n\nColumn 단순히 가족 외부의 정부_사회적 제도에 의존 (-8.512)하려는 인식 보다는 가족 정부 사회가 함께(52.3) 부양에 대한 부담을 분담 해야 한다는 인식이 공유되어 있음이 확인되어 진다. 자립 혹은 가족에 대한 긍정적 인식은 적은데 한국사회의 경우 대부분의 노후자금이 토지에 묶여 있는 경우가 많고 자녀 교육 비용이 많이 지출되기 때문에 부모 스스로 부양을 하는 것이 쉽지 않다는 인식이 공유된 것으로 보인다.\n\n### residual Analysis\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 1988\npar\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nfunction (..., no.readonly = FALSE) \n{\n    .Pars.readonly <- c(\"cin\", \"cra\", \"csi\", \"cxy\", \"din\", \"page\")\n    single <- FALSE\n    args <- list(...)\n    if (!length(args)) \n        args <- as.list(if (no.readonly) \n            .Pars[-match(.Pars.readonly, .Pars)]\n        else .Pars)\n    else {\n        if (all(unlist(lapply(args, is.character)))) \n            args <- as.list(unlist(args))\n        if (length(args) == 1) {\n            if (is.list(args[[1L]]) || is.null(args[[1L]])) \n                args <- args[[1L]]\n            else if (is.null(names(args))) \n                single <- TRUE\n        }\n    }\n    value <- .External2(C_par, args)\n    if (single) \n        value <- value[[1L]]\n    if (!is.null(names(args))) \n        invisible(value)\n    else value\n}\n<bytecode: 0x000001f4940bb3e8>\n<environment: namespace:graphics>\n```\n:::\n\n```{.r .cell-code}\nfor (i in 1:6) \n  {barplot(pop1988_polished$residuals[i,],main=rownames(pop1988)[i])}\n```\n\n::: {.cell-output-display}\n![](과제5_files/figure-html/unnamed-chunk-20-1.png){width=70%}\n:::\n\n::: {.cell-output-display}\n![](과제5_files/figure-html/unnamed-chunk-20-2.png){width=70%}\n:::\n\n::: {.cell-output-display}\n![](과제5_files/figure-html/unnamed-chunk-20-3.png){width=70%}\n:::\n\n::: {.cell-output-display}\n![](과제5_files/figure-html/unnamed-chunk-20-4.png){width=70%}\n:::\n\n::: {.cell-output-display}\n![](과제5_files/figure-html/unnamed-chunk-20-5.png){width=70%}\n:::\n\n::: {.cell-output-display}\n![](과제5_files/figure-html/unnamed-chunk-20-6.png){width=70%}\n:::\n\n```{.r .cell-code}\nfor (i in 1:6)\n  {barplot(pop1988_polished$residuals[,i],main=names(pop1988)[i])}\n```\n\n::: {.cell-output-display}\n![](과제5_files/figure-html/unnamed-chunk-20-7.png){width=70%}\n:::\n\n::: {.cell-output-display}\n![](과제5_files/figure-html/unnamed-chunk-20-8.png){width=70%}\n:::\n\n::: {.cell-output-display}\n![](과제5_files/figure-html/unnamed-chunk-20-9.png){width=70%}\n:::\n\n::: {.cell-output-display}\n![](과제5_files/figure-html/unnamed-chunk-20-10.png){width=70%}\n:::\n\n::: {.cell-output-display}\n![](과제5_files/figure-html/unnamed-chunk-20-11.png){width=70%}\n:::\n\n::: {.cell-output-display}\n![](과제5_files/figure-html/unnamed-chunk-20-12.png){width=70%}\n:::\n:::\n\n\n10대 부터 30대 까지는 장남의 부양이 아닌 남녀에 상관없이 사회에 의존하거나 자녀 모두가 부모 부양을 분담해야한다는 인식이 많았으나, 40대 이후에서는 이러한 인식이 정 반대인 것으로 나타난다. 장남이 부모님의 부양을 담당해야한다는 인식이 가장 많았고 분담에 대한 부정적인 인식이 많았다.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 2018\n\nfor (i in 1:6) \n  {barplot(pop2018_polished$residuals[i,],main=rownames(pop2018)[i])}\n```\n\n::: {.cell-output-display}\n![](과제5_files/figure-html/unnamed-chunk-21-1.png){width=70%}\n:::\n\n::: {.cell-output-display}\n![](과제5_files/figure-html/unnamed-chunk-21-2.png){width=70%}\n:::\n\n::: {.cell-output-display}\n![](과제5_files/figure-html/unnamed-chunk-21-3.png){width=70%}\n:::\n\n::: {.cell-output-display}\n![](과제5_files/figure-html/unnamed-chunk-21-4.png){width=70%}\n:::\n\n::: {.cell-output-display}\n![](과제5_files/figure-html/unnamed-chunk-21-5.png){width=70%}\n:::\n\n::: {.cell-output-display}\n![](과제5_files/figure-html/unnamed-chunk-21-6.png){width=70%}\n:::\n\n```{.r .cell-code}\nfor (i in 1:8) \n  {barplot(pop2018_polished$residuals[,i],main=names(pop2018)[i])}\n```\n\n::: {.cell-output-display}\n![](과제5_files/figure-html/unnamed-chunk-21-7.png){width=70%}\n:::\n\n::: {.cell-output-display}\n![](과제5_files/figure-html/unnamed-chunk-21-8.png){width=70%}\n:::\n\n::: {.cell-output-display}\n![](과제5_files/figure-html/unnamed-chunk-21-9.png){width=70%}\n:::\n\n::: {.cell-output-display}\n![](과제5_files/figure-html/unnamed-chunk-21-10.png){width=70%}\n:::\n\n::: {.cell-output-display}\n![](과제5_files/figure-html/unnamed-chunk-21-11.png){width=70%}\n:::\n\n::: {.cell-output-display}\n![](과제5_files/figure-html/unnamed-chunk-21-12.png){width=70%}\n:::\n\n::: {.cell-output-display}\n![](과제5_files/figure-html/unnamed-chunk-21-13.png){width=70%}\n:::\n\n::: {.cell-output-display}\n![](과제5_files/figure-html/unnamed-chunk-21-14.png){width=70%}\n:::\n:::\n\n\n88년도에 20대였던 사람들이 50대, 30대였던 사람들이 60대인 시점 전 세대에서 장남 혼자, 딸 혼자, 능력있는 자식 등 한명이 부모님 부양에 대한 책임을 독점하는 것에 대해 부정적인 시각을 가지고 있다. 10\\~20대 까지는 자녀들이 부모님 부양에 대한 책임을 분담해야 한다고 주장하다가, 30대와 40대, 50대에서는 가족 정부 사회가 부모님 부양 책임을 분담해야한다는 인식이 가장 크다. 50대에서는 자녀들이 부모님 부양하는 것을 부정적으로 생각하는 것이 확인된다. 신기했던 포인트는 60대이상 계층에서 자립을 강조하는 모습이다. 가족이나 정부 사회에 의존한 부양에 대해서 부정적인 인식을 가지고 있는 것으로 보이므로 의존하지 않고 본인이 본인의 노후 설계를 해야 한다는 생각이 공유되는 것이 확인된다.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#2020\n\nfor (i in 1:6) \n  {barplot(pop2020_polished$residuals[i,],main=rownames(pop2020)[i])}\n```\n\n::: {.cell-output-display}\n![](과제5_files/figure-html/unnamed-chunk-22-1.png){width=70%}\n:::\n\n::: {.cell-output-display}\n![](과제5_files/figure-html/unnamed-chunk-22-2.png){width=70%}\n:::\n\n::: {.cell-output-display}\n![](과제5_files/figure-html/unnamed-chunk-22-3.png){width=70%}\n:::\n\n::: {.cell-output-display}\n![](과제5_files/figure-html/unnamed-chunk-22-4.png){width=70%}\n:::\n\n::: {.cell-output-display}\n![](과제5_files/figure-html/unnamed-chunk-22-5.png){width=70%}\n:::\n\n::: {.cell-output-display}\n![](과제5_files/figure-html/unnamed-chunk-22-6.png){width=70%}\n:::\n\n```{.r .cell-code}\nfor (i in 1:5)\n  {barplot(pop2020_polished$residuals[,i],main=names(pop2020)[i])}\n```\n\n::: {.cell-output-display}\n![](과제5_files/figure-html/unnamed-chunk-22-7.png){width=70%}\n:::\n\n::: {.cell-output-display}\n![](과제5_files/figure-html/unnamed-chunk-22-8.png){width=70%}\n:::\n\n::: {.cell-output-display}\n![](과제5_files/figure-html/unnamed-chunk-22-9.png){width=70%}\n:::\n\n::: {.cell-output-display}\n![](과제5_files/figure-html/unnamed-chunk-22-10.png){width=70%}\n:::\n\n::: {.cell-output-display}\n![](과제5_files/figure-html/unnamed-chunk-22-11.png){width=70%}\n:::\n:::\n\n\n40대부터 50대 까지는 부모님 부양에 대한 직접 책임을 지기 때문에 가족에 의한 부양에 대해서 부정적인 인식을 보이고 있는 것이 확인되어 진다. 60대 이상의 계층에서는 가족정부사회가 함께 부양을 해야 한다고 보지 않고 전통적인 노인 부양 방식에 대해서 오히려 긍정적인 인식을 가진 것을 확인할 수 있다. 10대의 20대 경우 가족에 의한 노인 부양에 긍정적인 시선을 가지고 있는데 이는 교육에 의한 규범적인 요인들에 의해 형성된 시각이라고 생각한다. 특이점은 이전 조사들과는 다르게 30대에서 부모님의 자립에 긍정적인 인식이 있는 것이 확인되어 지는데 일시적으로 확인되는 이상치일 가능성이 있다.\n\n## two-way plot 과 Coded plot\n\n### 1988\n\n-   1988년도 Two way plot\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_1988=pop1988_polished$overall + outer(pop1988_polished$row,pop1988_polished$col, \"+\")\nfit_1988=fit_1988[c(order(fit_1988[,1],decreasing=T)),]\nfit_1988=fit_1988[,c(order(fit_1988[1,],decreasing=T))]\n(resid_1988=pop1988_polished$residuals)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n           장남 아들모두     딸 아들딸모두   자립 사회및기타\n15~19세  -8.375   -4.225 -0.175      8.875  0.175      1.325\n20~29세  -7.625   -2.075 -0.225      8.325  0.225      1.075\n30~39세  -4.875   -0.725 -0.175      3.775  1.675      0.325\n40~49세   4.875    0.725  0.175     -3.775 -0.175     -0.325\n50~59세  12.975    3.625  0.475     -8.775 -3.475     -0.325\n60세이상 24.575    2.725  0.675    -14.475 -7.875     -0.525\n```\n:::\n\n```{.r .cell-code}\nfivenum(as.vector(resid_1988)) # hinge 밖에 있는 값들은 Residual로 표현 안함\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] -14.475  -2.775   0.000   1.500  24.575\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ntwoway::twoway(pop1988,method=\"median\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nMedian polish decomposition (Dataset: \"pop1988\"; Response: Value)\nResiduals bordered by row effects, column effects, and overall\n\n           장남    아들모두 딸      아들딸모두 자립    사회및기타   roweff \n         + ------- -------  ------- -------    ------- -------    + -------\n15~19세  |  -8.375  -4.225   -0.175   8.875      0.175   1.325    :   0.525\n20~29세  |  -7.625  -2.075   -0.225   8.325      0.225   1.075    :   0.175\n30~39세  |  -4.875  -0.725   -0.175   3.775      1.675   0.325    :   0.125\n40~49세  |   4.875   0.725    0.175  -3.775     -0.175  -0.325    :  -0.125\n50~59세  |  12.975   3.625    0.475  -8.775     -3.475  -0.325    :  -0.625\n60세이상 |  24.575   2.725    0.675 -14.475     -7.875  -0.525    :  -0.725\n         + ....... .......  ....... .......    ....... .......    + .......\ncoleff   |   6.800   0.750  -17.000  17.550     -0.750 -12.800    :  17.450\n```\n:::\n\n```{.r .cell-code}\nplot(twoway::twoway(pop1988,method=\"median\"))\n```\n\n::: {.cell-output-display}\n![](과제5_files/figure-html/unnamed-chunk-24-1.png){width=672}\n:::\n:::\n\n\n모든 자녀들이 부모님에 대한 부양을 분담해야 한다는 인식이 가장 높게 나타나고 그 다음은 장남이 책임져야 한다는 인식이 있는 것이 확인된다. 딸이 부모님 부양하는 것에 대한 인식은 낮은 편이다. 15\\~19 세 그룹에서 가장 부모님 부양에 대한 긍정적 인식을 보이고 있으며, 반면 60 세 이상 그룹에서는 부모님 부양에 대한 부정적 인식이 있는 것이 확인된다. 나이가 어릴수록 부모님 부양에 대해서 긍정적인 인식이 있는 것이 확인 되어진다.\n\n-   1988년도 coded plot\n\n\n::: {.cell}\n\n```{.r .cell-code}\nstandard=as.vector(resid_1988)\nfivenum(standard)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] -14.475  -2.775   0.000   1.500  24.575\n```\n:::\n\n```{.r .cell-code}\nHspread_1988=fivenum(standard)[4]-fivenum(standard)[2]\ninner_1988=c(fivenum(standard)[4]+1.5*Hspread_1988,fivenum(standard)[2]-1.5*Hspread_1988)\nouter_1988=c(fivenum(standard)[4]+3*Hspread_1988,fivenum(standard)[2]-3*Hspread_1988)\nHspread_1988; inner_1988; outer_1988\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 4.275\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n[1]  7.9125 -9.1875\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n[1]  14.325 -15.600\n```\n:::\n\n```{.r .cell-code}\nresid_1988=as.data.frame(resid_1988)\n# 교과서 기준과 동일하게 \"M\" - Far outside low, \"=\"- below low inner fence(outise), \"-\" - Below lower hinge but within inner fence\n# \".\" - Between Hinges , \"+\"- Above upper hinge, \"#\" - Above High inner fence (outside), \"F\" - Far outside high\nresid_1988_coded=ifelse(resid_1988 >= outer_1988[1], \"F\",\n                        ifelse(resid_1988 >= inner_1988[1], \"#\",\n                               ifelse(resid_1988 >= fivenum(standard)[4],\"+\",\n                                      ifelse(resid_1988 >=fivenum(standard)[2] ,\".\",\n                                             ifelse(resid_1988 >= inner_1988[2],\"-\",\n                                                    ifelse(resid_1988 >= outer_1988[2],\"=\",\"M\"))))))\nresid_1988\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n           장남 아들모두     딸 아들딸모두   자립 사회및기타\n15~19세  -8.375   -4.225 -0.175      8.875  0.175      1.325\n20~29세  -7.625   -2.075 -0.225      8.325  0.225      1.075\n30~39세  -4.875   -0.725 -0.175      3.775  1.675      0.325\n40~49세   4.875    0.725  0.175     -3.775 -0.175     -0.325\n50~59세  12.975    3.625  0.475     -8.775 -3.475     -0.325\n60세이상 24.575    2.725  0.675    -14.475 -7.875     -0.525\n```\n:::\n\n```{.r .cell-code}\n(resid_1988_coded=as.data.frame(resid_1988_coded))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n         장남 아들모두 딸 아들딸모두 자립 사회및기타\n15~19세     -        -  .          #    .          .\n20~29세     -        .  .          #    .          .\n30~39세     -        .  .          +    +          .\n40~49세     +        .  .          -    .          .\n50~59세     #        +  .          -    -          .\n60세이상    F        +  .          =    -          .\n```\n:::\n:::\n\n\n60 세 이상 집단에서는 자립을 강조하고 정부나 사회에 의존하는 것에 대한 부정적인 인식이 확인되어진다. 반면 10 대나 20 대의 경우 모든 자녀들이 부모님 부양에 대한 부담을 분담해야 한다고 보고 있는 것으로 보인다. 30\\~50 대에서는 부모님 부양에 대한 책임을 가족 정부 사회가 분담해야 한다고 보고 있다. 이러한 이유를 부모님 부양에 대한 부담을 느끼기 때문으로 보고 있다.\n\n### 2018\n\n-   2018년도 Two way plot\n\n\n::: {.cell}\n\n```{.r .cell-code}\nfit_2018=pop2018_polished$overall + outer(pop2018_polished$row,pop2018_polished$col, \"+\")\nfit_2018=fit_2018[c(order(fit_2018[,1],decreasing=T)),]\nfit_2018=fit_2018[,c(order(fit_2018[1,],decreasing=T))]\n(resid_2018=pop2018_polished$residuals)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n             자립     장남 아들모두       딸 모든_자녀     능력 가족정부사회\n13∼19세  0.06562 -0.06875  0.79688  0.56250   8.21250 -0.35312     -4.40313\n20∼29세  1.40312 -0.43125 -0.06562  0.10000   2.45000  0.08438     -1.06563\n30∼39세 -0.49687 -0.23125  0.13438  0.00000   0.55000 -0.01562      1.83437\n40∼49세 -0.89688  0.06875  0.03438  0.00000  -0.55000 -0.21562      2.53437\n50∼59세 -0.06562  0.20000 -0.03438 -0.06875  -1.01875  0.01562      1.06563\n60세이상  6.09063  0.75625 -0.27812 -0.91250  -2.26250  0.27187    -12.87813\n         정부사회\n13∼19세 -0.53750\n20∼29세 -1.10000\n30∼39세 -0.40000\n40∼49세  0.40000\n50∼59세  0.73125\n60세이상  1.68750\n```\n:::\n\n```{.r .cell-code}\nfivenum(as.vector(resid_2018)) # hinge 밖에 있는 값들은 Residual로 표현 안함\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] -12.878130  -0.415625   0.000000   0.556250   8.212500\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ntwoway::twoway(pop2018,method=\"median\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nMedian polish decomposition (Dataset: \"pop2018\"; Response: Value)\nResiduals bordered by row effects, column effects, and overall\n\n           자립      장남      아들모두  딸        모든_자녀 능력     \n         + --------- --------- --------- --------- --------- ---------\n13∼19세 |   0.06562  -0.06875   0.79688   0.56250   8.21250  -0.35312\n20∼29세 |   1.40312  -0.43125  -0.06562   0.10000   2.45000   0.08438\n30∼39세 |  -0.49687  -0.23125   0.13438   0.00000   0.55000  -0.01562\n40∼49세 |  -0.89688   0.06875   0.03438   0.00000  -0.55000  -0.21562\n50∼59세 |  -0.06562   0.20000  -0.03438  -0.06875  -1.01875   0.01562\n60세이상 |   6.09063   0.75625  -0.27812  -0.91250  -2.26250   0.27187\n         + ......... ......... ......... ......... ......... .........\ncoleff   |  12.94688  -3.81875  -4.08438  -4.65000  13.70000  -0.23438\n         가족정부사회 정부사회    roweff   \n         ---------    --------- + ---------\n13∼19세  -4.40313     -0.53750 :  -0.36250\n20∼29세  -1.06563     -1.10000 :   0.00000\n30∼39세   1.83437     -0.40000 :   0.00000\n40∼49세   2.53437      0.40000 :   0.00000\n50∼59세   1.06563      0.73125 :   0.06875\n60세이상 -12.87813      1.68750 :   1.11250\n         .........    ......... + .........\ncoleff    45.71562      0.25000 :   4.85000\n```\n:::\n\n```{.r .cell-code}\nplot(twoway::twoway(pop2018,method=\"median\"))\n```\n\n::: {.cell-output-display}\n![](과제5_files/figure-html/unnamed-chunk-27-1.png){width=672}\n:::\n:::\n\n\n가족 정부 사회가 협력하여 부모님 부양을 담당해야 한다는 인식이 높은 것으로 보인다. 특이하게, 가족이 배제된 부모님 부양에 대한 인식은 부정적인 것으로 보인다. 60 세 이상에서 88 년도와는 다르게 부모님 부양에 대해 인식이 개선됨 (BUT 88 년도와 20 년도의 Column 항목들이 다르기 때문에 단순히 전반적 인식이 개선되었다라고 보기에는 한계가 있음) 60 세 이상,65 세 이상 집단에서 부모님 부양에 대한 인식이 높은 것으로 보이며 30 대,40 대,50 대가 서로 비슷한 수준의 부모님 부양에 대한 인식을 가지고 있는 것으로 보인다.\n\n-   2018년도 coded plot\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresid_2018=pop2018_polished$residuals\nstandard=as.vector(resid_2018)\nfivenum(standard)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] -12.878130  -0.415625   0.000000   0.556250   8.212500\n```\n:::\n\n```{.r .cell-code}\nHspread_2018=fivenum(standard)[4]-fivenum(standard)[2]\ninner_2018=c(fivenum(standard)[4]+1.5*Hspread_2018,fivenum(standard)[2]-1.5*Hspread_2018)\nouter_2018=c(fivenum(standard)[4]+3*Hspread_2018,fivenum(standard)[2]-3*Hspread_2018)\nHspread_2018; inner_2018; outer_2018\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.971875\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n[1]  2.014063 -1.873438\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n[1]  3.471875 -3.331250\n```\n:::\n\n```{.r .cell-code}\nresid_2018=as.data.frame(resid_2018)\n# 교과서 기준과 동일하게 \"M\" - Far outside low, \"=\"- below low inner fence(outise), \"-\" - Below lower hinge but within inner fence\n# \".\" - Between Hinges , \"+\"- Above upper hinge, \"#\" - Above High inner fence (outside), \"F\" - Far outside high\nresid_2018_coded=ifelse(resid_2018 >= outer_2018[1], \"F\",\n       ifelse(resid_2018 >= inner_2018[1], \"#\",\n              ifelse(resid_2018 >= fivenum(standard)[4],\"+\",\n                     ifelse(resid_2018 >=fivenum(standard)[2] ,\".\",\n                            ifelse(resid_2018>= inner_2018[2],\"-\",\n                                   ifelse(resid_2018 >= outer_2018[2],\"=\",\"M\"))))))\nresid_2018\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n             자립     장남 아들모두       딸 모든_자녀     능력 가족정부사회\n13∼19세  0.06562 -0.06875  0.79688  0.56250   8.21250 -0.35312     -4.40313\n20∼29세  1.40312 -0.43125 -0.06562  0.10000   2.45000  0.08438     -1.06563\n30∼39세 -0.49687 -0.23125  0.13438  0.00000   0.55000 -0.01562      1.83437\n40∼49세 -0.89688  0.06875  0.03438  0.00000  -0.55000 -0.21562      2.53437\n50∼59세 -0.06562  0.20000 -0.03438 -0.06875  -1.01875  0.01562      1.06563\n60세이상  6.09063  0.75625 -0.27812 -0.91250  -2.26250  0.27187    -12.87813\n         정부사회\n13∼19세 -0.53750\n20∼29세 -1.10000\n30∼39세 -0.40000\n40∼49세  0.40000\n50∼59세  0.73125\n60세이상  1.68750\n```\n:::\n\n```{.r .cell-code}\n(resid_2018_coded=as.data.frame(resid_2018_coded))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n         자립 장남 아들모두 딸 모든_자녀 능력 가족정부사회 정부사회\n13∼19세    .    .        +  +         F    .            M        -\n20∼29세    +    -        .  .         #    .            -        -\n30∼39세    -    .        .  .         .    .            +        .\n40∼49세    -    .        .  .         -    .            #        .\n50∼59세    .    .        .  .         -    .            +        +\n60세이상    F    +        .  -         =    .            M        +\n```\n:::\n:::\n\n\n### 2020\n\n-   2020년도 Two way plot\n\n\n::: {.cell}\n\n```{.r .cell-code}\nf=pop2020_polished$overall + outer(pop2020_polished$row,pop2020_polished$col, \"+\")\n\nf=f[c(order(f[,1],decreasing=T)),]\nf=f[,c(order(f[1,],decreasing=T))]\n\n(resid_2020=pop2020_polished$residuals)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n         부모_스스로 가족 가족정부사회가_함께 정부_사회 기타\n15∼19세        -0.6  5.3                -4.6       0.4  0.0\n20∼29세         0.0  0.0                 1.0       0.0  0.0\n30∼39세         2.5 -2.7                 0.0       0.0 -0.3\n40∼49세        -0.6 -2.4                 3.1       0.9  0.0\n50∼59세        -0.9 -2.6                 3.1       1.4  0.0\n60세이상         1.4  1.2               -13.6       0.0 -3.0\n65세이상         1.8  1.9               -17.1       0.0 -3.6\n```\n:::\n\n```{.r .cell-code}\nfivenum(as.vector(resid_2020)) # hinge 밖에 있는 값들은 Residual로 표현 안함\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] -17.10  -0.75   0.00   1.10   5.30\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ntwoway::twoway(pop2020,method=\"median\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\nMedian polish decomposition (Dataset: \"pop2020\"; Response: Value)\nResiduals bordered by row effects, column effects, and overall\n\n           부모_스스로 가족  가족정부사회가_함께 정부_사회 기타    roweff\n         + -----       ----- -----               -----     ----- + ----- \n15∼19세 |  -0.6         5.3  -4.6                 0.4       0.0 :   0.0 \n20∼29세 |   0.0         0.0   1.0                 0.0       0.0 :  -0.1 \n30∼39세 |   2.5        -2.7   0.0                 0.0      -0.3 :   0.2 \n40∼49세 |  -0.6        -2.4   3.1                 0.9       0.0 :  -0.1 \n50∼59세 |  -0.9        -2.6   3.1                 1.4       0.0 :  -0.1 \n60세이상 |   1.4         1.2 -13.6                 0.0      -3.0 :   2.9 \n65세이상 |   1.8         1.9 -17.1                 0.0      -3.6 :   3.5 \n         + .....       ..... .....               .....     ..... + ..... \ncoleff   |   0.0        10.2  51.8                -9.4     -11.6 :  11.7 \n```\n:::\n\n```{.r .cell-code}\nplot(twoway::twoway(pop2020,method=\"median\"))\n```\n\n::: {.cell-output-display}\n![](과제5_files/figure-html/unnamed-chunk-30-1.png){width=672}\n:::\n:::\n\n\n가족 정부 사회가 협력하여 부모님 부양을 담당해야 한다는 인식이 높은 것으로 보인다. 특이하게, 가족이 배제된 부모님 부양에 대한 인식은 부정적인 것으로 보인다. 60 세 이상에서 88 년도와는 다르게 부모님 부양에 대해 인식이 개선됨 (BUT 88 년도와 20 년도의 Column 항목들이 다르기 때문에 단순히 전반적 인식이 개선되었다라고 보기에는 한계가 있음) 60 세 이상,65 세 이상 집단에서 부모님 부양에 대한 인식이 높은 것으로 보이며 30 대,40 대,50 대가 서로 비슷한 수준의 부모님 부양에 대한 인식을 가지고 있는 것으로 보인다.\n\n-   2020년도 coded plot\n\n\n::: {.cell}\n\n```{.r .cell-code}\nresid_2020=pop2020_polished$residuals\nstandard=as.vector(resid_2020)\nfivenum(standard)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] -17.10  -0.75   0.00   1.10   5.30\n```\n:::\n\n```{.r .cell-code}\nHspread_2020=fivenum(standard)[4]-fivenum(standard)[2]\ninner_2020=c(fivenum(standard)[4]+1.5*Hspread_2020,fivenum(standard)[2]-1.5*Hspread_2020)\nouter_2020=c(fivenum(standard)[4]+3*Hspread_2020,fivenum(standard)[2]-3*Hspread_2020)\nHspread_2020; inner_2020; outer_2020\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.85\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n[1]  3.875 -3.525\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n[1]  6.65 -6.30\n```\n:::\n\n```{.r .cell-code}\nresid_2020=as.data.frame(resid_2020)\n# 교과서 기준과 동일하게 \"M\" - Far outside low, \"=\"- below low inner fence(outise), \"-\" - Below lower hinge but within inner fence\n# \".\" - Between Hinges , \"+\"- Above upper hinge, \"#\" - Above High inner fence (outside), \"F\" - Far outside high\nresid_2020_coded=ifelse(resid_2020 >= outer_2020[1], \"F\",\n       ifelse(resid_2020 >= inner_2020[1], \"#\",\n              ifelse(resid_2020 >= fivenum(standard)[4],\"+\",\n                     ifelse(resid_2020 >=fivenum(standard)[2] ,\".\",\n                            ifelse(resid_2020>= inner_2020[2],\"-\",\n                                   ifelse(resid_2020 >= outer_2020[2],\"=\",\"M\"))))))\nresid_2020\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n         부모_스스로 가족 가족정부사회가_함께 정부_사회 기타\n15∼19세        -0.6  5.3                -4.6       0.4  0.0\n20∼29세         0.0  0.0                 1.0       0.0  0.0\n30∼39세         2.5 -2.7                 0.0       0.0 -0.3\n40∼49세        -0.6 -2.4                 3.1       0.9  0.0\n50∼59세        -0.9 -2.6                 3.1       1.4  0.0\n60세이상         1.4  1.2               -13.6       0.0 -3.0\n65세이상         1.8  1.9               -17.1       0.0 -3.6\n```\n:::\n\n```{.r .cell-code}\n(resid_2020_coded=as.data.frame(resid_2020_coded))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n         부모_스스로 가족 가족정부사회가_함께 정부_사회 기타\n15∼19세           .    #                   =         .    .\n20∼29세           .    .                   .         .    .\n30∼39세           +    -                   .         .    .\n40∼49세           .    -                   +         .    .\n50∼59세           -    -                   +         +    .\n60세이상           +    +                   M         .    -\n65세이상           +    +                   M         .    =\n```\n:::\n:::\n\n\n60 세 이상집단에서 외부의 도움보다는 가족 혹은 본인이 부모님 부양을 담당해야 한다고 생각하는 것으로 보인다. 이러한 이유는 나이가 많은 집단에서 외부의 도움을 별로 좋아하지 않기 때문이라고 보인다. 88 년도 자료에서와 엄밀한 비교는 어렵지만 정부나 사회에 도움을 받는 것을 꺼려하는 60 대 이상 계층들의 태도는 일관적일 것으로 보인다. 반면, 40 대 50 대 집단에서는 가족정부사회가 함께 부모님 부양을 담당해야 한다는 인식이 있는데 실제로 40 대\\~50 대가 부모님 부양을 담당하면서 부담을 느끼기 때문이라고 추측할 수 있다.\n",
    "supporting": [
      "과제5_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}