{
  "hash": "99de6d4f86c6b7d82b2bde1e851fe4af",
  "result": {
    "markdown": "---\ntitle: \"EDA Assignment 2: Chapter 4\"\nauthor: \"Sangwon Ju, Yonsei Public Administration\"\ndate: 'march/30/2021'\npage-layout: full\nformat: \n    html\ncategories: \n    \"Exploratory Data Analysis (2021 Spring) [in Korean]\"\n---\n\n\n4장. 수치요약과 상자그림, 여러 그룹의 비교\n\n자료를 분석할 때 모든 부분을 R로 할 수도 없는 경우도 있다. R에서 이용할 수 있는 것들은 이용하되 수작업이 필요한 부분은 수작업으로 하여야 한다. 곱하기 나누기 등 간단한 계산은 계산기를 사용할 수도 있다.\n\n# 1번\n\nIslands 자료\n\n## (1) inner fence와 outer fence값들을 구하여라.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(islands)\nhead(islands)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n      Africa   Antarctica         Asia    Australia Axel Heiberg       Baffin \n       11506         5500        16988         2968           16          184 \n```\n:::\n\n```{.r .cell-code}\nf=fivenum(islands)\nHl=as.numeric(f[2])\nM=as.numeric(f[3])\nHu=as.numeric(f[4])\nhspread=as.numeric(Hu-Hl)\nhspread\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 163.5\n```\n:::\n\n```{.r .cell-code}\n# Inner Fence\nIF=c(Hl-1.5*hspread,Hu+1.5*hspread)\nIF\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] -225.25  428.75\n```\n:::\n\n```{.r .cell-code}\n# Outer Fence\nOF=c(Hl-3*hspread,Hu+3*hspread)\nOF\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] -470.5  674.0\n```\n:::\n\n```{.r .cell-code}\nSKEW=((Hu-M)-(M-Hl))/((Hu-M)+(M-Hl))\nSKEW # +이기에 Skewed to the right\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.7431193\n```\n:::\n:::\n\n\n## (2) letter value display와 boxplot을 만들고 자료의 특성을 요약하여라.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# letter value display\nsource(\"http://mgimond.github.io/ES218/es218.R\")\nlvd=lsum(islands)\nlvd\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n                 letter depth lower     mid   upper  spread\nIceland               M  24.5  41.0   41.00    41.0     0.0\nTierra del Fuego      H  12.5  20.0  101.75   183.5   163.5\nTaiwan                E   6.5  14.5 1685.50  3356.5  3342.0\nPrince of Wales       D   3.5  13.0 4052.75  8092.5  8079.5\nHainan                C   2.0  13.0 5759.50 11506.0 11493.0\n```\n:::\n\n```{.r .cell-code}\nlvd[,4]\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1]   41.00  101.75 1685.50 4052.75 5759.50\n```\n:::\n\n```{.r .cell-code}\n# boxplot\nboxplot(islands,horizontal=T,main=\"Boxplot of islands data\")\n```\n\n::: {.cell-output-display}\n![](과제2_files/figure-html/unnamed-chunk-2-1.png){width=672}\n:::\n\n```{.r .cell-code}\nboxplot(log(islands))\n```\n\n::: {.cell-output-display}\n![](과제2_files/figure-html/unnamed-chunk-2-2.png){width=672}\n:::\n:::\n\n\n-   letter value display median의 값은 41, Upper Hinge의 값은 183.5, Lower Hinge의 값은 20으로 확인 됨. depth가 24.5까지 들어가고 있다. H-Spread의 값은 163.5이고 이를 통해 계산한 Pseudo Variance값은 163.5/1.35=121.11 로 계산된다. mid 값이 41, 101.75, 1685.50, 4052.75, 5759.50 순으로 증가하고 있기 때문에 이 자료의 분포는 Skewed to the right이라고 생각하면 좋다.\n-   box plot Symmetric하지 않고, Skewed to the right 하여 극단적으로 큰 값들이 존재한다는 것을 존재한다는 것은 Box Plot을 통해 재확인할 수 있다. Median의 위치는 매우 작아서 확인이 불가능하다. Spread는 약 11000 정도인 것으로 보이며 Whisker의 크기도 거의 확인할 수가 없다. 위의 문제에서 계산한 Outer Fence의 값은 -470과 674인데 Outer Fence밖의 Far Out(Outliers)값이 8개 존재하는 것을 확인 할 수 있다. 로그변환이나 지수변환을 통해서 데이터들을 Symmetric하게 만들고 Spread를 확인할 수 있게 만들어 데이터를 조금 더 해석하기 용이하게 해야 한다.\n\n# 2번\n\nOzone 자료\n\n바람이 세게 불 때와 그렇지 않을 때로 자료를 나누어 오존량의 letter value display를 각각 만들고 mid와 spread 칼럼의 값과 stem-and-leaf display와 boxplot의 notch등을 이용하여 두 집단의 오존량을 비교하여라.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndata(\"airquality\")\nhead(airquality)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  Ozone Solar.R Wind Temp Month Day\n1    41     190  7.4   67     5   1\n2    36     118  8.0   72     5   2\n3    12     149 12.6   74     5   3\n4    18     313 11.5   62     5   4\n5    NA      NA 14.3   56     5   5\n6    28      NA 14.9   66     5   6\n```\n:::\n\n```{.r .cell-code}\nairquality<-as.data.frame(airquality)\nclass(airquality)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"data.frame\"\n```\n:::\n\n```{.r .cell-code}\n# 자료 요약 / Five Numbers / Boxplot\nsummary(airquality$Ozone)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's \n   1.00   18.00   31.50   42.13   63.25  168.00      37 \n```\n:::\n\n```{.r .cell-code}\nfivenum(airquality$Ozone)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1]   1.0  18.0  31.5  63.5 168.0\n```\n:::\n\n```{.r .cell-code}\nboxplot(airquality$Ozone,title=\"Boxplot of Ozone Variable\")\n```\n\n::: {.cell-output-display}\n![](과제2_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\nMedian 값에서 Upper Hinge나 Lower Hinge 까지의 거리에 비해서 최대값까지의 거리가 길다는 것을 확인할 수 있다. 따라서 주어진 자료의 분포는 Skewed to the right이라는 것을 확인할 수 있다. Boxplot상 Outer Hinge 밖의 Outlier가 2개 정도 존재하고 있음을 확인할 수 있다.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# 바람이 세게 부는 집단과 그렇지 않은 집단의 분류\n# Wind: Average wind speed in miles per hour at 0700 and 1000 hours at LaGuardia Airport\n# Ozone: Mean ozone in parts per billion from 1300 to 1500 hours at Roosevelt Island\n\nw_med=median(airquality$Wind)\nhist(airquality$Wind,main=\"Histogram of Windspeed(mph)\",xlab=\"Windspeed\",breaks=20)\nabline(v=w_med,col=\"red\",lty=2)\n```\n\n::: {.cell-output-display}\n![](과제2_files/figure-html/unnamed-chunk-4-1.png){width=672}\n:::\n\n```{.r .cell-code}\nhigherwind=airquality$Wind>=w_med\nncol(airquality[airquality$Wind==w_med,]) # Median Value를 갖는 관측치의 수 \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 6\n```\n:::\n\n```{.r .cell-code}\n#정의: 바람이 세게 부는 집단은 Median값보다 바람이 세게 부는 집단, 바람이 약하게 부는 집단은 Median값보다 바람이 약하게 부는 집단\n\nstrongwind=airquality[higherwind,] #바람이 세게부는 집단\nweakwind=airquality[!higherwind,] #바람이 약하게 부는 집단 \n\nnrow(strongwind); nrow(weakwind) #Windspeed의 Median Value를 Strongwind에 포함시킴\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 83\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 70\n```\n:::\n:::\n\n\n강한 바람의 그룹은 83개의 데이터를 가지고 있는 것에 비해, 약한 바람의 그룹은 70개의 데이터를 가지고있는데 여기서의 차이는 바람속도가 Median에 속하는 Observation들이 강한 바람을 가진 그룹으로 분류되었기 때문이다.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# Letter Value Display\nsource(\"http://mgimond.github.io/ES218/es218.R\")\nlsum(strongwind$Ozone)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  letter depth lower   mid upper spread\n1      M  32.0    21 21.00  21.0    0.0\n2      H  16.5    13 23.75  34.5   21.5\n3      E   8.5     9 26.75  44.5   35.5\n4      D   4.5     7 35.50  64.0   57.0\n5      C   2.5     5 39.25  73.5   68.5\n```\n:::\n\n```{.r .cell-code}\nlsum(weakwind$Ozone)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  letter depth lower   mid upper spread\n1      M  27.0  59.0 59.00  59.0    0.0\n2      H  14.0  30.0 57.00  84.0   54.0\n3      E   7.5  20.0 61.25 102.5   82.5\n4      D   4.0  16.0 67.00 118.0  102.0\n5      C   2.5  13.5 71.00 128.5  115.0\n```\n:::\n\n```{.r .cell-code}\nlsum(weakwind$Ozone)[2,5]-lsum(weakwind$Ozone)[2,3]\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 54\n```\n:::\n\n```{.r .cell-code}\nlsum(strongwind$Ozone)[2,5]-lsum(strongwind$Ozone)[2,3] #spread\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 21.5\n```\n:::\n\n```{.r .cell-code}\n#kurtosis\n82.5/54-1.705\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] -0.1772222\n```\n:::\n\n```{.r .cell-code}\n35.5/21.5-1.705\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] -0.05383721\n```\n:::\n\n```{.r .cell-code}\n#skewedness\nlsum(weakwind$Ozone)[,4]\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 59.00 57.00 61.25 67.00 71.00\n```\n:::\n\n```{.r .cell-code}\nlsum(strongwind$Ozone)[,4]\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 21.00 23.75 26.75 35.50 39.25\n```\n:::\n:::\n\n\n바람 세기가 약한그룹의 H-Spread는 54인 반면 바람세기가 강한 그룹의 H-Spread는 21.5이므로 바람세기가 약한 그룹의 데이터가 조금 더 변동성이 큰 것으로 확인된다. Median 값의 경우 바람세기가 강한 그룹은 21, 바람세기가 약한그룹은 59이므로 바람세기가 약한 그룹에 속하는 Observation들의 오존측정량이 더 높은 경향성을 보인다는 것을 확인 할 수 있다. (바람에 의해서 오존들이 흩어지게 되면서 측정치가 상대적으로 낮게 나타나는 것으로 보인다.)\n\nKurtosis: E-spread/H-spread-1.705 바람세기가 약한 그룹: (82.5/(54))-1.705=-0.1772222 바람세기가 강한 그룹: 35.5/21.5-1.705=-0.05383721 첨도가 두 집단에서 모두 음수이기 때문에 정규분포보다 평평한 성질을 가지고 있음이 확인되어 진다.\n\nSkewedness: 두 그룹의 Display에서 mid 값이 점차 커지고 있는 상황이므로 두 그룹 자료의 분포들은 Skewed to the right되어 있다고 볼 수 있다.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n# stem and leaf \n# install.packages(\"aplpack\")\nstem(strongwind$Ozone)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  The decimal point is 1 digit(s) to the right of the |\n\n  0 | 146778999\n  1 | 011223333444468889\n  2 | 001111233447889\n  3 | 012245679\n  4 | 044455\n  5 | 2\n  6 | 35\n  7 | 16\n  8 | 9\n```\n:::\n\n```{.r .cell-code}\nstem(weakwind$Ozone)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n\n  The decimal point is 1 digit(s) to the right of the |\n\n   0 | 716668\n   2 | 0033338025679\n   4 | 16789099\n   6 | 1446337889\n   8 | 024551677\n  10 | 8058\n  12 | 25\n  14 | \n  16 | 8\n```\n:::\n\n```{.r .cell-code}\nlibrary(aplpack)\nstem.leaf(strongwind$Ozone,rule.line = \"Dixon\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n1 | 2: represents 12\n leaf unit: 1\n            n: 63\n    2    0* | 14\n    9    0. | 6778999\n   22    1* | 0112233334444\n   27    1. | 68889\n  (11)   2* | 00111123344\n   25    2. | 7889\n   21    3* | 01224\n   16    3. | 5679\n   12    4* | 0444\n    8    4. | 55\n    6    5* | 2\n         5. | \n    5    6* | 3\n    4    6. | 5\n    3    7* | 1\nHI: 76 89\nNA's: 20\n```\n:::\n\n```{.r .cell-code}\nstem.leaf(weakwind$Ozone,rule.line = \"Dixon\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n1 | 2: represents 12\n leaf unit: 1\n            n: 53\n   1     0 | 7\n   6     1 | 16668\n  13     2 | 0033338\n  19     3 | 025679\n  24     4 | 16789\n  (3)    5 | 099\n  26     6 | 1446\n  22     7 | 337889\n  16     8 | 02455\n  11     9 | 1677\n   7    10 | 8\n   6    11 | 058\n   3    12 | 2\n   2    13 | 5\nHI: 168\nNA's: 17\n```\n:::\n\n```{.r .cell-code}\nstem.leaf.backback(strongwind$Ozone,weakwind$Ozone,rule.line = \"Dixon\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n_________________________________________________________\n  1 | 2: represents 12, leaf unit: 1 \n          strongwind$Ozone      weakwind$Ozone        \n_________________________________________________________\n    9            999877641|  0 |7                    1   \n   27   988864444333322110|  1 |16668                6   \n  (15)     988744332111100|  2 |0033338             13   \n   21            976542210|  3 |025679              19   \n   12               554440|  4 |16789               24   \n    6                    2|  5 |099                 (3)  \n    5                   53|  6 |1446                26   \n    3                   61|  7 |337889              22   \n    1                    9|  8 |02455               16   \n                          |  9 |1677                11   \n                          | 10 |8                    7   \n                          | 11 |058                  6   \n                          | 12 |2                    3   \n                          | 13 |5                    2   \n_________________________________________________________\n                                HI: 168                   \nn:                      83      70                    \nNAs:                    20      17                    \n_________________________________________________________\n```\n:::\n:::\n\n\n맨 마지막의 Stem and leaf plot을 기준으로 설명하고자 한다. 강한 바람 집단과 약한 바람 집단의 분포를 간단하게 살펴보면 강한 바람 집단의 경우 한개의 봉우리로 이루어져 있는데 반해 약한 바람 집단은 두개의 봉우리를 이루고 잇는 것을 확인할 수 있다. 강한 바람 집단은 Stem 1을 기준으로 leaf들이 Cluster 되어있는데 반해 약한 바람 집단은 Stem 2와 Stem 7의 두개의 Cluster로 이루어져 있으므로 조금 더 자료들이 넓게 퍼져있는 것이 확인되어진다. 중간에 Blank된 부분은 없는 것으로 보이며 Stem 12,13의 Leaf들의 존재는 Outlier의 존재 가능성을 확인하여 준다. 실제로 Boxplot을 그려 Outer Fence내에 자료값들이 존재하는지 여부를 확인하고자 한다.\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Boxplot\nairquality$Group<-ifelse(airquality$Wind>=w_med,\"Faster\",\"Slower\")\nboxplot(airquality$Ozone~airquality$Group,main=\"Comparison b/w Different Windspeed Groups\",col=c(\"Red\",\"Blue\"),notch=T)\n\nlibrary(ggplot2)\n```\n\n::: {.cell-output-display}\n![](과제2_files/figure-html/unnamed-chunk-7-1.png){width=672}\n:::\n\n```{.r .cell-code}\nggplot(data=airquality,aes(x=Group,y=Ozone,fill=Group))+\n  geom_boxplot(notch=T)+ \n  labs(title=\"Comparison b/w Different Windspeed Groups\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: Removed 37 rows containing non-finite values (stat_boxplot).\n```\n:::\n\n::: {.cell-output-display}\n![](과제2_files/figure-html/unnamed-chunk-7-2.png){width=672}\n:::\n\n```{.r .cell-code}\nmedian(strongwind$Ozone,na.rm=T)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 21\n```\n:::\n\n```{.r .cell-code}\nc(21-(21.5*1.58/sqrt(83)),21+(21.5*1.58/sqrt(83)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 17.27131 24.72869\n```\n:::\n\n```{.r .cell-code}\nmedian(weakwind$Ozone,na.rm=T)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 59\n```\n:::\n\n```{.r .cell-code}\nc(59-(54*1.58/sqrt(70)),59+(54*1.58/sqrt(70)))\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 48.80231 69.19769\n```\n:::\n:::\n\n\n두 집단의 Notched Interval이 서로 겹치지 않기 때문에 두 Median은 신뢰수준 5% 수준에서 서로 유의미하게 차이를 보인다고 볼 수 있다. 바람이 더 센 그룹의 오존량이 더 적다고 보는 것은 따라서 타당하다. 바람 속도가 빠른집단에서는 Outlier가 세개, 느린집단에서는 두개가 발견되었으며 위에서 확인하였던 것 처럼 두 그룹 모두 오존량의 데이터들은 Skewed to the right되어 있다. (Whisker의 길이는 바람속도가 느린 집단에서 더 긴것으로 확인되어진다. )\n\n-   바람속도가 빠른 집단과 느린집단을 분류하는 기준이 조금 더 명확해야 한다. 히스토그램을 그려 두 집단을 분류해보고자 하였다. 하지만, Median값이 6개로 여러개가 관측되는 상황이기 때문에 Median값에 해당하는 관측치들을 어떤 집단에 분류하느냐에 따라 분석결과가 달라지게 되는 문제가 존재하므로 바람속도와 오존량의 관계에 대한 사전지식을 가지고 분석을 진행하는 것이 더 의미있는 분석결과를 도출할 수 있을 것이라고 생각한다. (데이터의 수가 서로 동일하지 않다는 문제가 존재)\n\n#3번 통계청 자료 싸이트에서 교과서 4.6절의 자료를 최신 것으로 얻어 교과서에서의 분석을 따라하고 달라진 점들을 보고하라.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(ggplot2)\n# 교과서 자료 활용\npop2000<-read.csv(\"https://raw.githubusercontent.com/SangwonJu/data/0676d5a195bc0198085765d26b646351a858db74/%EA%B4%91%EC%97%AD%EC%8B%9C-%EA%B5%AC%20%EC%9D%B8%EA%B5%AC.csv\",header=T)\n\nstr(pop2000)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t74 obs. of  4 variables:\n $ 지역코드: int  1 1 1 1 1 1 1 1 1 1 ...\n $ 지역명  : chr  \"서울\" \"서울\" \"서울\" \"서울\" ...\n $ 구      : chr  \"종로구\" \"중구\" \"용산구\" \"성동구\" ...\n $ 인구    : int  168879 130370 226540 322990 380164 366282 440018 459011 340327 352098 ...\n```\n:::\n\n```{.r .cell-code}\n# 1) 광역시별로 상자그림을 그린다음 나란히 늘여놓은 그래프\nboxplot(pop2000$인구~pop2000$지역명)\n```\n\n::: {.cell-output-display}\n![](과제2_files/figure-html/unnamed-chunk-8-1.png){width=672}\n:::\n\n```{.r .cell-code}\nggplot(data=pop2000,aes(x=지역명,y=인구,fill=지역명))+\n  geom_boxplot()+\n  scale_y_continuous(labels = scales::comma)+\n  scale_fill_brewer(palette=\"Pastel1\")\n```\n\n::: {.cell-output-display}\n![](과제2_files/figure-html/unnamed-chunk-8-2.png){width=672}\n:::\n\n```{.r .cell-code}\n# 2) 가나다 순에서 지역코드 순으로\npop2000$시=ordered(reorder(pop2000$지역명,pop2000$지역코드))\nstr(pop2000)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t74 obs. of  5 variables:\n $ 지역코드: int  1 1 1 1 1 1 1 1 1 1 ...\n $ 지역명  : chr  \"서울\" \"서울\" \"서울\" \"서울\" ...\n $ 구      : chr  \"종로구\" \"중구\" \"용산구\" \"성동구\" ...\n $ 인구    : int  168879 130370 226540 322990 380164 366282 440018 459011 340327 352098 ...\n $ 시      : Ord.factor w/ 7 levels \"서울\"<\"부산\"<..: 1 1 1 1 1 1 1 1 1 1 ...\n```\n:::\n\n```{.r .cell-code}\nboxplot(pop2000$인구~pop2000$시)\n```\n\n::: {.cell-output-display}\n![](과제2_files/figure-html/unnamed-chunk-8-3.png){width=672}\n:::\n\n```{.r .cell-code}\nggplot(data=pop2000,aes(x=시,y=인구,fill=시))+\n  geom_boxplot()+\n  scale_y_continuous(labels = scales::comma)+\n  scale_fill_brewer(palette=\"Pastel1\")\n```\n\n::: {.cell-output-display}\n![](과제2_files/figure-html/unnamed-chunk-8-4.png){width=672}\n:::\n\n```{.r .cell-code}\n# 3)상자의 폭을 각 광역시의 구 수에 비례하게 표현한 그래프\nboxplot(pop2000$인구~pop2000$시,width=table(pop2000$시))\n```\n\n::: {.cell-output-display}\n![](과제2_files/figure-html/unnamed-chunk-8-5.png){width=672}\n:::\n\n```{.r .cell-code}\nmy_xlab<-paste(levels(pop2000$시),\"\\n(N=\",table(pop2000$시),\")\",sep=\"\")\nggplot(data=pop2000,aes(x=시,y=인구,fill=시))+\n  geom_boxplot(varwidth=T)+\n  scale_y_continuous(labels = scales::comma)+\n  scale_fill_brewer(palette=\"Pastel1\")+\n  scale_x_discrete(labels=my_xlab)\n```\n\n::: {.cell-output-display}\n![](과제2_files/figure-html/unnamed-chunk-8-6.png){width=672}\n:::\n\n```{.r .cell-code}\n# 2021년 2월 통계청 인구자료\npop2021<-read.csv(\"https://raw.githubusercontent.com/SangwonJu/data/main/2021.02%20pop.csv\",header=T)\n\nstr(pop2021)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t75 obs. of  6 variables:\n $ 지역코드: int  1 1 1 1 1 1 1 1 1 1 ...\n $ 지역명  : chr  \"서울\" \"서울\" \"서울\" \"서울\" ...\n $ 구      : chr  \"종로구\" \"중구\" \"용산구\" \"성동구\" ...\n $ 인구    : int  148884 124836 230113 292537 345248 341756 393933 437961 306639 323431 ...\n $ 남자인구: int  72372 61018 110646 142904 166535 169139 194665 211283 149427 157603 ...\n $ 여자인구: int  76512 63818 119467 149633 178713 172617 199268 226678 157212 165828 ...\n```\n:::\n\n```{.r .cell-code}\n# 1) 광역시별로 상자그림을 그린다음 나란히 늘여놓은 그래프\nboxplot(pop2021$인구~pop2021$지역명)\n```\n\n::: {.cell-output-display}\n![](과제2_files/figure-html/unnamed-chunk-8-7.png){width=672}\n:::\n\n```{.r .cell-code}\nggplot(data=pop2021,aes(x=지역명,y=인구,fill=지역명))+\n  geom_boxplot()+\n  scale_y_continuous(labels = scales::comma)+\n  scale_fill_brewer(palette=\"Pastel1\")\n```\n\n::: {.cell-output-display}\n![](과제2_files/figure-html/unnamed-chunk-8-8.png){width=672}\n:::\n\n```{.r .cell-code}\n# 2) 가나다 순에서 지역코드 순으로\n\npop2021$시=ordered(reorder(pop2021$지역명,pop2021$지역코드))\nstr(pop2021)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t75 obs. of  7 variables:\n $ 지역코드: int  1 1 1 1 1 1 1 1 1 1 ...\n $ 지역명  : chr  \"서울\" \"서울\" \"서울\" \"서울\" ...\n $ 구      : chr  \"종로구\" \"중구\" \"용산구\" \"성동구\" ...\n $ 인구    : int  148884 124836 230113 292537 345248 341756 393933 437961 306639 323431 ...\n $ 남자인구: int  72372 61018 110646 142904 166535 169139 194665 211283 149427 157603 ...\n $ 여자인구: int  76512 63818 119467 149633 178713 172617 199268 226678 157212 165828 ...\n $ 시      : Ord.factor w/ 8 levels \"서울\"<\"부산\"<..: 1 1 1 1 1 1 1 1 1 1 ...\n```\n:::\n\n```{.r .cell-code}\nboxplot(pop2021$인구~pop2021$시)\n```\n\n::: {.cell-output-display}\n![](과제2_files/figure-html/unnamed-chunk-8-9.png){width=672}\n:::\n\n```{.r .cell-code}\nggplot(data=pop2021,aes(x=시,y=인구,fill=시))+\n  geom_boxplot()+\n  scale_y_continuous(labels = scales::comma)+\n  scale_fill_brewer(palette=\"Pastel1\")\n```\n\n::: {.cell-output-display}\n![](과제2_files/figure-html/unnamed-chunk-8-10.png){width=672}\n:::\n\n```{.r .cell-code}\n# 3)상자의 폭을 각 광역시의 구 수에 비례하게 표현한 그래프\nboxplot(pop2021$인구~pop2021$시,width=table(pop2021$시))\n```\n\n::: {.cell-output-display}\n![](과제2_files/figure-html/unnamed-chunk-8-11.png){width=672}\n:::\n\n```{.r .cell-code}\nmy_xlab<-paste(levels(pop2021$시),\"\\n(N=\",table(pop2021$시),\")\",sep=\"\")\nggplot(data=pop2021,aes(x=시,y=인구,fill=시))+\n  geom_boxplot(varwidth=T)+\n  scale_y_continuous(labels = scales::comma)+\n  scale_fill_brewer(palette=\"Pastel1\")+\n  scale_x_discrete(labels=my_xlab)\n```\n\n::: {.cell-output-display}\n![](과제2_files/figure-html/unnamed-chunk-8-12.png){width=672}\n:::\n\n```{.r .cell-code}\n# Comparison\n\n\npop2021<-pop2021[c(1:4,7)]\n\npop2021$년도<-rep(2021,nrow(pop2021))\npop2000$년도<-rep(2000,nrow(pop2000))\nnew<-rbind(pop2000,pop2021)\nnew$년도<-as.factor(new$년도)\n\nggplot(data=new,aes(x=시,y=인구))+\n  geom_boxplot(aes(fill=년도),varwidth=T)+\n  scale_y_continuous(labels = scales::comma)+\n  scale_fill_brewer(palette=\"Pastel1\")+\n  scale_x_discrete(labels=my_xlab)\n```\n\n::: {.cell-output-display}\n![](과제2_files/figure-html/unnamed-chunk-8-13.png){width=672}\n:::\n:::\n",
    "supporting": [
      "과제2_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}